### ISSUE TITLE
Implementado linha para CPF/CNPJ

### ISSUE THREAD

**Issue by jonatasaraujo** [paghiper/whmcs#1]
@paghiper boa tarde,

De acordo com a documentação fiz a implementação no código da seguinte forma;;

customfields1 é o meu campo utilizado para capturar o CPF e o mesmo serve para o CNPJ.
`<input name='cpf' type='hidden' value='{$params['clientdetails']['customfields1']}' required/>
<input name='cnpj' type='hidden' value='{$params['clientdetails']['customfields1']}' />`

Ainda estou trabalhando na alteração do valor que eu recebi e taxa cobrada, está retornando a taxa que vocês cobram e não a taxa que eu informei.

Obrigado.

Att
Jônatas Araújo
www.designworld.com.br

**Comment by paghiper** [comment]
Olá Jonatas
Começamos a editar o nosso modulo para atender as normas de boleto em 2017, já temos o modulo quase pronto, e gostaria de compartilhar com você. Acesse o seu site: http://designworld.com.br/contato/ e enviei o modulo no email contato@......
Obrigado.

**Comment by MarksEliel** [comment]
@paghiper  Se não for pedir muito poderia enviar para nós?
www.m7web.com.br

**Comment by TecSecret** [comment]
Bom dia,

Poderiam por favor atualizar no repositório o módulo em vez de ficar enviando por e-mail ai todo mundo terá acesso.

Abraços

**Comment by MarksEliel** [comment]
@TecSecret realizei a minha própria modificação...
Segue o link: http://pastebin.com/7K78M1zp

Tem algumas alterações para serem feitas, pois fiz o módulo utilizando o mesmo campo para CNPJ e CPF, na linha 199 tem isso $CPF_CNPJ = $params['clientdetails']['customfields1'];

Você altera o customfields1 para o número do campo que vc está usando para CPF e CPNJ

Bom uso!

**Comment by tsabaia** [comment]
@TecSecret Tentei aqui e não rolou, o CPF/CNPJ aparece ao lado do botão de gerar boleto ao invés de criar um input.

**Comment by leonardoasb** [comment]
Alguma novidade sobre o envio do cpf/cnpf e o cliente poder ir direto para a tela do boleto?

**Comment by leonardoasb** [comment]
@paghiper pode me enviar o modulo novo?

**Comment by jonatasaraujo** [comment]
@leonardoasb já recebeu o módulo atualizado?
Não tenho acessado muito o GIT hoje que vi a quantidade de questionamentos 👍

**Comment by leonardoasb** [comment]
@jonatasaraujo recebi sim, já estou testando há alguns dias e até agora não tive problemas.

**Comment by henriqueccruz** [comment]
Pessoal, preparamos uma nova versão do plugin e vamos subir aqui no repositório amanhã.
Várias funções novas, entre elas, integração com um campo dinâmico para CPF/CNPJ.

O plugin trata o campo automaticamente e oferece um checkout 100% transparente, tanto para clientes Pessoa Física, quanto Pessoa Jurídica (nesse caso, a razão social é usada, para efeitos contábeis).

Vamos colocar aqui também, um tutorial de como criar o campo, caso vocês não tenham.

**Comment by henriqueccruz** [comment]
O módulo oficial versão 1.1 implementa isso.
Incluimos um assistente que retorna os campos na tela de configuração, daí é só usar.

Caso não tenha criado o campo ainda, você pode usar o tutorial que criamos:
https://github.com/paghiper/whmcs/wiki/Criando-o-campo-de-CPF-CNPJ
