### ISSUE TITLE
Checkout transparente

### ISSUE THREAD

**Issue by gheeenrique** [paghiper/whmcs#10]
Olá, fiz a instalação do modulo, mas quando clico em para gerar o boleto, ele abre na mesma página o boleto, assim não tem a possibilidade do cliente voltar ao meu site.

**Comment by henriqueccruz** [comment]
Isso é uma característica do checkout transparente, o cliente navega até o boleto sem precisar mudar de site, ou aba. Posso checar se é possível fazer com que abra em outra aba, mas antes preciso ter certeza sobre a compatibilidade com todas as versões do WHMCS

**Comment by Elicast** [comment]
no meu checkout transparente é direcionado a uma tela branca, o que pode ser isso?

**Comment by henriqueccruz** [comment]
@Elicast, checa o campo admin do WHMCS, ele precisa estar preenchido corretamente para a API Local do WHMCS funcionar. Além disso, cheque se estiver usando VestaCP, precisa atualizar seu httpd.conf pra permitir "CURLOPT_FOLLOWLOCATION".

Caso ainda tenha problemas, abra outro ticket por favor.

**Comment by Elicast** [comment]
realmente uso VestaCP, mas não tenho conhecimento para tal configuração, como eu colocaria e em quem parte ? Obrigado
