### ISSUE TITLE
Erro de transações no módulo

### ISSUE THREAD

**Issue by ricardomecca** [paghiper/whmcs#100]
Olá,
Anteriormente abri um Issue aqui no Github pois meu WHMCS não estava registrando as transações nas faturas, pois bem, foi sanado o problema e parecia estar ocorrendo tudo normalmente. Habilitei a parte PIX do módulo, e até então tudo retornou a não registrar novamente as transações, sendo que verifiquei a configuração dos módulos e está tudo perfeitamente configurado.

Tentei enviar um e-mail para suporte@paghiper.com mas parece que não estão recebendo enfim, não tive nenhuma resposta enviando os e-mails!

**Comment by AlexandreLage** [comment]
Será que o hype do PagHiper mal começou e já está acabando?
O site é um pouco amador.
A ideia e as soluções são boas?

Pelos issues tenho dúvidas. Só tem um participante desenvolvedor aqui?

Querem ajuda? haha

**Comment by ricardomecca** [comment]
PagHiper está no ramo a anos, acho que o fim dela está mais que longe. Não devemos generalizar problemas e levar isso a uma opinião concreta, uso por anos a plataforma e tive esses problemas atualmente em meu WHMCS pois atualizei ele e implementei o novo módulo, pode ter sido um erro meu mas me ajudaram a solucionar por e-mail.
PagHiper é a melhor atualmente, pois a tarifa de boleto confirmado é a mais baixa do mercado e não tem burocracias. Não me vejo abandonando esta incrível plataforma.

**Comment by souzadavi** [comment]
Realmente o site tem um design ultrapassado, mas o serviço esta longe de ser! Sempre que tem um problema o pessoal resolve bem rápido e com respostas satisfatórias. Para boletos e PIX no WHMCS acredito ser a melhor solução.

**Comment by henriqueccruz** [comment]
@ricardomecca e @souzadavi 
Agradecemos pelos comentários e por contarem com a Paghiper!

@souzadavi 
Sobre sua questão com as transações, o log ocorre no momento em que a Paghiper notifica a sua instalação do WHMCS de uma movimentação na transação. Nem sempre isso é instantâneo.

Tendo isso em mente, me tira uma dúvida: As faturas em que a transação não é registrada dão baixa normalmente?
Você nota que as transações são registradas após alguns minutos?

--

@AlexandreLage 
Existe alguma questão com que precise de suporte? Nos colocamos a disposição pra te auxiliar.

**Comment by ricardomecca** [comment]
@henriqueccruz 
O problema era comigo, em contato via e-mail acredito que solucionado! Se possível encerrar este issue.

Acredito que o problema estava que meu WHMCS pois estava configurado HTTP no URL do Sistema, mudei HTTPS e também removi o uso do CloudFlare pois pode ter dado conflito também. Mas resolvido, agradecido novamente!

**Comment by henriqueccruz** [comment]
@ricardomecca 
Ah sim, que bom que resolveu. Não temos problemas de compatibilidade com Cloudflare.
Sobre o HTTP, também não há problema. Normalmente o problema ocorre quando a URL do WHMCS está configurada para HTTP e existe um redirect (normalmente via .htaccess) para HTTPS

Não permitimos redirects no endpoint que recebe notificações, por motivos de segurança.
Se tiver mais alguma outra questão, fique 100% a vontade para abrir outro ticket.
Fechando este por questões de organização.
