### ISSUE TITLE
Faturas duplicadas.

### ISSUE THREAD

**Issue by danilobsantos** [paghiper/whmcs#101]
Está gerando múltiplas faturas para um mesmo pedido e quando o cliente efetua o pagamento continua gerando fatura.

**Comment by henriqueccruz** [comment]
Olá @danilobsantos 
Estamos falando do plug-in da PagHiper para WHMCS?
Ou você usa a integração com o Woocommerce?

**Comment by henriqueccruz** [comment]
Confirma pra gente por favor qual versão do WHMCS, qual versão do plugin está usando
Se tiver um passo-a-passo de como duplicar as transações, melhor ainda. Ou um link onde possamos testar.

**Comment by danilobsantos** [comment]
WHMCS 8.1.1 e plugin 2.1. Ele gera um boleto a cada e-mail enviado, mesmo que este já tenha sido gerada no e-mail anterior.

**Comment by henriqueccruz** [comment]
@danilobsantos, esse comportamento certamente não é o esperado.
Você faria alguns testes pra encontrarmos a causa? 

1. Tenta acessar o link de um boleto ja emitido antes
2. Dá uma olhada nos logs de portais de pagamentos
3. Veja se há alguma mensagem relacionada a emissão do boleto da fatura relacionada

Adicionalmente, checa se o banco de dados do seu WHMCS tem uma tabela chamada mod_paghiper
Aguardamos seu retorno para seguir com o diagnóstico.

**Comment by henriqueccruz** [comment]
Como não conseguimos mais interação no ticket, estamos fechando.
Caso queira retomar, peço a gentileza de abrir novo ticket.
