### ISSUE TITLE
Erro ao Marcar Fatura como Pago

### ISSUE THREAD

**Issue by lyno89** [paghiper/whmcs#104]
Olá estou encontrando seguinte arro no WHMCS ao Marcar fatura como Pago

Error: Call to undefined function log_status_to_db() in /home1/ibisys93/public_html/includes/hooks/cancel_paghiper_slip.php:74
Stack trace:
#0 /home1/ibisys93/public_html/vendor/whmcs/whmcs-foundation/lib/Hook/Manager.php(0): cancel_paghiper_slips(Array)
#1 /home1/ibisys93/public_html/vendor/illuminate/support/Facades/Facade.php(261): WHMCS\Hook\Manager->run('InvoicePaid', Array, false)
#2 /home1/ibisys93/public_html/includes/functions.php(0): Illuminate\Support\Facades\Facade::__callStatic('run', Array)
#3 /home1/ibisys93/public_html/includes/invoicefunctions.php(0): run_hook('InvoicePaid', Array)
#4 /home1/ibisys93/public_html/vendor/whmcs/whmcs-foundation/lib/Billing/Invoice.php(0): processPaidInvoice(2775, false, Object(WHMCS\Carbon))
#5 /home1/ibisys93/public_html/includes/invoicefunctions.php(0): WHMCS\Billing\Invoice->addPayment(39.9, '', '', 'paghiper', false, Object(WHMCS\Carbon))
#6 /home1/ibisys93/public_html/adm_folder/clientsinvoices.php(0): addInvoicePayment('2775', '', 39.9, '', 'paghiper')
#7 {main}

![Erro WHMCS PagHiper](https://user-images.githubusercontent.com/49218298/121683355-a4463580-ca93-11eb-9ff0-2fcc052408f3.jpeg)

**Comment by henriqueccruz** [comment]
Olá @lyno89 , boa noite.
Pode nos confirmar qual é a versão ativa do plug-in? Você encontra essa informação no seu painel mesmo, na seção Opções > Pagamento > Portais para Pagamento > Paghiper (PIX ou Boleto)
Aguardamos seu retorno.

**Comment by lyno89** [comment]
Olá bom dia 
Versão 2.2 , este erro começou aparecer após fazer atualização do mesmo

**Comment by henriqueccruz** [comment]
Checa por favor se seu arquivo abaixo também foi atualizado apra a versão 2.2:
`/includes/hooks/cancel_paghiper_slip.php`

Você pode ver essa informação no cabeçalho do arquivo. As primeiras linhas devem ser:
`<?php
/**
 * Cancela boletos bancários não-pagos, atrelados a uma fatura cancelada ou paga.
 * 
 * @package    PagHiper para WHMCS
 * @version    2.2`

**Comment by paulonichio** [comment]
@henriqueccruz, boa tarde! Tudo bem?

Apenas para dar seguimento ao assunto, após atualizarmos aqui, também passamos a receber o mesmo erro ao cancelar um boleto via admin.
Verifiquei o arquivo /includes/hooks/cancel_paghiper_slip.php e sim, o mesmo encontra-se na versão 2.2.

O problema passou a acontecer após a atualização para a última versão, como mencionado pelo @lyno89 acima.
