### ISSUE TITLE
Erro na emissão do boleto após atualização

### ISSUE THREAD

**Issue by souzadavi** [paghiper/whmcs#106]
Olá bom dia. Após atualizar para o novo release. Versão 2.2.1. quando tenta emitir o boleto da um erro, depois atualiza a página o boleto gera normal.

Ou seja, todo primeiro acesso da erro no boleto, após acessar pela segunda vez o boleto é gerado. No log do WHMCS da esta mensagem de erro.
![Screenshot from 2021-06-21 11-00-31](https://user-images.githubusercontent.com/636225/122775330-65c52d80-d280-11eb-88a3-475ac1f71754.png)

alguém sabe o que pode ser?

Obrigado.

**Comment by henriqueccruz** [comment]
Olá @souzadavi 
Seu problema ainda persiste?
Pode ser questão de permissão de acesso as tabelas do banco de dados (usuário MySQL configurado nas opções do WHMCS não tem permissão pra modificação/criação de tabelas).

Consegue confirmar pra gente?
