### ISSUE TITLE
Pagamentos Duplicados

### ISSUE THREAD

**Issue by ddrhost** [paghiper/whmcs#107]
Olá. Em algumas situações a confirmação do pagamento continua sendo duplicada, adicionando créditos aos clientes.

Estamos utilizando a versão mais recente do módulo.

**Comment by linkoficial** [comment]
Já tive este mesmo problema aqui algumas poucas vezes, inclusive com versões anteriores. No nosso caso não era adicionado crédito, simplesmente era adicionado o período para próxima fatura.
Exemplo, se o cliente pagou a fatura que vencia dia 15/07 a próxima fatura fica para 15/09, ganhando assim o cliente "1 mês grátis". Nestes casos não houve pagamento duplicado por parte do cliente.

**Comment by henriqueccruz** [comment]
Uma update foi lançada a pouco, homologada e testada. Ela resolve os pontos citados nesta issue.
Pedimos sinceras desculpas pelo transtorno causado.

#114
