### ISSUE TITLE
Erro ao pagar via pix após o vencimento

### ISSUE THREAD

**Issue by russo1** [paghiper/whmcs#108]
Bom dia, estou recebendo muitas reclamações de clientes que tentam pagar via Pix após passar da data do vencimento da fatura

dá erro no aplicativo do banco ao tentar pagar uma fatura fora do vencimento impedindo do cliente realizar o pagamento

estou tendo que cancelar manualmente o pix pelo painel do paghiper e alterar o vencimento da fatura para o cliente conseguir pagar

**Comment by henriqueccruz** [comment]
Olá @russo1 , boa tarde.
Me tira uma dúvida: Você utiliza a opção de tolerância para pagamento após vencimento?
Se sim, como está configurada essa opção (para quantos dias) nas configurações do plug-in?

Aguardamos seu retorno.

**Comment by russo1** [comment]
eu uso a configuração de 3 dias de tolerância para pagamento de boletos, o modulo pix não tem essa configuração

aumentei a tolerância no modulo de boleto para 10 dias para testar se vai resolver o problema, mas lembrando que o que eu relatei ocorre para pagamentos via PIX

**Comment by henriqueccruz** [comment]
Basicamente, no seu caso, os clientes continuam vendo o PIX vencido ao acessarem o endpoint de emissão de nova transação ou ao receberem e-mails de lembrete?

**Comment by russo1** [comment]
Ao abrir a fatura e clicar para pagar via pix, o cliente continua para o pagamento do pix vencido, só gera um novo pix se eu alterar o vencimento da fatura 

Ao tentar pagar pelo aplicativo do banco via qrcode ou pix copia e cola o cliente recebe uma mensagem de pix inválido

**Comment by henriqueccruz** [comment]
@russo1 
Do que se tratava o seu problema? Pergunto para termos melhor entendimento sobre o ocorrido.

**Comment by russo1** [comment]
O problema é que se passar do vencimento da fatura o cliente não consegue pagar via PIX

Exemplo: o vencimento da fatura foi ontem dia 15/08
Se o cliente tentar pagar hoje, dia 16/08 vai dar erro no PIX

Só consegue pagar se eu cancelar o pix aberto pelo painel da paghiper, mudar o vencimento da fatura no painel do meu whmcs para o dia 16/08 para ele conseguir gerar um novo pix e realizar o pagamento

**Comment by henriqueccruz** [comment]
Vamos tentar replicar por aqui. Reabrindo o ticket até finalizar a checagem.
Caso consigamos replicar, faremos um update no módulo para corrigir.

**Comment by russo1** [comment]
Ok, estava respondendo pelo celular e não notei que havia fechado o ticket, cliquei no botão errado.

**Comment by russo1** [comment]
um cliente acabou de me relatar que está tendo o problema que falei aqui
olhe o erro que dá no app do banco: https://prnt.sc/1pyw1q8

fatura do cliente com vencimento: https://prnt.sc/1pywa8f

**Comment by russo1** [comment]
outro cliente informando o problema: https://prnt.sc/1q71wwk

OBS: já estou passando por ele problema há mais ou menos 2 meses, mas só informei agora pois tem muitos clientes atrasando o pagamento, ai o problema está mais frequente..

**Comment by henriqueccruz** [comment]
@russo1 Hoje a tarde terei uma potencial solução para o problema.
Vou mandar um gist e você me diz se resolveu seu caso. Podemos fazer assim?

**Comment by russo1** [comment]
Claro!
estou no aguardo.

**Comment by henriqueccruz** [comment]
@russo1 
Como acabei precisando atualizar mais de um arquivo, subi em um repositório de dev.
Pegue a versão corrente [nesse repositório](https://github.com/henriqueccruz/whmcs-paghiper) por favor.

Arquivos atualizados:
/modules/gateways/paghiper/inc/helpers/gateway_functions.php
/modules/gateways/paghiper/inc/helpers/process_payment.php

Nos avise se funcionou como esperado.
Aguardamos seu retorno.

**Comment by russo1** [comment]
Atualizei os arquivos que informou só que vai ser um pouco difícil para eu saber se resolveu, já que dependo da reclamação de clientes para saber e pode demorar alguns dias para isso
creio que você tenha feito algum teste, se resolveu para você provavelmente irá resolver o problema para mim.

**Comment by henriqueccruz** [comment]
Boa tarde @russo1 
Temos mais algum incidente envolvendo essa issue?

**Comment by russo1** [comment]
até o momento não, caso volte a ocorrer eu abro o ticket novamente
obrigado!!
