### ISSUE TITLE
Problema com SSL

### ISSUE THREAD

**Issue by ctnsantos** [paghiper/whmcs#109]
Estou com problema tanto no módulo de boleto bancário quanto o PIX.

Quando o cliente está na fatura e clica para efetuar o pagamento a seguinte mensagem é exibida para o cliente:

As informações que você está prestes a enviar não estão protegidas
Como o formulário é enviado por uma conexão que não é segura, suas informações ficarão visíveis para outras pessoas.

''Sua conexão com este site não é segura''

Alguém poderia me auxiliar? Meu site já possui Certificado SSL.

**Comment by sistemaweb** [comment]
estou com o mesmo problema, você conseguiu resolver? @ctnsantos @henriqueccruz consegue nos ajudar? eu imagino que colocar um https:// em algum lugar do arquivo viewinvoice.php, mas não sei onde exatamente

**Comment by fernandogobah** [comment]
Man, eu fiz algumas alterações funcionou até certo ponto, daí gerou outro erro. Acionei o suporte, eles foram corrigindo a cada erro que aparecia até que eles mesmo desistiram e pediram pra aguardar o lançamento da nova versão que deveria ser compatível com a versão 8 do PHP.
Eu sigo que deveria, pois eles falaram que era pra ser lançando no final de novembro e até agora nada.
Resultado final, estou saindo da plataforma e migrando para uma que tenha suporte.

**Comment by sistemaweb** [comment]
Eita, blz, valeu ai!

**Comment by sistemaweb** [comment]
@henriqueccruz deu certo, obrigado

@fernandogobah só colocar o https:// na URL das configurações gerais do WHMCS deu certo pra mim
