### ISSUE TITLE
Gerar email de "visualizar boleto" AUTOMATICAMENTE antes da fatura vencer.

### ISSUE THREAD

**Issue by aespa** [paghiper/whmcs#11]
Muito boa a implementação com o Paghiper, parabéns! Só uma dúvida: não teria como GERAR E ENVIAR AUTOMATICAMENTE aquele segundo email intitulado:
"Seu boleto do pedido XXXX foi gerado com sucesso. Você poderá gerar seu boleto clicando no botão abaixo: Visualizar boleto" 
Exemplo: alguns dias antes da fatura vencer, ao invés de enviar um e-mail de lembrete de vencimento da fatura, já enviar esse email com o link para gerar o boleto?

Agradeço pela ajuda.

Jones

**Comment by henriqueccruz** [comment]
Olá @aespa, temos isso planejado e em progresso para a próxima versão do plug-in, que deve sair nos próximos dias. A estimativa é entre uma e duas semanas.
Atualizo este ticket assim que tivermos a versão disponível para download.

**Comment by deguirbr** [comment]
Interessante o recurso.

**Comment by ddrhost** [comment]
Implementado. Verifique na nova atualização disponibilizada.
