### ISSUE TITLE
Boleto da erro quando acessa pela primeira vez o link do boleto

### ISSUE THREAD

**Issue by souzadavi** [paghiper/whmcs#112]
O usuário acessa a fatura do WHMCS dentro da fatura no  botão de gerar boleto, quando clica pela primeira vez no botão da erro. Para o boleto aparecer tem que fechar a página do boleto com erro e depois clicar no botão da fatura de gerar boleto novamente. Abaixo segue link de um boleto que deu erro e agora consegue acessar normal.

Obs.: frequentemente temos cliente reclamando deste problema, parece um problema besta mais gera desconforto para o usuário e demanda de suporte para a gente. Na tela do erro poderia aparecer uma informação do tipo: Erro ao carregar o boleto, por favor tente atualizar esta página.

Obrigado.

![Screenshot from 2021-11-28 20-28-59](https://user-images.githubusercontent.com/636225/143790826-64a86eb0-534c-487f-8c4b-ba3dcdea72ee.png)

**Comment by souzadavi** [comment]
Continuo com o problema, alguém conseguiu reproduzir o erro?


obs.: se atualizar a página o boleto aparece, apenas na primeira tentativa de carregamento do boleto.

**Comment by souzadavi** [comment]
Fiz uma solução para tentar evitar um erro por parte dos usuários adicionando um link para atualizar a página:

ARQUIVO:
https://github.com/paghiper/whmcs/blob/master/modules/gateways/paghiper/inc/helpers/gateway_functions.php#L501

ALTEREI em: 
        $title = 'Ops! Não foi possível emitir o '.((!$is_pix) ? 'boleto bancário' : 'PIX').'.';
        $message = 'Número de CPF/CNPJ inválido! Por favor atualize seus dados ou entre em contato com o suporte';
POR
        $title = 'Desculpe, houve um erro ao carregar esta página!';
        $message = 'Para resolver <a href="javascript:window.location.href=window.location.href">por favor atualize esta página</a> ou entre em contato com o suporte';

**Comment by henriqueccruz** [comment]
Acabamos por não incorporar o pullrequest mencionado pelo amigo acima, optamos por lidar com a issue de outra maneira.
Uma update foi lançada a pouco, homologada e testada. Ela resolve os pontos citados nesta issue.
