### ISSUE TITLE
Nome Empresa vazio e CNPJ preenchido - CPF/CNPJ Inválido. Atualize seus dados cadastrais

### ISSUE THREAD

**Issue by paulonichio** [paghiper/whmcs#115]
Fiz a atualização do módulo para a versão 2.3 e passei a receber o seguinte problema.

Se o cliente realiza um cadastro e não informa um **nome de empresa** (fantasia) - o sistema acusa que "CPF ou CNPJ inválido, atualize seus dados cadastrais.".
Ao colocar qualquer coisa no campo **Nome da Empresa**, o sistema deixa prosseguir com o pagamento normalmente.

Não sei se isto é um recurso novo ou não mas, começou a apresentar tal problema nesta última versão.

Por hora, retornamos a versão anterior que tem funcionado normalmente.

Se precisarem de informações adicionais, estou à disposição!

**Comment by henriqueccruz** [comment]
Olá @paulonichio , boa tarde
Nos tire uma dúvida: Você tem campos separados para CPF e CNPJ?
Para o cliente usado como caso-teste, estão informando CPF, CNPJ ou ambos?

**Comment by paulonichio** [comment]
Oi @henriqueccruz tudo certo?

Não, é o mesmo campo tanto para CPF quanto para CNPJ.
Resumindo o que aconteceu - o cliente efetuou uma compra, inseriu o CNPJ dele no ato da contratação e selecionou PIX (porém o boleto também de erro).
Ao finalizar a compra, apresentou erro 500 no servidor e ao abrir a página da fatura era exibida a mensagem "CPF ou CNPJ inválido, atualize seus dados cadastrais.". Coloquei outro CNPJ e o problema persistiu. Coloquei meu CPF e voltou a funcionar. Com isto, fiz um teste de colocar um nome da empresa no campo correspondente e voltou a funcionar. Retirei o nome da empresa voltou a mensagem de CPF ou CNPJ Inválido.

Ao voltar a versão antiga, o erro 500 na finalização não ocorreu mais também.

**Comment by henriqueccruz** [comment]
O problema citado ocorre quando se usa um número de CNPJ, sem nome de empresa ou razão social no checkout.
É comportamento esperado do plugin, pra evitar que o título de pagamento saia com nome de pessoa física mas atribuido a uma pessoa física.
Nas configurações da versão nova, temos instruções sobre como configurar o campo de razão social.

Seu checkout tem campo de "Empresa"?

**Comment by paulonichio** [comment]
Ah certo, eu vi nas configurações mas não preenchi pois não usamos o campo de nome da empresa/fantasia (tanto que o campo padrão do WHMCS para o nome da empresa deixamos oculto no formulário de compra). 
Vamos verificar Uma alternativa de contornar este problema.

**Comment by henriqueccruz** [comment]
O problema informado só ocorre quando as seguintes condições ocorrem juntas:
- Campo de CPF/CNPJ é o mesmo
- Número informado é formato CNPJ
- Não há campo de razão social/nome da empresa ou ele está vazio

Uma alternativa simples é informar número de CPF ao invés de CNPJ para o caso de não ter nome de empresa informado... Ou preencher o campo de empresa

Vamos checar do nosso lado também, para que casos como esse não passem na validação de checkout. Isso vai ajudar a reduzir erros e confusões com a base de clientes.

**Comment by linkoficial** [comment]
Mesmo problema aqui, usamos o campo Empresa, como já de padrão no WHMCS, mas talvez pelo WHMCS dizer que é "opcional", alguns clientes acabam por preencher no campo nome/sobrenome a informação da empresa. Acredito que fazer um método onde o script use o campo do nome caso o campo empresa esteja em branco seria a melhor opção.

**Comment by henriqueccruz** [comment]
Na verdade não há problema em usar o campo empresa.
A questão é quando o campo empresa está sendo usado e não temos um CNPJ, o que configura cadastro inconsistente
A versão nova do plugin implementa checagens por esse tipo de inconsistência no checkout para evitar novos casos, no entanto, os anteriores devem ser resolvidos.

**Comment by souzadavi** [comment]
@henriqueccruz a mensagem de erro poderia tratar melhor o motivo do erro e informar qual o campo errado, temos este problema por aqui tbm várias vezes, mostrar que o erro é no CPF ou CNPJ, mas na realidade é a falta do campo razão social ou nome da empresa do WHMCS.

**Comment by paulonichio** [comment]
> @henriqueccruz a mensagem de erro poderia tratar melhor o motivo do erro e informar qual o campo errado, temos este problema por aqui tbm várias vezes, mostrar que o erro é no CPF ou CNPJ, mas na realidade é a falta do campo razão social ou nome da empresa do WHMCS.

Concordo plenamente. Por este motivo sigo na versão antiga do módulo ainda. Do jeito que está, fica inviável deixar para o cliente por conta da alta demanda de chamados para ficar arrumando cadastro.

**Comment by hostsr** [comment]
Boa noite Henrique e a todos 
Estou a dias com o mesmo problema inclusive estou a alguns dias com o pessoal da Paghiper sem sucesso na correção. Quando uso a versão 2.2.1  funciona perfeitamente, inclusive atualizei para a última versão do WHMCS na possibilidade de solução.
No meu caso até achamos que poderia ser os campos já que usamos um campo que não foi marcado onde foi criado o campo CNPJ separado só para consultas dos atendentes com informações da Receita Federal, mas o campo utilizado a anos é o CPF/CNPJ campo único como um dos colega já sitou acima.
Se entendi sua explicação para empresas teremos que colocar o nome da empresa no campo fantasia mais isso envolveria milhares de cadastros concorda.

Fico como os colegas aguardando uma solução.
Enquanto isso vou deixar a versão 2.21

**Comment by hostsr** [comment]
Henrique 

Não se ajuda
Mais se gerar na versão 2.21 e depois mudar para a versão nova o erro some para boletos já emitidos, mais permanece para os novos.
Ou seja parece que depois que foi gerado e tenta a reemissão o erro não da mais só na primeira emissão

**Comment by henriqueccruz** [comment]
Olá pessoal, boa tarde.
Temos várias correções nesse sentido implementadas na v2.3.
A versão mais recente, v2.4, implementa mais correções, melhorias e suporte total a PHP8.1.
Peço a gentileza de atualizarem e, caso tenham mais questões, abram novo ticket.
Obrigado!
