### ISSUE TITLE
Módulo não envia boleto no PDF

### ISSUE THREAD

**Issue by fabwebbr** [paghiper/whmcs#117]
Voltamos a usar o módulo para recebimento via Paghiper, mas não tenho obtido sucesso em enviar o boleto/PIX anexo à fatura do cliente.
Fiz o include no arquivo invoicepdf.tpl do tema que usamos e ele está no topo do arquivo (antes da abertura do php original), mas não funciona. O envio da linha digitável no corpo do e-mail está indo corretamente.  No PDF também não ocorre nenhum erro.

As versões que usamos
PHP: 7.4
WHMCS: 8.4.1

Alguém já passou por isso?

**Comment by h2kdev** [comment]
Olá @fabwebbr - tenho o mesmo problema por aqui! no meu caso, a cada 30 invoices gerados, apenas 2 ou 3 anexam o boleto no PDF, de forma bem aleatória. Em alguns casos (quando a cron roda), nunca funciona, em outros, ocorre de forma intermitente. Eu achava que era algum problema com o ambiente, mas subi uma outra VPS só para o WHMCS, em outro IP, etc.. e ocorre o mesmo comportamento que você descreveu.

**Comment by souzadavi** [comment]
@h2kdev vc consegue gerar o boleto pela fatura destes clientes que não enviaram o boleto?

**Comment by h2kdev** [comment]
> @h2kdev vc consegue gerar o boleto pela fatura destes clientes que não enviaram o boleto?

Sim, manualmente sim. Apenas pela cron é que ocorrer essa intermitência. 

Mas quando é feito (gerado) manualmente, todos eles vão com o boleto no PDF.

**Comment by henriqueccruz** [comment]
Olá pessoal, boa tarde
Teremos uma update abordando esses pontos sendo lançada na próxima semana.
Atualizaremos este ticket avisando sobre o release.

**Comment by rbaldasso** [comment]
@henriqueccruz tem algum update relacionado a esse problema? Notei que no thema Lagom, ele acaba sobreescrevendo todo o PDF da fatura e envia só o boleto, não envia o resto do arquivo.

**Comment by henriqueccruz** [comment]
To: @fabwebbr 
CC: @h2kdev 

O problema citado por você se deve a um request HTTP que fazemos durante a integração nos PDFs.
Identificamos que, dependendo das configurações do servidor HTTP, essa etapa pode se tornar problemática, especialmente se a CRON gerar muitas faturas de uma vez e o server não estiver preparado para suportar muitos requests.

Ja temos uma mudança nesse sentido, em algumas semanas estará disponível.
Obrigado por reportar. Manterei esse ticket aberto para atualizações.

**Comment by adam-mazzei** [comment]
Bom dia pessoal. Alguma novidade nessa situação?
Quando roda o cron do WHMCS, o modulo inclui o boleto anexo na fatura apenas na 1ª.
Quando envia manualmente, vai certinho.
Ex.: No cron gerou 6 faturas, apenas a primeira que foi gerada foi com o boleto anexo, mas todos os 6 boletos foram gerados no PagHiper. Esses que não foram anexados, tbm não estão no diretório \modules\gateways\paghiper\tmp\billets
Nos logs do portais, todos os 6 tem a urlPagamento certinho.

**Comment by h2kdev** [comment]
> To: @fabwebbr CC: @h2kdev
> 
> O problema citado por você se deve a um request HTTP que fazemos durante a integração nos PDFs. Identificamos que, dependendo das configurações do servidor HTTP, essa etapa pode se tornar problemática, especialmente se a CRON gerar muitas faturas de uma vez e o server não estiver preparado para suportar muitos requests.
> 
> Ja temos uma mudança nesse sentido, em algumas semanas estará disponível. Obrigado por reportar. Manterei esse ticket aberto para atualizações.

Oi Henrique, tudo bem? Temos algum update desta issue? Há algo que possamos fazer no ambiente (servidor) para que funcione corretamente essa questão dos requests? Obrigado.

**Comment by henriqueccruz** [comment]
Olá pessoal, boa tarde
Em aprox. 1 semana teremos uma update que aborda essa questão definitivamente.
Vamos remover esse request HTTP e fazer isso usando um método mais estável.

**Comment by h2kdev** [comment]
> Olá pessoal, boa tarde Em aprox. 1 semana teremos uma update que aborda essa questão definitivamente. Vamos remover esse request HTTP e fazer isso usando um método mais estável.

Olá Henrique, teria algum paliativo que podemos aplicar no ambiente (servidor), que amenize esse problema enquanto o update não sai?

**Comment by h2kdev** [comment]
> Olá pessoal, boa tarde Em aprox. 1 semana teremos uma update que aborda essa questão definitivamente. Vamos remover esse request HTTP e fazer isso usando um método mais estável.

Nenhum update nessa issue ainda?

**Comment by thigas88** [comment]
Olá Henrique, teria algum paliativo que podemos aplicar no ambiente (servidor), que amenize esse problema enquanto o update não sai?

**Comment by thigas88** [comment]
> Olá pessoal, boa tarde Em aprox. 1 semana teremos uma update que aborda essa questão definitivamente. Vamos remover esse request HTTP e fazer isso usando um método mais estável.

Olá Henrique, teria algum paliativo que podemos aplicar no ambiente (servidor), que amenize esse problema enquanto o update não sai?

**Comment by h2kdev** [comment]
> Olá pessoal, boa tarde Em aprox. 1 semana teremos uma update que aborda essa questão definitivamente. Vamos remover esse request HTTP e fazer isso usando um método mais estável.

Oi @henriqueccruz , tudo bem? Temos algum update desta issue? Há algo que possamos fazer no ambiente (servidor) para que funcione corretamente essa questão dos requests? Obrigado.

**Comment by henriqueccruz** [comment]
Acabamos de lançar uma update que remove esse request HTTP
Levou um pouco mais de tempo que o esperado pra validarmos mas vou fechar esse ticket e pedir pra, caso tenham problemas com a update nova, abram nova issue here para acompanharmos
Obrigado a todos por reportarem.
