### ISSUE TITLE
WHMCS PHP 8.1 validate_paghiper_taxid.php:23

### ISSUE THREAD

**Issue by maisondasilva** [paghiper/whmcs#118]
Whoops\Exception\ErrorException: Unparenthesized `a ? b : c ? d : e` is not supported. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in /home/XXXXXXX/public_html/includes/hooks/validate_paghiper_taxid.php:23

Stack trace:
#0 /home/xxxxxxxx/public_html/vendor/whmcs/whmcs-foundation/lib/Utility/Error/Run.php(0): WHMCS\Utility\Error\Run->handleError(64, 'Unparenthesized...', '/home/xxxxxxxxxxx/...', 23)
#1 [internal function]: WHMCS\Utility\Error\Run->handleShutdown()
#2 {main}

**Comment by fernandogobah** [comment]
+1

**Comment by maisondasilva** [comment]
> +1

Segue o arquivo enviado por eles para a solução.
[validate_paghiper_taxid.zip](https://github.com/paghiper/whmcs/files/9944966/validate_paghiper_taxid.zip)

**Comment by fernandogobah** [comment]
Valeu @maisondasilva

**Comment by henriqueccruz** [comment]
Olá pessoal. Essa lógica foi encapsulada em uma função (é utilizada em diversos arquivos e pontos diferentes da regra de negócio).
A v2.4.0 incorpora essas mudanças junto com suporte a PHP 8.1.
Obrigado pela paciência.
