### ISSUE TITLE
Retorno Automático não Funciona

### ISSUE THREAD

**Issue by MarksEliel** [paghiper/whmcs#12]
Olá, desde que atualizei o módulo o Retorno Automático não funciona.
Esperei dois dias após o boleto ser compensado mais o status da fatura continua como Não Pago.

**Comment by henriqueccruz** [comment]
Olá @MarksEliel, o problema persiste?
Gostariamos de investigar, caso o retorno não esteja funcionando para você.

**Comment by MarksEliel** [comment]
Olá @henriqueccruz  continua sem funcionar :/

**Comment by henriqueccruz** [comment]
@MarksEliel, checa se o usuário designado na página de configurações tem permissões para dar baixa em faturas. Pode ser um firewall bloqueando o post de retorno também.

Desde quando você encontra este problema?

**Comment by MarksEliel** [comment]
Desde que instalei o módulo de vocês, quando eu tinha o outro módulo(Desenvolvido pela CompuLabs) funcionava normalmente.

**Comment by MarksEliel** [comment]
Não encontrei nenhum bloqueio quanto ao administrador, só tenho um administrador e ele tem permissão para tudo.

**Comment by henriqueccruz** [comment]
Na versão 1.1, tinhamos um problema ondea URL do sistema não era retornada caso o WHMCS estivesse instalado em subdiretório.
A versão mais recente é a 1.12. Checa se está utilizando a última versão por favor.

**Comment by MarksEliel** [comment]
Meu WHMCS está em subdiretório, acabei de verificar e a versão é a 1.12

**Comment by henriqueccruz** [comment]
Se você estiver utilizando checkout transparente, pode ser que o plugin esteja enviando sua URL de retorno sem a base do domínio.
Sua instalação do WHMCS não usa SSL, correto?

**Comment by MarksEliel** [comment]
Estou usando o Checkout Transparente
Na URL principal estava com https:// mais no campo SSL não tinha nada.
Acha que pode ser isso?

**Comment by henriqueccruz** [comment]
Tenho quase certeza. Ja reescrevemos a query que busca a URL do sistema quando o checkout transparente está ativado, para evitar que isso aconteça. Preencher o campo SSL resolverá isso até a próxima versão ser lançada.

**Comment by MarksEliel** [comment]
Ok, irei aguardar o próximo pagamento do cliente para que eu possa retornar aqui e deixar meu feedback.

**Comment by henriqueccruz** [comment]
Até lá, você pode preencher o campo e emitir uma fatura de teste. Caso o retorno esteja chegando corretamente, a PagHiper enviará um post de retorno, informando que o boleto foi gerado. Isso criará uma entrada de log dentro da fatura no WHMCS.

**Comment by MarksEliel** [comment]
Deveria aparecer algo nas Transações né quando abrisse o boleto?

**Comment by MarksEliel** [comment]
Verificando os logs das transações vejo esse erro: Não foi possível gravar os dados no banco.

**Comment by henriqueccruz** [comment]
Você está com esse problema mesmo depois de preencher o campo de SSL nas configurações?

**Comment by MarksEliel** [comment]
Sim

**Comment by henriqueccruz** [comment]
@MarksEliel, fiz uma atualização no método de definição da URL do sistema.
Você pode baixar novamente o plug-in e substituir o que está instalado no seu WHMCS.

Confirme se isso resolveu seu problema por favor? Estamos monitorando para resolver isso o quanto antes.

**Comment by MarksEliel** [comment]
Fatal error: Call to undefined function get_system_url() in /modules/gateways/paghiper.php 211

**Comment by henriqueccruz** [comment]
Me esqueci de atualizar essa linha, desculpe. Acabei de dar um commit atualizando isso.
Tenta de novo por favor.

**Comment by MarksEliel** [comment]
http://prntscr.com/g1wvs9

**Comment by henriqueccruz** [comment]
Interessante. Atualiza sua linha 211, substituindo essa linha com a linha abaixo por favor. Isso deve resolver o erro 500 e te dar o bugfix da ultima versão.
`$systemurl = $params['systemurl'];`

**Comment by MarksEliel** [comment]
Resolveu o Internal Server Error

**Comment by henriqueccruz** [comment]
Ótimo. O post de retorno da PagHiper deve chegar em breve, assim que isso acontecer, o plugin criará um item no log de transações dentro da própria fatura, informando que o boleto foi gerado.

**Comment by MarksEliel** [comment]
Recebi deste modo, está correto?
http://prntscr.com/g1x5qz

**Comment by henriqueccruz** [comment]
Sim, esse é o comportamento esperado do plugin. O prefixo é o ID da Transação, assim você consegue rastrear o boleto dentro do painel da PagHiper. Outros itens de log serão criados, de acordo com a data de vencimento, pagamento do cliente e/ou cancelamento do boleto.

**Comment by henriqueccruz** [comment]
@MarksEliel, quando puder, nos diga se isso resolveu seu problema definitivamente por favor.

**Comment by Rhenan** [comment]
Pra mim também não esta mais funcionando o retorno das transações, parou de funcionar após atualizar para a nova versão

**Comment by MarksEliel** [comment]
Pensei que havia resolvido, mais não resolveu, já recebi dois pagamentos e nenhum foi confirmado automaticamente.

**Comment by Rhenan** [comment]
Eu baixei a ultima realese e pra mim resolveu, voltou a aparecer as trasações normalmente...

https://github.com/paghiper/whmcs/releases/tag/1.12

**Comment by Caiao25** [comment]
Olá, desculpa mas não achei outro lugar pra postar amigos. :/ Você faz integração do PagHiper com o Shopify Henrique? To precisando muito :/.

**Comment by henriqueccruz** [comment]
@MarksEliel checa se os boletos pagos foram gerados antes da atualização que corrigiu esse problema.
Os boletos gerados após isso não devem apresentar essa dificuldade na baixa automática.

**Comment by MarksEliel** [comment]
Fiz uns testes, abri a fatura e gerei o boleto e não apareceu nada nos logs das transações...

**Comment by henriqueccruz** [comment]
Olá @MarksEliel, agradeço de antemão pela paciência. Estamos trabalhando pra tornar as integrações robustas e estáveis, sem abrir mão das funcionalidades planejadas para as próximas versões.
Vou investigar internamente e te peço mais informações conforme o resultado.

**Comment by lvdc** [comment]
Estou com o mesmo problema, utilizando a versão 1.12 o retorno automático não funciona.

**Comment by henriqueccruz** [comment]
A última versão do plugin ([1.121](https://github.com/paghiper/whmcs/archive/1.121.zip)) acaba de ser liberada para donwload e corrige um possível problema com o retorno automático.

O problema que abordamos é quando a URL definida na configuração do WHMCS não contém a barra no final. É recomendado adicionar a barra independente da atualização, para evitar um redirecionamento 301 ao acessar o site pois reflete no SEO.

**Comment by MarksEliel** [comment]
Aqui continua com o mesmo problema nenhum boleto está sendo confirmado automaticamente.
Veja se isso ajuda, quando vou em Transações > Logs dos Portais > as transações do paghiper tem isso: Não foi possível gravar os dados no banco.

**Comment by henriqueccruz** [comment]
@MarksEliel, pegue a versão 1.121 e emita um boleto com a versão nova.
Olhando nos nossos logs, vimos que a atualização lançada resolve seu problema.

A baixa automática começará a ocorrer quando os boletos gerados com a versão nova começarem a compensar.

**Comment by CezarLucena** [comment]
Ola boa noite acabei de integrar o whmcs no meu cpanel instalei o paghiper como esta no github mas não subiu a forma de pagamento 
A minha versão no whmcs é  7.4.2 e baixei a ultima atualização dopaghiper 1.121mesmo assim ela não Aparece no portais para pagamento. 
Espero que posam me ajudar e desde já muito obrigado.
