### ISSUE TITLE
Update para PHP 8.1

### ISSUE THREAD

**Issue by fernandogobah** [paghiper/whmcs#121]
Olá, quando saíra a versão compatível com o PHP 8.1?

**Comment by OneHitX** [comment]
No aguardo.

**Comment by maisondasilva** [comment]
A última versão é compatível se der um erro tem um Issue meu antes com o arquivo de correção.

**Comment by henriqueccruz** [comment]
Olá pessoal, boa tarde.
Versão v2.4.0 lançada. Essa versão remove alguns warnings, implementa suporte a PHP 8.1 e corrige alguns bugs.

Caso tenham mais questões que precisem de suporte, peço a gentileza de abrir no ticket.
Obrigado pela paciência.
