### ISSUE TITLE
Table exists / PIX não disponível para esta fatura

### ISSUE THREAD

**Issue by paulonichio** [paghiper/whmcs#123]
Fiz a atualização do módulo PagHiper da versão 2.2.1 para 2.4.
Troquei todos os arquivos no FTP e, ao testar o módulo, constatei dois erros:

**1.** Ao abrir qualquer boleto bancário ou PIX, no topo da página fica presente a informação "Table exists". Apenas isto... não faço ideia do que pode ser feito.
**2.** As faturas via boleto bancário estão abrindo... porém mesmo abrindo a fatura e trocando de Boleto Bancário para PIX, ao gerar o PIX é exibida a mensagem: **PIX não disponível para essa fatura! O método de pagamento escolhido para esta fatura não é PIX. Caso ache que isso é um erro, contate o suporte.**

Criei por exemplo uma adição de créditos e marque o PIX como forma de pagamento e o mesmo erro foi exibido.

**Comment by henriqueccruz** [comment]
Olá, boa tarde.Sobre a mensagem "Table exists", é um bugzinho.Um fix abordará essa questão em algumas horas, no máximo.Sobre a questão do PIX, pode me confirmar qual versão do WHMCS e PHP estão em uso?Em 9 de jan. de 2023 14:18, Paulo Nichio ***@***.***> escreveu:

Fiz a atualização do módulo PagHiper da versão 2.2.1 para 2.4.

Troquei todos os arquivos no FTP e, ao testar o módulo, constatei dois erros:

1. Ao abrir qualquer boleto bancário ou PIX, no topo da página fica presente a informação "Table exists". Apenas isto... não faço ideia do que pode ser feito.

2. As faturas via boleto bancário estão abrindo... porém mesmo abrindo a fatura e trocando de Boleto Bancário para PIX, ao gerar o PIX é exibida a mensagem: PIX não disponível para essa fatura! O método de pagamento escolhido para esta fatura não é PIX. Caso ache que isso é um erro, contate o suporte.

Criei por exemplo uma adição de créditos e marque o PIX como forma de pagamento e o mesmo erro foi exibido.

**Comment by henriqueccruz** [comment]
@paulonichio  - Confere por favor se sua configuração de usuário admin está diferente entre os dois gateways (PIX e boleto)?

**Comment by henriqueccruz** [comment]
Checa se a v2.4.1 resolve esses problemas listados.
Vamos manter o ticket aberto para receber seu feedback.

**Comment by paulonichio** [comment]
Oi Henrique, boa noite!

Fiz a atualização dos arquivos e, o erro de Table Exist... desapareceu.
Já com relação ao outro erro, resolveu em partes...

Agora o que está acontecendo é que: eu emito uma fatura em Boleto Bancário... Ao gerar o boleto é exibida a mensagem:

Ops! Não foi possível emitir o PIX.
Por favor entre em contato com o suporte. Erro 0x004681

(sim, a mensagem de erro está ao contrário... se eu tento emitir o PIX aparece que não foi possível emitir o boleto bancário e vice-versa).
Ao olhar o log do WHMCS, é exibida diversas mensagens de erro, como:

**Não foi possível associar o ID de requisição ao boleto.**
invoice_id => 
exception => Failed to write Paghiper
LockID

**Não foi possível inserir a transação no banco de dados. Por favor entre em contato com o suporte.**
json => 
    create_request => 
        result => success
        response_message => transacao criada
        transaction_id => 017ZWXLRC9T36O23
        created_date => 2023-01-09 23:22:33
        value_cents => 1500
        status => pending
        order_id => 111620
        due_date => 2023-01-09
        bank_slip => 
            digitable_line => XXXX
            url_slip => https://www.paghiper.com/checkout/boleto/XXXX
            url_slip_pdf => https://www.paghiper.com/checkout/boleto/XXXX/pdf
            bar_code_number_to_image => XXXX
        http_code => 201
        http_cod => 201
query => INSERT INTO mod_paghiper (transaction_type,transaction_id,order_id,due_date,status,url_slip,url_slip_pdf,digitable_line,bar_code_number_to_image,open_after_day_due,slip_value,qrcode_base64,qrcode_image_url,emv,bacen_url,pix_url) VALUES ('billet', 'XXXX','111620','2023-01-09','pending','https://www.paghiper.com/checkout/boleto/XXXX','https://www.paghiper.com/checkout/boleto/XXXX/pdf','XXXX', '1','15.00','','','','','');
query_result => {"queryString":"INSERT INTO mod_paghiper (transaction_type,transaction_id,order_id,due_date,status,url_slip,url_slip_pdf,digitable_line,bar_code_number_to_image,open_after_day_due,slip_value,qrcode_base64,qrcode_image_url,emv,bacen_url,pix_url) VALUES ('billet', 'XXXX','111620','2023-01-09','pending','https:\/\/www.paghiper.com\/checkout\/boleto\/XXXX','https:\/\/www.paghiper.com\/checkout\/boleto\/XXXX\/pdf','XXXX', '1','15.00','','','','','');"}
exception => 

>> Eu removi algumas informações com XXXX de propósito, para que não fique público tais informações.

**Comment by henriqueccruz** [comment]
Olá @paulonichio , obrigado pelas informações complementares.
Nos ajudou a entender melhor seu caso e, consequentemente, a melhorar nosso plug-in.

Acabamos de lançar uma update com bugfixes (v2.4.2) que aborda todas essas questões.
Vou manter o ticket aberto para confirmação de que suas questões foram sanadas.

**Comment by maisondasilva** [comment]
@henriqueccruz o paghiper_force_sync.php não está mais funcionando e depois que botei 2.4 varias fatura não deram baixa ao abrir o paghiper_force_sync.php aparece Oops!

Something went wrong and we couldn't process your request.

Please go back to the previous page and try again.

**Comment by henriqueccruz** [comment]
@maisondasilva - Não recomendamos uso desse script. A issue relacionada foi fechada em 2020
Fizemos ele para um caso bastante específico e o módulo evoluiu bastante desde então.

Caso você ainda tenha problemas com baixa, sugerimos que atualize para a v2.4.2 e aguarde.
Se o problema persistir (updates não ocorrerem em algumas horas), solicite reenvio das notificações de mudança de status ao nosso suporte.

Se tiver problemas com o módulo (esse script mencionado não faz parte do bundle), peço a gentileza de abrir outro ticket.

**Comment by henriqueccruz** [comment]
Obrigado por reportar! Essa integração foi refeita na v2.4.3
Caso tenha alguma outra questão, abra nova issue por favor
