### ISSUE TITLE
Erro novo Modulo V2.41

### ISSUE THREAD

**Issue by Jcobello** [paghiper/whmcs#128]
Henriques bom dia

Esse erro já se apresentou na versão anterior mais quando se gerava o boleto agora esta na situa''cão inversa.
Ele não aplica baixa a alguns boletos, principalmente os com cnpj. Mesmo estando configurada como tinha solicitado na versão anterior para colocar o campo nome da empresa preenchido quando fosse cnpj

Estamos tendo que ficar atentos e baixar os boletos na mão pois já tivemos casos de clientes bloqueados por esse motivo.
Fico no aguardo

Versão WHMCS foi atualizada pela WHMCS para versão mais nova e mesmo assim continuou.
Gera normal

**Comment by Jcobello** [comment]
Henrique

Verifiquei os logs no WHMCS mais o que percebi e que só aparece log na geração os logs que apareciam quando o paghiper fazia alterações simplesmente sumiram
Veja este log do cliente que por confidencia pagou em pix mais o erro da nas duas modalidades

https://prnt.sc/6osuGEuoILo9

mais veja no segundo print de um cliente que foi finalizado o pagamento com a versão anterior mostras no log o recebimento das informações do PagHiper com os procedimentos.

https://prnt.sc/wWvQgyjySK7C

**Comment by henriqueccruz** [comment]
Uma coisa importante a notar é que a 2.4 (major update) apresentou um bug relacionado a baixa.
Um simples update para a 2.4.2 deve resolver a questão.

Agora, se a questão for intermitente, precisamos analisar o caso mais a fundo realmente.
Esses logs enviados ajudam, mas os que preciso para avaliar melhor a questão são guardados no caminho abaixo:
Menu Superior > Transações > **Logs dos Portais**

Seria legal ver quais faturas estão dessincronizadas (foram pagas, estão pagas no painel Paghiper mas não no WHMCS) e usar esse ID de fatura nas buscas.

**Comment by Jcobello** [comment]
Isso que vi a ler um caso que esta em tratamento relacionado ao pix acabei de atualizar para a .42 vou aguardar a virada do dia quando gera os boleto e te repasso o que ocorreu 
Por ora gradecido pela atenção

**Comment by henriqueccruz** [comment]
@Jcobello , bom dia
Temos novidades quanto ao seu caso?

**Comment by Jcobello** [comment]
Bom dia  Henrique

Infelizmente não conseguimos testar hoje pois acabou que não tinha nenhum vencimento de cliente hoje esta previsto dia 14/01 a geração pelo que vimos de um lote. Mais esta na minha agenda testando já informo pode ficar tranquilo.
O que ocorreu uma vez só com esta sua última versão foi quando vai olhar uma boleta já gerada um sequencia de letras que faz a página descer para o meio da tela, mas como disse só ocorreu uma vez e parou.
Assim que tiver info informo. Obrigado pela atenção

**Comment by Jcobello** [comment]
Henrique boa tarde,

as baixas ocorreram perfeitamente hoje pelo que vimos.
Só temos um problema que vi que um dos itens do fórum foi questionado e tinha comentado que deu uma vez depois sumiu. E que quando acessa um boleto pago no painel do WHMCS aparece algumas vezes um texto sem sentido na vertical fazendo descer a tela até o meio parece algum Lixo que ficou de comentário na programação quando da ctrl+f5 e some e não aparece mais.
Com relação as baixas parece que a sua correção deu certo.

**Comment by souzadavi** [comment]
Devido a falta da correção e aplicação da funcionalidade, acabamos criando um repositório aonde o plugin possui alguns recursos extras, segue o link do novo repositorio para resolver esse problema: https://github.com/LinkNacional/whmcs-boleto-pix
