### ISSUE TITLE
Erro na versão 2.4.2 (Corigido)

### ISSUE THREAD

**Issue by seridohost** [paghiper/whmcs#129]
PagHiper para WHMCS
Erro ao enviar os e-mails de faturas para todos os clientes que utilizam o modulo quando usado o comando baixar PDF da fatura ou PDF por e-mail.
Arquivo com erro:
modules/gateways/paghiper/inc/helpers/attach_pdf_slip.php linha 19

Solução:
Adicionar  $sql = "SELECT paymentmethod, total FROM tblinvoices WHERE id = {$invoiceid};"; na linha 17

**Comment by souzadavi** [comment]
Devido a falta da correção e aplicação da funcionalidade, acabamos criando um repositório aonde o plugin possui alguns recursos extras, segue o link do novo repositorio para resolver esse problema: https://github.com/LinkNacional/whmcs-boleto-pix

**Comment by henriqueccruz** [comment]
Na v2.4.3 toda essa integração foi refatorada. Caso tenha alguma questão que precise de suporte na versão nova, favor abrir nova issue
Obrigado por reportar
