### ISSUE TITLE
Próxima Versão

### ISSUE THREAD

**Issue by jonatasaraujo** [paghiper/whmcs#13]
Boa noite, tem previsão para as próximas novidades??
Esperando pela versão de encaminhamento do boleto por e-mail ao gerar fatura e uma possível reimpressão do boleto ao invés de gerar um novo.

Att Jônatas Araújo
DesignWorld.com.br

**Comment by paulonichio** [comment]
Fala Jonatas.
Idem, estou querendo saber também... a próxima versão promete e será extremamente útil para mim e para todos.

Tomara que a PagHiper acelere o desenvolvimento.

**Comment by henriqueccruz** [comment]
Olá @jonatasaraujo e @paulonichio, a nova versão deve sair daqui a uma ou duas semanas, com alguns bugfixes e melhorias.
Dentre elas, o suporte a emissão de boletos junto com a fatura e reutilização de boletos ja emitidos, enquanto não vencidos.

Atualizo este ticket assim que tivermos disponível para download.

**Comment by TecSecret** [comment]
Bom dia, tem previsão desse lançamento.

**Comment by andrevilalta** [comment]
Oi Henrique, voce tem alguma noticia sobre essa nova versão, estou com clientes falando que ta entrando varios boletos no DDA deles por essa questão de cada vez o sistema gerar um novo.

Existe algo que podemos ajudar para agilizar o processo, até mesmo contribuindo com $? 

Aguardo amigo

**Comment by divulgaabc** [comment]
Tem alguma previsão, já se passarem quase 1 ano rsrs?

**Comment by henriqueccruz** [comment]
Versão liberada para download (v1.2).
