### ISSUE TITLE
Erro na versao 2.4.2

### ISSUE THREAD

**Issue by eseixas** [paghiper/whmcs#131]
Quando envio um email de Invoice Criado, eu recebo a mensagem abaixo:

TypeError: property_exists(): Argument #1 ($object_or_class) must be of type object|string, null given in /modules/gateways/paghiper/inc/helpers/attach_pdf_slip.php:46

Meu PHP é a versão 8.1.16 e meu WHMCS está na versão 8.6.1.

Eu não sei como resolver essa mensagem de erro.

**Comment by souzadavi** [comment]
Devido a falta da correção e aplicação da funcionalidade, acabamos criando um repositório aonde o plugin possui alguns recursos extras, segue o link do novo repositorio para resolver esse problema: https://github.com/LinkNacional/whmcs-boleto-pix

**Comment by henriqueccruz** [comment]
Checa se a última update resolve sua questão. Toda a integração para criação dos anexos dos e-mails foi refatorada.
Caso persista, abra novo ticket por gentileza
