### ISSUE TITLE
Desconto não aplica corretamente.

### ISSUE THREAD

**Issue by rafaelbok** [paghiper/whmcs#132]
Olá, estou tendo o seguinte problema. 
Marquei para aplicar desconto de 10% antes do vencimento, mas está aplicando apenas 1%, tentei botar 100% mas o resultado foi o mesmo.

Atualizei da 2.2.1 para a 2.4.2 mas o problema permanece.

Alguma idéia?

**Comment by souzadavi** [comment]
Tente usar esse outro módulo, é atualizado com mais frequência: https://github.com/LinkNacional/whmcs-boleto-pix

**Comment by henriqueccruz** [comment]
@rafaelbok , isso deve resolver.
Testa com a última versão por gentileza. Se voltar a enfrentar problemas, abra novo ticket por gentileza
