### ISSUE TITLE
Erro ao cancelar um pedido que não foi pago.

### ISSUE THREAD

**Issue by wheslleyandrade** [paghiper/whmcs#133]
Olá, esse erro me aparece desde outras versões, ao cancelar um pedido que não foi pago.

For additional assistance, please reference the [WHMCS TroubleShooting Guide »](https://docs.whmcs.com/Troubleshooting_Guide)

Error: Call to undefined function log_status_to_db() in /home2/sertanej/www.andradedeveloper.net/area-do-cliente/includes/hooks/cancel_paghiper_slip.php:67
Stack trace:
#0 /home2/sertanej/www.andradedeveloper.net/area-do-cliente/vendor/whmcs/whmcs-foundation/lib/Hook/Manager.php(0): cancel_paghiper_slips(Array)
#1 /home2/sertanej/www.andradedeveloper.net/area-do-cliente/vendor/illuminate/support/Facades/Facade.php(261): WHMCS\Hook\Manager->run('InvoiceCancelle...', Array, false)
#2 /home2/sertanej/www.andradedeveloper.net/area-do-cliente/includes/functions.php(0): Illuminate\Support\Facades\Facade::__callStatic('run', Array)
#3 /home2/sertanej/www.andradedeveloper.net/area-do-cliente/includes/orderfunctions.php(0): run_hook('InvoiceCancelle...', Array)
#4 /home2/sertanej/www.andradedeveloper.net/area-do-cliente/admin/orders.php(0): changeOrderStatus(229, 'Cancelled')
#5 {main}

**Comment by souzadavi** [comment]
Tente usar esse outro módulo, é atualizado com mais frequência: https://github.com/LinkNacional/whmcs-boleto-pix

**Comment by henriqueccruz** [comment]
Muito provavelmente esse erro foi causado por um hook desatualizado
Essas funções foram renomeadas em algum ponto nas últimas updates para evitar conflto com outros módulos
Caso precise de suporte com alguma quetão, abra novo ticket por favor
