### ISSUE TITLE
Este método de pagamento só pode ser utilizado para pagamentos em R$ (BRL)

### ISSUE THREAD

**Issue by imprezahost** [paghiper/whmcs#134]
Nosso WHMCS possui USD como moeda padrão (Currency ID 2 exemplo), mesmo configurando o módulo para converter para BRL, tendo o perfil do cliente configurado como BRL (Currency ID 1 exemplo) e também com CPF/CNPJ registrados, ao gerar um boleto/PIX, recebemos o erro: 

**Este método de pagamento só pode ser utilizado para pagamentos em R$ (BRL)**

Na versão 2.3 funciona corretamente, mas qualquer versão acima, ele apresenta esse erro.

Então ao ler um pouco o código da versão 2.4.2, alteramos na **linha 319** do arquivo: process_payment.php encontrado em: /modules/gateways/paghiper/inc/helpers

De:
`if($currency !== 'BRL' && $currency !== 'R$') {`

Para:
`if(array_key_exists('currency_code', $client_details['client']) && ($client_details['client']['currency_code'] !== 'BRL' && $client_details['client']['currency_code'] !== 'R$')) {`

Que era a mesma linha 306 da versão 2.3

Isso corrige o problema na versão 2.4.2 e agora conseguimos gerar boletos/PIX normalmente.

**Comment by henriqueccruz** [comment]
Abordamos essa questão na update que acabou de sair, obrigado por reportar

**Comment by imprezahost** [comment]
O mesmo erro retornou na versão 2.5.

Para resolver, eu comentei as linhas (// Get used currency) 317 até 331 e isso resolveu o problema.
