### ISSUE TITLE
Demora no retorno automático

### ISSUE THREAD

**Issue by rafaelbok** [paghiper/whmcs#135]
Olá, estou tendo problemas com o retorno automático nas transações, estão demorando muito, o sintoma começou após update do whmcs, chega a levar mais de 10 horas, para emitir e cancelar os boletos/pix vai no mesmo instante, as outras gateways também nào tiveram problemas, apenas com a paghiper, na hora de confirmar o pagamento esta levando muitas horas para confirmar! 
O que posso fazer?

**Comment by linkoficial** [comment]
Tenho o mesmo problema na demora de compensão, apenas no PIX. É de forma aleatória, mas poucas as vezes, quando ocorre isso leva de 30min a algumas horas para compensar.
Sempre tive esse problema, mesmo com versões anteriores do módule e do WHMCS.
Da mesma forma os IP's estão em whitelist, tanto no firewall quanto no webserver. Em todo esse período, inclusive o WHMCS já rodou em servidores diferentes e sempre apresentou o mesmo comportamento.

**Comment by linkoficial** [comment]
Nunca houve solução, mas não tenho problemas de nunca compensar, apenas a demora mesmo.
Eu vou experimentar em uma próxima atualização do meu WHMCS este projeto: https://github.com/LinkNacional/whmcs-boleto-pix
Eles deram uma melhor continuidade neste módulo, eu recomendaria testar e se tiver sucesso me avise.

**Comment by linkoficial** [comment]
Se puder questionar eles sobre a solução e postar aqui, acredito que seria de grande valia para a comunidade.

**Comment by brunoferreiralkn** [comment]
> > Nunca houve solução, mas não tenho problemas de nunca compensar, apenas a demora mesmo. Eu vou experimentar em uma próxima atualização do meu WHMCS este projeto: https://github.com/LinkNacional/whmcs-boleto-pix Eles deram uma melhor continuidade neste módulo, eu recomendaria testar e se tiver sucesso me avise.
> 
> O suporte acabou resolvendo o problema, não sei o que fizeram, mas agora funciona normalmente. Esse modulo da https://github.com/LinkNacional/whmcs-boleto-pix vi que vc tentou fazer o update mas houve um erro com o banco, eu não testei porque acabaria tendo o mesmo problema.

Boa tarde, @rafaelbok. Você encontrou um problema na nossa versão do módulo? Se sim, poderia compartilhar conosco [aqui](https://github.com/LinkNacional/whmcs-boleto-pix/issues/new?assignees=&labels=bug&projects=&template=reportar-bug.md&title=)?

**Comment by brunoferreiralkn** [comment]
> > > > Nunca houve solução, mas não tenho problemas de nunca compensar, apenas a demora mesmo. Eu vou experimentar em uma próxima atualização do meu WHMCS este projeto: https://github.com/LinkNacional/whmcs-boleto-pix Eles deram uma melhor continuidade neste módulo, eu recomendaria testar e se tiver sucesso me avise.
> > > 
> > > 
> > > O suporte acabou resolvendo o problema, não sei o que fizeram, mas agora funciona normalmente. Esse modulo da https://github.com/LinkNacional/whmcs-boleto-pix vi que vc tentou fazer o update mas houve um erro com o banco, eu não testei porque acabaria tendo o mesmo problema.
> > 
> > 
> > Boa tarde, @rafaelbok. Você encontrou um problema na nossa versão do módulo? Se sim, poderia compartilhar conosco [aqui](https://github.com/LinkNacional/whmcs-boleto-pix/issues/new?assignees=&labels=bug&projects=&template=reportar-bug.md&title=)?
> 
> eu não usei o modulo de vcs pq vi que nos issues havia um problema quando era feito o update do modulo original da paghiper, sendo necessário fazer uma ação manual no banco de dados, por este motivo não testei, mas caso seja seguro fazer o update da versão antiga do módulo, terei prazer em utilizar.

As issues atuais do módulo não apresentam nenhum problema em relação a banco de dados. Pode conferir ou nos apontar o problema exato?

**Comment by henriqueccruz** [comment]
Pessoal, vou fechar essa issue por não estar relacionada a integração do módulo em si
Mas caso o problema volte a acontecer, abram nova issue por favor pra eu acompanahar com o time de devs aqui.
Obrigado!
