### ISSUE TITLE
Ops! Não foi possível emitir o boleto bancário. Erro 0x004682. Campos com valores null.

### ISSUE THREAD

**Issue by paulonichio** [paghiper/whmcs#138]
Após atualizar o módulo para a versão 2.4.3 (disponibilizada dia 26/10), alguns clientes começaram a nos relatar a exibição da seguinte mensagem de erro na tela de PIX (inclusive para boletos também).

**Ops! Não foi possível emitir o boleto bancário** (já começa errado aqui onde o cliente marcou PIX e não boleto bancário).
**Por favor entre em contato com o suporte. Erro 0x004682**

Ao verificar o código fonte da página do WHMCS (viewinvoice.php), todos os campos do formulário estavam como "null", não capturando nenhuma informação na página.

< form name="paghiper" action="[https://MEUDOMINIO.com.br/modules/gateways/paghiper_pix.php?invoiceid=1455&uuid=XXXX&mail=XXXXXX&pix=true](view-source:https://MEUDOMINIO.com.br/modules/gateways/paghiper_pix.php?invoiceid=1455&uuid=XXXX&mail=XXXX&pix=true)" method="post">
<input type="hidden" name="client_data" value='{"firstname":":null","lastname":":null" --- e por aí vai.

Verificando os logs do WHMCS (gatewaylog.php) apenas constou o seguinte:

```
json => 
    pix_create_request => 
        result => reject
        response_message => payer_email invalido
        http_code => 200
post => 
    client_data => {"firstname":null,"lastname":null,"companyname":null,"email":null,"phonenumber":null,"address1":null,"address2":null,"city":null,"state":null,"postcode":null,"cpf_cnpj":"AQUI PEGOU CORRETAMENTE O CPF","razao_social":null}
request => {"apiKey":"XXXX","partners_id":"XXXX","order_id":1455,"notification_url":"https:\/\/MEUDOMINIO.com.br\/modules\/gateways\/paghiper_pix.php","days_due_date":0,"type_bank_slip":"boletoA4","items":[{"item_id":1455,"description":"Fatura #1455","price_cents":"5590","quantity":1}],"payer_email":null,"payer_name":" ","payer_phone":"","payer_street":null,"payer_complement":null,"payer_city":null,"payer_state":null,"payer_zip_code":null,"payer_cpf_cnpj":"AQUI PEGOU CORRETAMENTE O CPF","fixed_description":false,"per_day_interest":false}
```

Voltei a versão anterior que segue funcionando normalmente.
Obrigado.

**Comment by henriqueccruz** [comment]
Olá @paulonichio , boa tarde
Esse comportamento mencionado ocorre com clientes que compram via checkout WHMCS?
Clientes com faturas geradas via CRON?

Se são clientes com faturas geradas via CRON, sabe dizer se eles tem uma sub-conta responsável pelo financeiro?

**Comment by paulonichio** [comment]
Olá, boa tarde!

Segue respostas:

- Esse comportamento mencionado ocorre com clientes que compram via checkout WHMCS?
Trata-se de um cliente antigo nosso, no qual a fatura já estava disponível para pagamento (estava como MercadoPago), ele trocou para PIX e Boleto e ocorreram estes erros/problemas.

- Ocorre com clientes com faturas geradas via CRON?
Aparentemente as novas faturas emitidas hoje pelo cron saíram corretamente e não consta erros nos logs.

- Se são clientes com faturas geradas via CRON, sabe dizer se eles tem uma sub-conta responsável pelo financeiro?
O cliente que testei (da fatura que já estava emitida e ele só trocou o método de pagamento para PIX) não possui subcontas cadastradas.

- Qual versão do PHP está usando?
PHP 7.4.33

- Qual versão do WHMCS está usando?
WHMCS 8.8.0 

- Fez upgrade total do módulo? (Todos os arquivos, incluindo hooks)
Sim, todos os arquivos nos dois diretórios foram substituídos.

Obrigado!

**Comment by henriqueccruz** [comment]
Infelizmente estou com dificuldades para replicar o seu caso então vou te pedir uma gentileza.
Mesmo usando a mesma versão do PHP e mesma versão do WHMCS.

Entre em contato com nosso time de integração para investigarmos. 
É muito importante para nós entender exatamente o que causou esse problema no seu ambiente.

Pra isso, basta fazer contato através do e-mail integracao@paghiper.com
Vou manter esse ticket aberto para updates.

**Comment by paulonichio** [comment]
> @paulonichio , estamos tentando contato contigo para investigar a questão. Por favor cheque seu e-mail.

Opa, eu respondi ao e-mail alguns dias atrás e estou aguardando um retorno. 
Agradeço pela atenção!

**Comment by rgazetta** [comment]
Isso ocorre conosco também, o que descobri é que se no nome do cliente ou empresa tiver caracteres especiais o sistema da este erro, ao remover o boleto ou o pix funciona de boa.

Tive este problema com 4 clientes todos tinham ' no nome da empresa.

**Comment by henriqueccruz** [comment]
Obrigado por reportar, @rgazetta 
Vamos tentar replicar esse comportamento por aqui e atualizamos este ticket assim que tivermos novidades

**Comment by hostsr** [comment]
henrique

Cobello, boa noite pesquisando acabei achando este caso e estou com um caso com a ultima versão com o mesmo problema achei que poderia ser algum erro com a conta do cliente mais não é  a única coisa que estou a fazer logo mais e trocar a versão do php pois o cliente instalou o whmcs com a versão 8,3 sou descer para 7,4 para ver o erro que esta idêntico até na troca de info como nosso colega descreveu as respostas do erro vem trocadas onde e pix  vem boleto

**Comment by hostsr** [comment]
henrique 

Troquei da versão 8,2 para 7,4 continua  mais o erro mudou mais veja que a mensagem continua errada eu esteva gerando boleto e retornou pix

O estranho e que a mesma versão em outro servidor funciona perfeito só esta que esta dando erro.

Ops! Não foi possível emitir o PIX.
Por favor entre em contato com o suporte. Erro 0x004682
