### ISSUE TITLE
CPF/CNPJ Inválido

### ISSUE THREAD

**Issue by rgazetta** [paghiper/whmcs#139]
Quando o cliente cria contatos adicionais e seleciona 1 desses contatos para ser o responsável pela cobrança o módulo não abre o boleto apresentando erro de CPF/CNPJ Inválido, para corrigir temos que remover o contato de cobrança como responsável.

O correto seria o módulo pegar os dados do perfil e não do contato adicional.

**Comment by henriqueccruz** [comment]
Olá @rgazetta , boa tarde.
Esse comportamento se dá devido as mudanças implementadas na versão 8 do WHMCS e a última vesão do módulo ja leva isso em consideração.


Confirma pra mim por gentileza qual versão do módulo está utilizando e qual versão do WHMCS.

**Comment by rgazetta** [comment]
> Olá @rgazetta , boa tarde. Esse comportamento se dá devido as mudanças implementadas na versão 8 do WHMCS e a última vesão do módulo ja leva isso em consideração.
> 
> Confirma pra mim por gentileza qual versão do módulo está utilizando e qual versão do WHMCS.

Utilizamos o WHMCS 7.1 por questões de outros módulos não podemos atualizar ainda.
Utilizamos o 2.4.3 Paghiper.

**Comment by brinsleyparagao** [comment]
Aqui mesmo problema

WHMCS 8.8
Modulo 2.4.3

**Comment by brinsleyparagao** [comment]
> Fizemos uma pequena update (RC) que aborda essa questão. Conseguem atualizar para teste? Arquivos afetados são:
> 
> /modules/gateways/paghiper.php /modules/gateways/paghiper_pix.php /modules/gateways/paghiper/classes/PaghiperTransaction.php
> 
> Vou manter o ticket aberto para feedbacks de vocês.

Deu certo !

Quando peguei o RAW dos arquivos alterados e coloquei lá, simplesmente tudo voltou a funcionar.

Muito obrigado amigo,,, 100% OK 😊

**Comment by rgazetta** [comment]
> @rgazetta : No caso desse cliente usado como demonstração de caso, ainda estamos falando de um cliente que tem um contato responsável pelo financeiro? Adicionalmente: Seu cliente tem algum caractére especial no nome da empresa? Um apóstrofo, talvez...

No caso é um cliente que tem contato especifico para o financeiro.
Não o cliente não tem nenhum caractere especial, tanto que basta alterar o contrato financeiro para padrão que o boleto é gerado de boa.

**Comment by henriqueccruz** [comment]
Chequem a última update por favor, deve resolver a questão definitivamente.
Caso tenham outras questões, abram novo ticket por gentileza
