### ISSUE TITLE
Não reconhece créditos na fatura

### ISSUE THREAD

**Issue by divulgaabc** [paghiper/whmcs#14]
Atualizei recentemente para esta nova versão, e à princípio tudo ok e esta muito melhor que a anterior. Contudo uma coisa não havia testado, quando o cliente tem um crédito em conta e debita de uma fatura, ao gerar o boleto não reconhece o crédito, ou seja, o boleto é emitido com o valor total, não com o 'desconto' do crédito aplicado (Forma de Pagamento: Boleto + Partial Credit ), o que poderia fazer para resolver este problema? Na versão o crédito era considerado como desconto no valor total do boleto... Como podemos solucionar este problema?

**Comment by henriqueccruz** [comment]
Olá @divulgaabc, realmente, o módulo não suporta a aplicação de créditos.
Teremos suporte a créditos na próxima versão, que sairá entre uma e duas semanas.

**Comment by divulgaabc** [comment]
Olá, Henrique! Vocês tem a previsão para nova versão?

**Comment by agenciah1code** [comment]
@henriqueccruz e @divulgaabc Acabei abrindo a Issue #34 sem antes ter visto essa anterior já aberta. Acabei fazendo alguns testes aqui no módulo que uso na empresa, e funcionou corretamente, sendo assim, enviei um pull request #35 com esta correção, espero ter ajudado!

**Comment by henriqueccruz** [comment]
A versão liberada para download (v1.2) hoje resolve o problema citado.
