### ISSUE TITLE
Verificar paymentmethod na inclusão do hook

### ISSUE THREAD

**Issue by mazzei-adam** [paghiper/whmcs#145]
Tente criar uma fatura com forma de pagamento diferente de PagHiper e terá um erro, pois o hook é executado no 'EmailPreSend' e não há uma verificação se a fatura tem o método de pagamento do PagHiper, ou seja o 'PaghiperTransaction' será executado para todas as faturas, mesmo que tenham outras forma de pagamento.

E tbm é incluído no template invoicepdf.tpl, ao incluir attach_pdf_slip.php, deve haver uma verificação se a fatura tem o paymentmethod = 'paghiper'

**Comment by YanBerardinelli** [comment]
Aqui também temos o mesmo problema, tivemos que desabilitar o envio via PDF pois estava apresentando problemas no Cron.

**Comment by tarcisiocosta96** [comment]
Conseguiu resolver? Estou com o mesmo problema

**Comment by henriqueccruz** [comment]
Olá prezados, boa noite.
Lançamos uma update a alguns minutos abordando várias dessas questões relacionadas a estabilidade e fluidez da operação.
Peço que atualizem o módulo (incluindo os hooks e integração no invoicepdf.tpl) e abram novo ticket caso tenham novas questões que precisem de suporte
