### ISSUE TITLE
Erros após atualização.

### ISSUE THREAD

**Issue by rgazetta** [paghiper/whmcs#146]
1 – Esta gerando problemas com outros módulos de pagamento, quando a fatura está vencida e usa outro meio de pagamento o sistema não permite reenviar nenhum aviso manual, (Ops! Não foi possível emitir o boleto bancário.
Número de CPF/CNPJ inválido! Por favor atualize seus dados ou entre em contato com o suporte)

2 – Continua sem gerar o qrcode ou link do boleto quando a fatura é criada pelo sistema (cron), se a fatura for criada manualmente este funciona, ou se o cliente já tiver visualizado e gerado o qr ou o boleto também funciona.

3 – Quando a fatura está vencida o sistema esta gerando erro ao reenviar avisos manualmente.

4 – Anexar (<?php include dirname(__FILE__).'/../../modules/gateways/paghiper/inc/helpers/attach_pdf_slip.php'; ?>) 
o boleto ou o qrcode na fatura em pdf funciona apenas para o pix, para o boleto da erro.

**Comment by tarcisiocosta96** [comment]
Conseguiu resolver? Estou com o mesmo problema.
