### ISSUE TITLE
Envio de PDF na fatura 

### ISSUE THREAD

**Issue by eniofreitasjr** [paghiper/whmcs#147]
Olá pessoal, tudo bem?

Fiz a instalação do módulo paghiper no meu whmcs e tenho duas dúvidas:

1 - Como faço para habilitar o envio do boleto em pdf em anexo as faturas?

2 - Na parte do tutorial que cita o seguinte:

> Adicione o texto abaixo no arquivo invoicepdf.tpl do seu tema, para anexar boletos e códigos PIX ao PDF das faturas (opcional)
> 
> <?php include dirname(__FILE__).'/../../modules/gateways/paghiper/inc/helpers/attach_pdf_slip.php'; ?>

Eu utilizo o template **twenty-x** e até onde vi não possui o arquivo invoicepdf.tpl mas possui o download do pdf ativo na fatura

**Comment by rgazetta** [comment]
Este você edita no template SIX mesmo e deixa ele la.

**Comment by henriqueccruz** [comment]
A informação do @rgazetta procede.
Caso tenha problemas, peço a gentileza de abrir novo ticket
