### ISSUE TITLE
WHMCS não envia e-mail de confirmação de pagamento

### ISSUE THREAD

**Issue by lucklikeee** [paghiper/whmcs#149]
Olá,

Depois de atualizar para a versão 2.5 do módulo, meu whmcs parou de enviar mensagens de confirmação de pagamento e não consigo encontrar a razão.

Jean

**Comment by henriqueccruz** [comment]
Olá @lucklikeee , boa noite.
Lançamos uma update a alguns minutos abordando várias questões relacionadas a estabilidade e fluidez da operação.
Peço que atualize o módulo (incluindo os hooks e integração no invoicepdf.tpl) e abram novo ticket caso tenham novas questões que precisem de suporte
