### ISSUE TITLE
Não está obtendo o CPF/CNPJ

### ISSUE THREAD

**Issue by leonardoasb** [paghiper/whmcs#15]
Olá,

Mesmo com o cnpj ou cpf informado o meu cliente esta sendo sendo enviado para a página do paghiper para informar o CPF. Com módulos de terceiro não tenho este problema. Poderia me ajudar, por favor.

**Comment by henriqueccruz** [comment]
Olá @leonardoasb,
Você preencheu o ID do seu campo de CPF na página de configuração?

**Comment by leonardoasb** [comment]
@henriqueccruz sim, informei o id do campo. Em módulos não oficiais funciona normalmente. Somente no módulo ofical é que enfrento esta dificuldade.

**Comment by henriqueccruz** [comment]
Tem usado a versão mais recente do plug-in?
Preencheu o campo de usuário admin corretamente?

**Comment by leonardoasb** [comment]
Sim, versão mais recente do módulo e do whmcs. Estou utilizando a versão 7 do PHP.

**Comment by henriqueccruz** [comment]
O plug-in é compatível com a versão 7 do PHP, não temos nenhum caso de incompatibilidade até então.
O ID do campo CPF/CNPJ está correto no painel de configuração? Ou há divergência entre os IDs usados no plug-in oficial e o desenvolvido por terceiros?

**Comment by leonardoasb** [comment]
Obrigado, encontrei o problema. Por algum motivo o admin que atribui estava sem permissões. Tudo funcionando agora. Vi que é possivel colocar o código de barras do boleto no corpo do e-mail, como fazer isso?

**Comment by henriqueccruz** [comment]
Ah sim. O plug-in sempre utiliza o padrão "admin", caso o campo de usuário admin esteja vazio. Talvez por isso os plug-ins de terceiros não te causaram problemas nesse sentido.
Sobre o código de barras no corpo do boleto, será possível na próxima versão, que deve ser lançada daqui a duas semanas, com uma série de outras melhorias.

Vou aproveitar e implementar a checagem de permissões para o admin atribuido.
