### ISSUE TITLE
boleto direto no email

### ISSUE THREAD

**Issue by carlosdfoz** [paghiper/whmcs#17]
olá já esta disponível a opção do boleto direto no email?

Quais melhorias foram feitas na versão 1.12?

Testei o boleto direto no email usei como referencia o hotmail o botão link não funciona no hotmail, fiz o teste com gmail funciona bem: print do hotmail: https://drive.google.com/file/d/0ByFX2XqmOA44ZnRUU3JacEZTRzA/view

**Comment by aespa** [comment]
Olá Carlos, como fazer a integração desse botão no email?!

**Comment by carlosdfoz** [comment]
usei esse código {$invoice_payment_link} porem não funciona corretamente.

**Comment by aespa** [comment]
hum.. entendi.. qual o problema encontrado?!

**Comment by carlosdfoz** [comment]
alguns clientes de email por exemplo hotmail não fica como link o botão e não captura o cpf ou cnpj do cliente

**Comment by aespa** [comment]
entendi..

**Comment by carlosdfoz** [comment]
vou bancar um desenvolvedor, por que aqui acho  que não resolvem isso

**Comment by henriqueccruz** [comment]
Por "opção de boleto direto no e-mail" vocês querem dizer um link para o boleto bancário direto no corpo do e-mail?

**Comment by aespa** [comment]
Por mim, poderia ser... Ao clicar no link abriria o boleto..

**Comment by henriqueccruz** [comment]
Caso você tenha checkout transparente ativado, não é necessário esperar a próxima versão.

O bloco abaixo inclui um link direto para o boleto, caso o método de pagamento seja o boleto Bancário PagHiper. Lembre-se de que, caso você configure o plug-in com outro nome (como "Boleto Bancário" por exemplo, troque o nome na condicional abaixo.


```
{if $invoice_payment_method eq "PagHiper Boleto"}

<p style="width: 100%; text-align: center; ">
<a href="{$whmcs_url}modules/gateways/paghiper.php?invoiceid={$invoice_id}&uuid={$client_id}&mail={$client_email}"> Gerar boleto bancário </a>
</p>

{/if} 
``` 


Caso queira incluir somente o link em algum lugar no e-mail, aqui vai somente a fórmula do link:

```
{$whmcs_url}modules/gateways/paghiper.php?invoiceid={$invoice_id}&uuid={$client_id}&mail={$client_email}
```

**Comment by henriqueccruz** [comment]
@carlosdfoz, checa se o CPF no cadastro do cliente é válido. Caso o CPF/CNPJ seja inválido, a PagHiper rejeitará os dados e solicitará novamente ao cliente.

**Comment by carlosdfoz** [comment]
@henriqueccruz 

deu certo essa opção aqui:

{$whmcs_url}modules/gateways/paghiper.php?invoiceid={$invoice_id}&uuid={$client_id}&mail={$client_email}

**Comment by henriqueccruz** [comment]
Ótimo. Só lembrando que, o bloco condicional acima precisa ser atualizado caso você mude o nome do Gateway. Por ex.:

Se você definiu o nome do modo de pagamento como simplesmente "Boleto Bancário", O bloco ficaria como abaixo:

´´´
{if $invoice_payment_method eq "Boleto Bancário"}

<p style="width: 100%; text-align: center; ">
<a href="{$whmcs_url}modules/gateways/paghiper.php?invoiceid={$invoice_id}&uuid={$client_id}&mail={$client_email}"> Gerar boleto bancário </a>
</p>

{/if} 
´´´

Vou disponibilizar essas informações em um guia para facilitar.

**Comment by carlosdfoz** [comment]
@henriqueccruz   prezado calculo de juros e multa seria muito bom

**Comment by henriqueccruz** [comment]
@carlosdfoz, ja está em desenvolvimento.
Atualizo este ticket quando estiver pronto para uso.

**Comment by Caiao25** [comment]
Olá, desculpa mas não achei outro lugar pra postar amigos. :/ Você faz integração do PagHiper com o Shopify Henrique? To precisando muito :/.

**Comment by henriqueccruz** [comment]
@Caiao25, obrigado por entrar em contato!
Estava considerando integrar em um futuro próximo mas preciso estudar como poderia funcionar.

Sua loja Shopify ja está em produção?

**Comment by Caiao25** [comment]
@henriqueccruz, entao cara ja esta pronta rs. Gostaria de migrar pro paghiper pois muita gente utiliza boleto

**Comment by carlosdfoz** [comment]
@henriqueccruz ao utilizar o link direto no corpo do email, habilitando a opção  checkout transparente o modulo não envia ao whmcs o arquivo de retorno do pagamento "não baixa a fatura automático"

**Comment by Jcobello** [comment]
Colegas prazer em fazer parte deste grupo primeiramente.
Testando o script do colega henriqueccruz verifiquei que o segundo funciona perfeitamente no e-mail abrindo uma lacuna que já vinha a algum Tempo pesquisando porem verifiquei um ponto grave ao meu ver, que quando se envia o cliente ao paghiper na geração d boleta ele acaba quitando a boleta
Não sei se seria um erro nosso aqui no sistema mais já verificamos várias vezes que se executando o processo pela plataforma isso não ocorre agora pelo e-mail ocorre.

**Comment by Jcobello** [comment]
Continuando a verificação acima, detectamos que no primeiro instante de se clicar na geração da boleta ocorre perfeitamente o que acontece e que se deixar o browser aberto com a fatura na mesma tela que se encontra o painel aberto ocorre o erro ( ironia de lógica) e manda-se salvar o pdf da boleta ocorre o pagamento.
Agora se faz via painel isso não ocorre no mesmo procedimento e se repetido por várias vezes.
Informações técnicas:
Navegador Firefox Versão 57.0 (64 Bits)
Sistema Operacional Windows Prof (64 Bits)
WHCMS 7.21 Atualizado todos os patches 
Pagamento só por deposito e PagHiper não existe mais nenhuma aplicação

**Comment by Jcobello** [comment]
Após postar achei este adendo do henrique cruz  lie ele por várias vezes pois ia contra o que estava acontecendo onde ele informa "SE ESTIVER ATIVADO" 

@henriqueccruz ao utilizar o link direto no corpo do email, habilitando a opção checkout transparente o modulo não envia ao whmcs o arquivo de retorno do pagamento "não baixa a fatura automático"

Só que no meu esta ativado e esta fazendo justamente ao contrário que ele disse ele gera o pagamento na impressão da boleta. O que de forma alguma deve-se ocorrer pois descontrola toda a plataforma.

**Comment by loganfonseca** [comment]
Olá a todos.
Gostaria de integrar o PAGHIPER com o shopify, porém não faço a menor ideia de como começar.
Alguém já conseguiu realizar esta integração? Não consegui nenhum freelancer para fazer isto para mim, se alguém estiver afim...

**Comment by ddrhost** [comment]
Implementado. Verifique na nova atualização disponibilizada.

**Comment by Jcobello** [comment]
Henrique boa noite

Desculpe a indiscrição mais não entendi a sua uma resposta agora a pouco.
Inclusive estou com a nova instalação em produção e funcionando e realmente ficou perfeita.
A minha questão não sei se vem ao caso pois como sou seu cliente recebi ao mesmo tempo um e-mail seu onde informa que conseguiu anexar a boleta ao e-mail de aviso ou mais precisamente o fechamento do whmcs isso é correto?
Então conseguiu que fosse gerada a fatura e ela enviada por e-mail seria isso.
Fico no aguardo

Cobello
