### ISSUE TITLE
Checkout não funcionando

### ISSUE THREAD

**Issue by rvfaelo** [paghiper/whmcs#18]
Acontece dois erros, na verdade.
O primeiro é que quando o cliente faz um pedido, não está aparecendo no site do PagHiper, nem o cliente consegue ver o boleto.

O segundo é que sempre que tento instalar a última versão do plugin, acontece isso http://prntscr.com/gjek4s

Aguardo resposta!

**Comment by henriqueccruz** [comment]
Olá @rvfaelo, pelo printscreen, da pra ver que o sistema é Woocommerce/Wordpress.
De qualquer forma, ja respondemos seu ticket e lançamos uma atualização que aborda seu problema.

Caso tenha outras questões, basta abrir outro ticket.
