### ISSUE TITLE
Boleto Direto

### ISSUE THREAD

**Issue by tsabaia** [paghiper/whmcs#2]
Olá,
Vocês poderiam adicionar a opção de ao cliente clicar em gerar boleto no WHMCS, ser redirecionado diretamente para o boleto, sem passar pela página de vocês, onde mostra a logo de vocês, dados do cliente e do pedido.

**Comment by rickhessmann** [comment]
O logo e dados da PagHiper eu vejo como segurança. Assim o cliente pode confimar na hora de pagar, uma vez que o boleto é registrado.
Porém, a opção de ter o link direto do boleto, dentro do WHMCS é uma coisa que também preciso.

**Comment by tsabaia** [comment]
Eu não utilizo a função de redirecionar a fatura do WHMCS para o boleto, logo o cliente pode conferir os dados ao abrir a fatura.

Quanto menos telas, mais pratico para o cliente. Nessa parte de pagamento é essencial, para o cliente não ficar usando como desculpa ao atrasar um pagamento. 

Aqui tivemos que mudar o modulo por conta própria para ignorar essa tela e levar diretamente ao boleto.

**Comment by rickhessmann** [comment]
Eu modifiquei o plug-in para funcionar com checkout transparente.
Modifiquei também para funcionar com campo personalizado de CPF/CNPJ, assim o cliente não precisa digitar essas informações sempre que emitir um boleto. Não publiquei aqui ainda.

**Comment by jonatasaraujo** [comment]
Para quem ainda não conseguiu o módulo atualizado da PagHiper já atualizado para checkout transparente só avisar que envio por e-mail. 👍

**Comment by henriqueccruz** [comment]
Temos uma versão nova saindo do forno amanhã.
A versão nova possui suporte tanto a checkout transparente quanto boleto direto.

**Comment by henriqueccruz** [comment]
A versão 1.1 que acaba de ser publicada implementa isso.
Basta ativar checkout transparente e acessar os boletos via link:
https://site/modules/gateways/paghiper.php?invoiceid=[iddafatura]&uuid=[iddocliente]&mail=[maildocliente]

Farei um manual de como reescrever esse link usando mod_rewrite em alguns dias.
