### ISSUE TITLE
Descrição do produto nos e-mails de notificação

### ISSUE THREAD

**Issue by senhoritos** [paghiper/whmcs#21]
Prezados, gostaria de saber se é possível alterar as informações do pedido, no e-mail de notificação do PagHiper.

Vendo matrículas online no WooCommerce, onde "Produto = Curso" e "Variação do produto = Cidade do curso". Facilitaria muito se nas informações do pedido aparecesse o **nome do produto/variação**, ao invés de aparecer a mensagem genérica **"Fatura #1234 emitida pelo site XXXXXX"**

Poderiam me informar se isto é possível? Agradeço desde já!

**Comment by TecSecret** [comment]
Este módulo é para WHMCS, o para Woocommerce deve ter outro git, mas se o cliente já recebe notificação pelo seu Woocommerce, não há nescessidade de ele receber do paghiper. Eu particularmente não gosto de usar as notificações do paghiper.

**Comment by henriqueccruz** [comment]
Por favor abra um ticket no repositório do plugin para Woocommerce, terei o maior prazer em abordar seu problema.
