### ISSUE TITLE
Ao clicar em gerar fatura a tela fica toda branca

### ISSUE THREAD

**Issue by rodrigoadamacena** [paghiper/whmcs#22]
Acontecendo agora dos últimos dias pra cá, ao clicar em gerar a tela fica branca. 

(https://user-images.githubusercontent.com/82585/33776361-435d8bae-dc28-11e7-9a2c-78761a243fbb.png)

Pode me ajudar?

**Comment by danimarw** [comment]
Está acontecendo com o meu também, conseguiu uma solução?

**Comment by danimarw** [comment]
Rodrigo, aparentemente descobri o que está acontecendo, na página do módulo, nas configurações, existe um campo, Administrador atribuído (Insira o nome de usuário ou ID do administrador do WHMCS que será atribuído as transações. Necessário para usar a API interna do WHMCS.)

No meu caso estava admin, porém meu nome de usuário era outro, alterei e começou a gerar o boleto, faça o teste.

**Comment by rodrigoadamacena** [comment]
Blz valeu!

**Comment by henriqueccruz** [comment]
Perfeito, obrigado por responder @danimarw
