### ISSUE TITLE
Transações por boleto

### ISSUE THREAD

**Issue by sidneydevelop** [paghiper/whmcs#23]
É normal no mesmo boleto haver mais de uma transação, no caso do cliente ver o mesmo boleto mais de uma vez acaba gerando uma nova transação.

**Comment by sidneydevelop** [comment]
Ex: gerei um boleto com valor x e o cliente visualizou agora mas não pagou, quando ele for pagar gera uma nova transação na fatura, isso é normal acontecer? Acaba ficando vários registros no PagHiper do mesmo boleto..

**Comment by webcomunica** [comment]
O meu tbm faz isso, pessoal ta comunidade ta devagar nos feedback

**Comment by henriqueccruz** [comment]
@sidneydevelop e @webcomunica, estão se referindo ao plug-in para WHMCS? Ou do plug-in para Woocommerce?

**Comment by sidneydevelop** [comment]
@henriqueccruz WHMCS

**Comment by webcomunica** [comment]
@henriqueccruz tbm WHMCS

**Comment by agenciah1code** [comment]
@sidneydevelop @webcomunica @henriqueccruz @linkoficial Sim, isso e fato ocorre porque toda vez que o cliente clica em "Gerar boleto", de fato ocorre a criação de um novo boleto e não o reaproveitamento do boleto anterior, isso é ruim até porque o próprio PagHiper envia e-mails de lembrança e cobrança de pagamento dos boletos gerados, ou seja, se o cliente gerar 5x o boleto, ele vai pagar 1 e vai ficar recebendo ainda por um tempo notificações de 4 boletos, não pelo WHMCS, mas sim pela própria @paghiper, já tivemos sérios problemas com clientes por este motivo, pois vieram questionando fortemente o motivo de estar sendo cobrados sendo que o boleto e fatura já estavam quitadas.

Acredito que seja o mesmo problema reportado nas issues #20 e #13

**Comment by henriqueccruz** [comment]
A versão liberada para download (v1.2) hoje resolve o problema citado.

**Comment by sidneydevelop** [comment]
testei na última release lançada hoje e continua gerando novas transações cada vez que acessa o boleto, verifiquei direto no painel da PagHiper as transações geradas apenas para uma cobrança, sendo que abri algumas vezes o mesmo boleto no WHMCS.

**Comment by henriqueccruz** [comment]
Checa se o usuário MySQL tem permissões para criar tabelas.
Se não tiver, você vai precisar rodar a query de criação do banco de dados manualmente.

`CREATE TABLE IF NOT EXISTS `mod_paghiper` (
          `id` int(11) NOT NULL AUTO_INCREMENT,
          `transaction_id` varchar(16) NOT NULL,
          `order_id` int(11) NOT NULL,
          `due_date` date,
          `status` varchar(45) NOT NULL,
          `url_slip` varchar(255) DEFAULT NULL,
          `url_slip_pdf` varchar(255) DEFAULT NULL,
          `digitable_line` varchar(54) DEFAULT NULL,
          `open_after_day_due` int(2) DEFAULT NULL,
          `slip_value` float(11) DEFAULT NULL,
          PRIMARY KEY (`id`),
          KEY `transaction_id` (`transaction_id`)
        ) ENGINE=InnoDB DEFAULT CHARSET=latin1;`
