### ISSUE TITLE
Carnê

### ISSUE THREAD

**Issue by Lder** [paghiper/whmcs#24]
Gostaria de saber se é possivel criar carnês por exemplo 5  numa compra de 500 saia cada boleto por R$100

**Comment by webcomunica** [comment]
Também gostaria disso

**Comment by henriqueccruz** [comment]
@Lder e @webcomunica, Estão falando do plug-in para WHMCS mesmo? Ou do plug-in para Woocommerce?

**Comment by webcomunica** [comment]
@henriqueccruz me refiro para WHMCS.

**Comment by Lder** [comment]
Oi boa noite já não estou usando
Obrigado

Em qui, 5 de abr de 2018 às 01:30, webcomunica <notifications@github.com>
escreveu:

**Comment by henriqueccruz** [comment]
Foge muito do escopo do plug-in e da plataforma WHMCS.
Recomendo uma plataforma de e-commerce como o Woocomerce para tal.
