### ISSUE TITLE
Cancelando pedidos indevidos

### ISSUE THREAD

**Issue by rdg2001** [paghiper/whmcs#25]
Olá, estou na versão atual Versão 1.2.4.2

Cliente gerou 2 Boletos mas só pagou 1.

Pedido foi APROVADO e depois mudei para PRODUÇÃO ( status personalizado nosso ) 
Dias depois o pedido voltou para CANCELADO pelo plugin paghiper. 

COMO TRAVAR ISSO?

**Comment by henriqueccruz** [comment]
@rdg2001, creio que esteja se referindo ao plugin pra Woocommerce, correto?
Abra um ticket no repositório do Woocommerce e abordaremos esse problema.
