### ISSUE TITLE
Compatibilidade com o WHMCS 7.5

### ISSUE THREAD

**Issue by webcomunica** [paghiper/whmcs#27]
Alguém esta conseguindo usar o modulo no whmcs 7.5 com php 7?

**Comment by fgsants** [comment]
Aqui também não visse @webcomunica, apresenta erro ao acessar a página de configuração dos gateways de pagamento.

**Comment by TecSecret** [comment]
@webcomunica e @fgsants na linha 23 você altera para isso: function paghiper_config() { seu problema vai estar resolvido.

**Comment by agenciah1code** [comment]
> @webcomunica e @fgsants na linha 23 você altera para isso: function paghiper_config() { seu problema vai estar resolvido.

Se alterar isso, ele continuará funcionando nas versões anteriores à 7.5 ou somente da 7.5 superior?

Se existir uma maneira da função funcionar nas duas versões, já pensou em enviar um pull request?

**Comment by agenciah1code** [comment]
> @agenciah1code eu estou usando sem problemas na versão 7.6.1. Mas ele tem umas outras modificações também, como por exemplo pegar o valor real da fatura, após aplicar desconto, etc.

Perfeito, obrigado!

**Comment by henriqueccruz** [comment]
A versão liberada para download (v1.2) hoje resolve o problema citado.
