### ISSUE TITLE
Módulo não aplica desconto

### ISSUE THREAD

**Issue by linkoficial** [paghiper/whmcs#28]
Como todos sabem, no WHMCS tem a opção de crédito, que o cliente pode pagar um valor adicionar e o próximo WHMCS aplica desconto deste valor na próxima fatura.
Pois bem, o fato é que o módulo paghiper do whmcs não gera o boleto com este desconto, mesmo já estando aplicado na fatura.

Exemplo, um cliente gerou uma fatura de R$ 59,90 e tinha R$ 49,90 de crédito.
Então a fatura ficou de R$ 59,90 - R$ 49,90, valor total final de R$ 10,00
O cliente vai lá e gera o boleto e ele sai com o valor original de R$ 59,90

A fatura está correta:
**Subtotal: R$ 59,90
Crédito: R$ 49,90
Total: R$ 10,00**

E o boleto gera com o valor do campo **Subtotal**.
Estou utilizando a última versão do módulo e WHMCS 7.4.2

**Comment by TecSecret** [comment]
Altera a linha  $subtotal    = $data["subtotal"]; para  $subtotal    = $data["total"];

**Comment by linkoficial** [comment]
Obrigado TecSecret.
Vou testar essa solução.

**Comment by fgsants** [comment]
Testei aqui e funciona perfeitamente, valeu.

**Comment by henriqueccruz** [comment]
A versão liberada para download (v1.2) hoje resolve o problema citado.
