### ISSUE TITLE
Erro módulo whmcs 7.5

### ISSUE THREAD

**Issue by TecSecret** [paghiper/whmcs#29]
Erro no módulo paghiper no whmcs.

ArgumentCountError: Too few arguments to function paghiper_config(), 0 passed and exactly 1 expected in whmcsroot/modules/gateways/paghiper.php:23
Stack trace:
#0 whmcsroot/admin/configgateways.php(0): paghiper_config()
#1 {main}

**Comment by deguirbr** [comment]
Estou com esse erro agora, o que foi feito para corrigir?

**Comment by henriqueccruz** [comment]
A ultima atualização lançada corrige este erro.
