### ISSUE TITLE
Feedback: Nova Atualização 1.1

### ISSUE THREAD

**Issue by jonatasaraujo** [paghiper/whmcs#3]
Bom dia Henrique, fiz o teste do novo plugin e ainda não está funcionando perfeitamente.
As alterações que você fez quanto aos novos campos ficou legal;
1 - O local onde você deixou disponível a consulta do ID para o formulário CPF_CNPJ, bacana, mas não consegui colocar para funcionar.
2 - O checkout transparente é outro item que não funcionou o link,

Eu fiz o teste implementando uma linha informando o código do customfield referente ao CPF_CNPJ mas ainda sim o link para o checkout transparente não funcionou, deixei de fazer algo?

Obrigado pelo plugin.

**Comment by henriqueccruz** [comment]
Olá Jonatas,
Explique o que acontece, assim posso ajudar melhor.

O checkout comum (não-transparente) pede quais dados na emissão do boleto?

**Comment by jonatasaraujo** [comment]
Bom dia Henrique,

Sim ele não reconhece o campo CPF/CNPJ criado, quando clica na área do cliente para gerar o boleto ele vai direto para página do PagHiper solicitando o CPF/CNPJ do cliente. As demais informações ele puxou certinho.

Já o checkout transparente ele não gera nenhuma informação, apenas direciona para uma página em branco.

**Comment by henriqueccruz** [comment]
Qual versão do WHMCS está usando?

**Comment by jonatasaraujo** [comment]
7.1.1

**Comment by henriqueccruz** [comment]
Olá Jonatas,

Estou curioso para testar. Não consegui reproduzir seu problema, mas posso pensar em algumas alternativas.
Me mande um e-mail em [comercial@intelihost.com.br](mailto:comercial@intelihost.com.br) por favor? Conforme conseguirmos progresso com o seu problema, sigo atualizando este ticket.

**Comment by henriqueccruz** [comment]
Jonatas, consegui replicar o problema. Estamos testando uma atualização que resolve isso. Te manteremos informado.

**Comment by henriqueccruz** [comment]
Prontinho, @jonatasaraujo.
Teste a nova versão, por favor!

**Comment by jonatasaraujo** [comment]
Beleza, vou testar hoje a noite e te retorno feedback @henriqueccruz

**Comment by jonatasaraujo** [comment]
Henrique, fiz o teste, mas ainda continua com o problema no campo CPF/CNPJ, ele aparece o campo para escolher mas quando gera o boleto ele não está buscando o campo selecionado. 

Segue print http://i68.tinypic.com/2gx41p4.jpg 

O checkout transparente já está em funcionamento.

**Comment by henriqueccruz** [comment]
Ótimo.
Sobre o CPF/CNPJ, só acontece no checkout comum, certo?
Ja que o checkout transparente funciona sem problemas, significa que o CPF/CNPJ está sendo informado corretamente.

Vou checar se existe algo que possa estar causando isso.
Se você puder, preencha um cadastro idêntico ao de um cliente que apresenta esse problema do CNPJ?

Nosso ambiente de testes fica em: http://cloud.paghiper.com/
Obrigado.

**Comment by jonatasaraujo** [comment]
Henrique para ambas as finalizações está apresentando o erro porque ele não encontra o CPF/CNPJ do cliente e direciona para página do PagHiper onde é necessário informar o documento antes de gerar o boleto.

Engraçado que em seu exemplo do link acima está funcionando perfeitamente!

Vou criar um novo campo e tentar utilizar, o campo existente ele não está filtrando a informação.

**Comment by weslleypg** [comment]
Jonatas, envie um e-mail para webmaster@paghiper.com com seu contato de skype.

Nossa equipe ira lhe ajudar a resolver seu problema mais de perto.
