### ISSUE TITLE
Enviar Boleto por E-mail

### ISSUE THREAD

**Issue by henriquelucas** [paghiper/whmcs#30]
Henrique, a API  do Paghiper permite que seja gerado o boleto e enviado para o cliente por E-mail? sem a necessidade dele clicar em um link para gerar? Digo isso porque o sistema em si do WHMCS envia um arquivo quando gerado uma nova fatura, minha dúvida: É possível  fazer com que esse modulo envie o boleto para cliente por E-mail assim que for gerado a fatura? 

Caso seja possível quanto custaria para desenvolver uma solução assim?

**Comment by agenciah1code** [comment]
@paghiper @henriqueccruz Essa ideia é realmente excelente, a PagHiper permite esse tipo de emissão sem que o cliente mesmo precise clicar no botão para gerar?

Aguardo retorno.

**Comment by ddrhost** [comment]
Implementado. Verifique na nova atualização disponibilizada.
