### ISSUE TITLE
Campo de telefone não ir com o 55 do código do Brasil

### ISSUE THREAD

**Issue by deguirbr** [paghiper/whmcs#33]
Prezados, 

Visualizei que o PagHiper avisa via SMS para os clientes no dia do vencimento, que o boleto vence naquele dia, mas nos testes que fiz não estava funcionando. Ao entrar em contato com o suporte me disseram que o número tem que ir sem o 55 do código do Brasil, que precisa ir somente assim:

6499021010

Ao invés de:

5564999021010

É possível alterar?

Obrigado desde já.

**Comment by TecSecret** [comment]
Bom dia, @deguirbr quando o módulo pega o campo phonenumber do whmcs ele pega como está salvo no banco de dados, no WHMCS tem uma opção aonde vc desativa que ele use o DDI (código do pais) no campo telefone. 

Vai no admin do whmcs, configurações gerais/localização  e desmarca a opção Phone Numbers.

Acredito que isso deva resolver.
