### ISSUE TITLE
Não reconhecimento de crédito aplicado no WHMCS

### ISSUE THREAD

**Issue by agenciah1code** [paghiper/whmcs#34]
Caros,

Quando o cliente tem um crédito no WHMCS e aplica o mesmo dentro da fatura, ao gerar o boleto, ele gera com o valor total da fatura e não com o valor final com o crédito aplicado, existiria alguma solução para estes casos?

**Comment by henriqueccruz** [comment]
A versão liberada para download (v1.2) hoje resolve o problema citado.
