### ISSUE TITLE
Data de vencimento se a fatura estiver vencida

### ISSUE THREAD

**Issue by divulgaabc** [paghiper/whmcs#37]
Recentemente atualizei para nova versão do módulo, com isso vi que alguns pontos foi corrigido, porém notei que quando o cliente gera um boleto de uma fatura vencida, o mesmo acrescenta 1 dia no prazo, ou seja, vamos supor que o vencimento do boleto era da 05/12, o cliente entra na plataforma dia 10/12, o boleto é gerado para o dia 11/12.

Contudo isso muitas das vezes é arriscado e ruim para nós que dependemos destes pagamentos, o cliente vai 'atrasar' ainda mais 1 dia para efetuar o pagamento, pois muitos clientes 'simples' só fazem no dia do vencimento. 

Entrei nos códigos do módulo e vi que tem a opção de dias após, e esta como +1, fiz um teste colocando +0, e funcionou! Com isso minha ideia seria disponibilizar diretamente nas configurações do módulo no painel a opção do vendedor em mudar esta data, o que acham, seria possível?

Uma outra coisa que seria interessante para complementar seria a opção de nós termos a possibilidade de incluir juros e multa! O próprio módulo faria os cálculos e geraria o boleto atualizado seguindo as funções acima (data atualizada), ai na aba de configurações nós incluiríamos as porcentagens de juros e multa.

**Comment by henriqueccruz** [comment]
@divulgaabc, ja temos uma implementação diferente na lógica diferente.
Está disponível na update lançada ontem.
Caso tenha problemas, por favor abra outro ticket.

**Comment by divulgaabc** [comment]
Olá Henrique, vi que atualizou o módulo, instalei e ficou bem bacana, estamos quase chegando no ideal rsrsrs.

Para funcionar a multa, acho que tem que ser criado uma forma de após gerar uma vez o boleto, ao tentar abrir novamente pelo link, seja aberto o mesmo boleto! Pois se não o cliente vai acessar o link sempre e o boleto estará com a data nova atualizada sem a multa! Digo isso para boletos já vencidos, pois notei que boleto ainda não vencidos ele acessa o mesmo boleto.

Também acho que faltou poder colocar um juros mora diário, só a multa não seria suficiente uma vez que infelizmente temos clientes que acaba atrasando por dias e mais dias! (Hoje fazemos isso manualmente, se pudesse ser direto no boleto seria show de bola!)

O boleto quando vencido, ainda esta gerando 1 dias à frente a data atual. Acho que seria legal nas configurações nós colocarmos a quantidade de dias que desejamos, podendo ser 0 (mesmo dia), ou, +1, +2, etc... Pois como disse na postagem anterior, temos clientes simples, que mesmo sabendo que estão atrasado, se colocarmos o vencimento acima da data atual. ele acabam pagando somente no dia que esta marcando no vencimento!

Acho que uma situação que seria ideal, seria o boleto ser emitido assim que o WHMCS emitir a fatura, pois já será uma fatura com a informação do desconto, se houver, com a multa e juros, e o mesmo boleto deveria ser acessado, até o limite de dias que inserirmos para que o mesmo possa ser pago após o vencimento. Após este prazo poderia aparecer uma tela solicitando entrar em contato com a empresa para solicitação de um novo boleto, pois a faríamos os cálculos manualmente... 

Uma coisa que notei, é que antes, se o cliente não tivesse o CPF ou CNPJ no WHMCS, o módulo levava para uma página no PagHiper para o mesmo preencher os dados que faltam. Já na versão atual ele vai para uma página de Erro do WHMCS! Falando que o CNPJ ou CPF são inválidos! Assim clientes que acessarem fora do horário comercial não vão conseguir emitir o boleto!

Gostei da parte de Desconto pagando antecipado, ficou show!!!
