### ISSUE TITLE
Seria bacana um tutorial das novas funções

### ISSUE THREAD

**Issue by carlosdfoz** [paghiper/whmcs#39]
Prezados como integrar?

linha digitável no corpo do e-mail ?

link direto do boleto no corpo do email ?

**Comment by leonardoasb** [comment]
Também não encontrei como inserir a linha digital no email .... faltam muitos detalhes das novas funções

**Comment by carlosdfoz** [comment]
> Também não encontrei como inserir a linha digital no email .... faltam muitos detalhes das novas funções

tudo desorganizado

**Comment by henriqueccruz** [comment]
Olá pessoal, boa tarde.
Falha minha, acabei não documentando as funcionalidades corretamente.

O link direto para o boleto pode ser usado assim:
 
`{$whmcs_url}/modules/gateways/paghiper.php?invoiceid={$invoice_num}&uuid={$client_id}&mail={$client_email}`

A emissão automática foi feita via hook, amanhã disponibilizo isso no Github.
Ja a inclusão do boleto no PDF anexo, temos um bloco que deverá ser inserido no invoicepdf.tpl do seu tema, a ser disponibilizado amanhã também.

Atualizo vocês aqui logo que disponibilizar.

**Comment by leonardoasb** [comment]
Muito obrigado @henriqueccruz 

Vamos ficar no aguardo.

**Comment by agenciah1code** [comment]
Acompanhando aqui para saber como integrar a linha digitável diretamente no e-mail.

**Comment by paulonichio** [comment]
E ficamos no aguardo...

**Comment by tgssb** [comment]
Libera as novas funcionalidades por favor 😄

**Comment by carlosdfoz** [comment]
vamos rezar pra que seja revelado as funções

**Comment by agenciah1code** [comment]
> E ficamos no aguardo...



> Libera as novas funcionalidades por favor 😄



> vamos rezar pra que seja revelado as funções

Engraçado que nós conversamos diretamente com um dos responsáveis da PagHiper em relação à este módulo, nos disponibilizamos para ajudar no desenvolvimento de forma voluntária, justamente porque o módulo estava parado, tendo em vista que faziam anos que não havia atualização. Simplesmente falaram "até dia X nós lhe fornecemos uma resposta", isso já tem mais de 1 ano e nada. Uma pena, tínhamos as melhores das intenções, justamente para desafogar um pouco a responsabilidade do @henriqueccruz, tendo em vista que ele é o único que desenvolve este módulo. Simplesmente uma pena!

**Comment by henriqueccruz** [comment]
Prezados, a v2.0.1 acaba de ser liberada para download, implementando várias melhorias.
A linha digitável no corpo do e-mail pode ser implementada através da tag {$linha_digitavel}

O boleto anexo pode ser implementado de maneira simples também, pegando o bloco contido no arquivo invoicepdf.tpl e adicionando ao início do arquivo invoicepdf.tpl do seu tema.

A URL para acesso direto ao boleto, como dito acima, é:
`{$whmcs_url}/modules/gateways/paghiper.php?invoiceid={$invoice_num}&uuid={$client_id}&mail={$client_email}`

**Comment by agenciah1code** [comment]
> Prezados, a v2.0.1 acaba de ser liberada para download, implementando várias melhorias.
> A linha digitável no corpo do e-mail pode ser implementada através da tag {$linha_digitavel}
> 
> O boleto anexo pode ser implementado de maneira simples também, pegando o bloco contido no arquivo invoicepdf.tpl e adicionando ao início do arquivo invoicepdf.tpl do seu tema.
> 
> A URL para acesso direto ao boleto, como dito acima, é:
> `{$whmcs_url}/modules/gateways/paghiper.php?invoiceid={$invoice_num}&uuid={$client_id}&mail={$client_email}`

Maravilha, funcionando perfeitamente! Como faço para alterar o nome do PDF gerado no e-mail? Gostaria de colocar algo como "Boleto-FaturaXXX.pdf)

**Comment by henriqueccruz** [comment]
> Maravilha, funcionando perfeitamente! Como faço para alterar o nome do PDF gerado no e-mail? Gostaria de colocar algo como "Boleto-FaturaXXX.pdf"

No seu arquivo de tradução (/lang/portuguese-br.php), você pode traduzir a variável $_LANG['invoicefilename'].

Para conseguir a personalização que indicou, a variável deve ficar algo como
`$_LANG['invoicefilename'] = "Boleto-Fatura-"`

**Comment by leonardoasb** [comment]
Instalei a atualização ... Habilitei a geração de boletos junto com a fatura ... Entretanto o sistema gera os boletos na paghiper, mas não insere o código de barras, o espaço da linha digitável fica em branco. Alguma ideia de como corrigir isso ?

**Comment by henriqueccruz** [comment]
Olá @leonardoasb ,
Qual versão do plugin está usando? A geração agora é funcionalidade padrão (a partir da versão 2.0.1). Checa se o hook necessário foi carregado corretamente, na pasta includes/hooks

**Comment by leonardoasb** [comment]
Aparentemente tudo ok, a versão a mesma disponível no Github. Ele gera o boleto, só não inseri a linha digital no e-mail ...
Aguardo por mais alguma orientação

**Comment by henriqueccruz** [comment]
Está inserindo a TAG em algum template não-padrão? Por padrão ela só funciona em e-mails de Nova fatura gerada, Avisos de fatura vencida e lembrete de pagamento.Por outro lado, já vi alguns casos em que o template de email fica duplicado para linguagens diferentes, checa se não é esse o caso também.Caso nenhum dos passos mencionados acima resolva, ideal seria ativar o log do WHMCS e procurarmos pela causa lá.

**Comment by agenciah1code** [comment]
> Aparentemente tudo ok, a versão a mesma disponível no Github. Ele gera o boleto, só não inseri a linha digital no e-mail ...
> Aguardo por mais alguma orientação

Se for o caso, retira todos os arquivos do módulo, baixa a nova versão 2.0.1.1 e instala novamente, testamos aqui desde o lançamento da 2.0.1 e está funcionando normalmente, tanto a geração de boletos, PDF por e-mail e também linha digitável. A versão 2.0.0.1 veio para corrigir alguns bugs, mas desde a antiga já funciona normalmente essa função da linha digitável no e-mail.

**Comment by leonardoasb** [comment]
> > Aparentemente tudo ok, a versão a mesma disponível no Github. Ele gera o boleto, só não inseri a linha digital no e-mail ...
> > Aguardo por mais alguma orientação
> 
> Se for o caso, retira todos os arquivos do módulo, baixa a nova versão 2.0.1.1 e instala novamente, testamos aqui desde o lançamento da 2.0.1 e está funcionando normalmente, tanto a geração de boletos, PDF por e-mail e também linha digitável. A versão 2.0.0.1 veio para corrigir alguns bugs, mas desde a antiga já funciona normalmente essa função da linha digitável no e-mail.

Baixei o módulo novamente e reinstalei ... Mesma coisa ... Gera o boleto mas anexa o boleto e nem insere a linha digitavel.

Alguns dos erros no log:

Data | Descrição | Nome de Usuário | Endereço IP
-- | -- | -- | --
12/02/2019 00:02 | Hooks Debug: Hook Defined for Point: AfterRegistrarRenewalFailed - Priority: 1 - Function Name: (anonymous function) | System | 216.244.66.228
12/02/2019 00:02 | Hooks Debug: Hook Defined for Point: AfterRegistrarRenewal - Priority: 1 - Function Name: (anonymous function) | System | 216.244.66.228
12/02/2019 00:02 | Hooks Debug: Hook Defined for Point: DomainTransferFailed - Priority: 1 - Function Name: (anonymous function) | System | 216.244.66.228
12/02/2019 00:02 | Hooks Debug: Hook Defined for Point: DomainTransferCompleted - Priority: 1 - Function Name: (anonymous function) | System | 216.244.66.228
12/02/2019 00:02 | Hooks Debug: Hook Defined for Point: AfterRegistrarTransferFailed - Priority: 1 - Function Name: (anonymous function) | System | 216.244.66.228
12/02/2019 00:02 | Hooks Debug: Hook Defined for Point: AfterRegistrarTransfer - Priority: 1 - Function Name: (anonymous function) | System | 216.244.66.228
12/02/2019 00:02 | Hooks Debug: Hook Defined for Point: AfterRegistrarRegistrationFailed - Priority: 1 - Function Name: (anonymous function) | System | 216.244.66.228
12/02/2019 00:02 | Hooks Debug: Hook Defined for Point: AfterRegistrarRegistration - Priority: 1 - Function Name: (anonymous function) | System | 216.244.66.228
12/02/2019 00:02 | Hooks Debug: Hook Defined for Point: CancellationRequest - Priority: 1 - Function Name: (anonymous function) | System | 216.244.66.228
12/02/2019 00:02 | Hooks Debug: Hook Defined for Point: AfterModuleTerminateFailed - Priority: 1 - Function Name: (anonymous function) | System | 216.244.66.228
12/02/2019 00:02 | Hooks Debug: Hook Defined for Point: AfterModuleTerminate - Priority: 1 - Function Name: (anonymous function) | System | 216.244.66.228
12/02/2019 00:02 | Hooks Debug: Hook Defined for Point: AfterModuleUnsuspendFailed - Priority: 1 - Function Name: (anonymous function) | System | 216.244.66.228
12/02/2019 00:02 | Hooks Debug: Hook Defined for Point: AfterModuleUnsuspend - Priority: 1 - Function Name: (anonymous function) | System | 216.244.66.228
12/02/2019 00:02 | Hooks Debug: Hook Defined for Point: AfterModuleSuspendFailed - Priority: 1 - Function Name: (anonymous function) | System | 216.244.66.228
12/02/2019 00:02 | Hooks Debug: Hook Defined for Point: AfterModuleSuspend - Priority: 1 - Function Name: (anonymous function) | System | 216.244.66.228
12/02/2019 00:02 | Hooks Debug: Hook Defined for Point: AfterModuleCreateFailed - Priority: 1 - Function Name: (anonymous function) | System | 216.244.66.228
12/02/2019 00:02 | Hooks Debug: Hook Defined for Point: AfterModuleCreate - Priority: 1 - Function Name: (anonymous function) | System | 216.244.66.228
12/02/2019 00:02 | Hooks Debug: Hook Defined for Point: FraudCheckFailed - Priority: 1 - Function Name: (anonymous function) | System | 216.244.66.228
12/02/2019 00:02 | Hooks Debug: Hook Defined for Point: CancelAndRefundOrder - Priority: 1 - Function Name: (anonymous function) | System | 216.244.66.228
12/02/2019 00:02 | Hooks Debug: Hook Defined for Point: CancelOrder - Priority: 1 - Function Name: (anonymous function) | System | 216.244.66.228
12/02/2019 00:02 | Hooks Debug: Hook Defined for Point: AcceptOrder - Priority: 1 - Function Name: (anonymous function) | System | 216.244.66.228

**Comment by agenciah1code** [comment]
> > > Aparentemente tudo ok, a versão a mesma disponível no Github. Ele gera o boleto, só não inseri a linha digital no e-mail ...
> > > Aguardo por mais alguma orientação
> > 
> > 
> > Se for o caso, retira todos os arquivos do módulo, baixa a nova versão 2.0.1.1 e instala novamente, testamos aqui desde o lançamento da 2.0.1 e está funcionando normalmente, tanto a geração de boletos, PDF por e-mail e também linha digitável. A versão 2.0.0.1 veio para corrigir alguns bugs, mas desde a antiga já funciona normalmente essa função da linha digitável no e-mail.
> 
> Baixei o módulo novamente e reinstalei ... Mesma coisa ... Gera o boleto mas anexa o boleto e nem insere a linha digitavel.
> 
> Alguns dos erros no log:
> 
> Data	Descrição	Nome de Usuário	Endereço IP
> 12/02/2019 00:02	Hooks Debug: Hook Defined for Point: AfterRegistrarRenewalFailed - Priority: 1 - Function Name: (anonymous function)	System	216.244.66.228
> 12/02/2019 00:02	Hooks Debug: Hook Defined for Point: AfterRegistrarRenewal - Priority: 1 - Function Name: (anonymous function)	System	216.244.66.228
> 12/02/2019 00:02	Hooks Debug: Hook Defined for Point: DomainTransferFailed - Priority: 1 - Function Name: (anonymous function)	System	216.244.66.228
> 12/02/2019 00:02	Hooks Debug: Hook Defined for Point: DomainTransferCompleted - Priority: 1 - Function Name: (anonymous function)	System	216.244.66.228
> 12/02/2019 00:02	Hooks Debug: Hook Defined for Point: AfterRegistrarTransferFailed - Priority: 1 - Function Name: (anonymous function)	System	216.244.66.228
> 12/02/2019 00:02	Hooks Debug: Hook Defined for Point: AfterRegistrarTransfer - Priority: 1 - Function Name: (anonymous function)	System	216.244.66.228
> 12/02/2019 00:02	Hooks Debug: Hook Defined for Point: AfterRegistrarRegistrationFailed - Priority: 1 - Function Name: (anonymous function)	System	216.244.66.228
> 12/02/2019 00:02	Hooks Debug: Hook Defined for Point: AfterRegistrarRegistration - Priority: 1 - Function Name: (anonymous function)	System	216.244.66.228
> 12/02/2019 00:02	Hooks Debug: Hook Defined for Point: CancellationRequest - Priority: 1 - Function Name: (anonymous function)	System	216.244.66.228
> 12/02/2019 00:02	Hooks Debug: Hook Defined for Point: AfterModuleTerminateFailed - Priority: 1 - Function Name: (anonymous function)	System	216.244.66.228
> 12/02/2019 00:02	Hooks Debug: Hook Defined for Point: AfterModuleTerminate - Priority: 1 - Function Name: (anonymous function)	System	216.244.66.228
> 12/02/2019 00:02	Hooks Debug: Hook Defined for Point: AfterModuleUnsuspendFailed - Priority: 1 - Function Name: (anonymous function)	System	216.244.66.228
> 12/02/2019 00:02	Hooks Debug: Hook Defined for Point: AfterModuleUnsuspend - Priority: 1 - Function Name: (anonymous function)	System	216.244.66.228
> 12/02/2019 00:02	Hooks Debug: Hook Defined for Point: AfterModuleSuspendFailed - Priority: 1 - Function Name: (anonymous function)	System	216.244.66.228
> 12/02/2019 00:02	Hooks Debug: Hook Defined for Point: AfterModuleSuspend - Priority: 1 - Function Name: (anonymous function)	System	216.244.66.228
> 12/02/2019 00:02	Hooks Debug: Hook Defined for Point: AfterModuleCreateFailed - Priority: 1 - Function Name: (anonymous function)	System	216.244.66.228
> 12/02/2019 00:02	Hooks Debug: Hook Defined for Point: AfterModuleCreate - Priority: 1 - Function Name: (anonymous function)	System	216.244.66.228
> 12/02/2019 00:02	Hooks Debug: Hook Defined for Point: FraudCheckFailed - Priority: 1 - Function Name: (anonymous function)	System	216.244.66.228
> 12/02/2019 00:02	Hooks Debug: Hook Defined for Point: CancelAndRefundOrder - Priority: 1 - Function Name: (anonymous function)	System	216.244.66.228
> 12/02/2019 00:02	Hooks Debug: Hook Defined for Point: CancelOrder - Priority: 1 - Function Name: (anonymous function)	System	216.244.66.228
> 12/02/2019 00:02	Hooks Debug: Hook Defined for Point: AcceptOrder - Priority: 1 - Function Name: (anonymous function)	System	216.244.66.228

Qual versão do PHP você está usando em sua hospedagem? Está utilizando todos os requisitos mínimos para funcionamento do módulo? Outra dúvida, qual a versão do seu WHMCS?

**Comment by henriqueccruz** [comment]
> Baixei o módulo novamente e reinstalei ... Mesma coisa ... Gera o boleto mas anexa o boleto e nem insere a linha digitavel.

Só por curiosidade, você compartilharia seu template de e-mail?
Pode ser um printscreen, pra ajudar a entender melhor o que está acontecendo.

**Comment by leonardoasb** [comment]
Tenho todos os requsitos para rodar o módulo, ... Não insere a linha digitavel e nem anexa o boleto.

![image](https://user-images.githubusercontent.com/10524219/52636916-9a549d80-2eac-11e9-8183-33873d39ee04.png)

**Comment by DerexScript** [comment]
Estou com o mesmo problema, e não faço ideia de como resolver! [Ver Print](https://i.ibb.co/P4k5DW3/Capturar.png)
Instalação totalmente limpa!
WHMCS_v783
php 7.3.12 com todas dependências que o WHMCS requer!
