### ISSUE TITLE
Integração com e-mail whmcs

### ISSUE THREAD

**Issue by tgssb** [paghiper/whmcs#4]
Olá amigos!

Como faço para colocar o código de barras junto ao e-mail que vai para o cliente ? 
É possível encaminhar o boleto em anexo ?

**Comment by henriqueccruz** [comment]
No momento, ainda não é possível colocar o boleto ou código de barras diretamente no e-mail.
Tenho essa facilidade em mente, devo atualizar o módulo para suportar isso em breve.

**Comment by ddrhost** [comment]
Implementada a função de enviar o boleto em anexo no e-mail. Verifique na nova atualização disponibilizada.
