### ISSUE TITLE
PDF sendo enviado em todas as formas de pagamento

### ISSUE THREAD

**Issue by agenciah1code** [paghiper/whmcs#40]
Caros,

Após esta última atualização, percebi que o boleto bancário é enviado via PDF para todos os métodos de pagamento selecionados.

Muitas empresas assim como nós, fornecemos descontos e preços diferenciados para cada forma de pagamento, ou seja, no cartão de crédito, caso seja selecionado, será enviado um boleto com valor X, caso ele mude para depósito em conta, é gerado outro boleto com valor Y e no caso de pagamento por boleto bancário, um terceiro com valor Z.

Digo isso para os e-mails que são enviados tanto de criação de fatura como de lembrete de pagamento. O correto seria o envio do boleto em PDF apenas para a forma de pagamento "Boleto Bancário"

**Comment by agenciah1code** [comment]
Consegui arrumar, vou enviar um pull request, vocês dão uma olhada!

**Comment by henriqueccruz** [comment]
Entendo.
Manda seu pull request sim, quero dar uma olhada na sua implementação e comparar com a que fizemos. Não consegui replicar aqui. Qual versão do WHMCS está usando?

**Comment by agenciah1code** [comment]
> Entendo.
> Manda seu pull request sim, quero dar uma olhada na sua implementação e comparar com a que fizemos. Não consegui replicar aqui. Qual versão do WHMCS está usando?

Versão mais recente, 7.7.0.

Enviei o Pull #41

**Comment by henriqueccruz** [comment]
Eu fiz um comentário no pull request mas vou replicar parcialmente aqui, caso outros usuários tenham o mesmo problema.

Nas configurações, checa se o item "Gerar boletos para todos os pedidos?" está setado como "Não". Essa configuração deve impedir a criação de linhas digitáveis e inserção de boletos bancários nos PDFs de faturas. Assim que puder, testa uma alteração nesse item da configuração e veja se resolve o seu caso.

**Comment by henriqueccruz** [comment]
Um operador ternário estava funcionando incorretamente, por inconsistência do PHP.
Reformulamos e o problema não deve ocorrer novamente.

Ainda não fechei o pull #41 para analisarmos as outras modificações propostas mas, como o problema mencionado no ticket foi resolvido, vou fechar por enquanto e pedir a gentileza de reabrir caso tenha problemas com a v2.0.1.1
