### ISSUE TITLE
linha digitável não funciona

### ISSUE THREAD

**Issue by carlosdfoz** [paghiper/whmcs#42]
Ola

implementei a tag 

{$linha_digitavel}

e não mostra no template email a  linha digitavel 

alguma dica?

**Comment by henriqueccruz** [comment]
Boa noite @carlosdfoz ,
Checa se seu plugin está atualizado (última versão é a v2.0.1). 
Ela contém o hook necessário (e várias outras melhorias) para que a tag funcione e emita os boletos de maneira automática, conforme anunciado. Vou deixar esse chamado aberto, pra você checar e confirmar. Caso funcione corretamente, vou pedir a gentileza de atualizar esse chamado quando finalizar.

**Comment by carlosdfoz** [comment]
Olá

obrigado o hook nao tinha subido corretamente para pasta
