### ISSUE TITLE
retorno automático 

### ISSUE THREAD

**Issue by carlosdfoz** [paghiper/whmcs#43]
retorno do novo modulo não funciona
whmcs 7.5.2

**Comment by henriqueccruz** [comment]
Provavelmente a notificação está sendo bloqueada.
Está usando mod_security e/ou cpGuard?

**Comment by Crea7e** [comment]
> mod_security

Precisa ser desabilitado ? eu instalei ontem esse seu módulo e ainda não testei o retorno, outra coisa é possível que ele não envie o email de boleto para o cliente ? pois já que o whmcs faz a notificação é meio inútil o paghiper enviar também  mensagem quando o boleto é gerado

**Comment by henriqueccruz** [comment]
Não, o bloqueio ocorre em alguns casos apenas.
Nesse cenário, é necessário somente que uma exceção seja configurada via htaccess.

Basta adicionar no início do arquivo .htaccess do seu WHMCS a seguinte linha:
`SetEnvIfNoCase REMOTE_ADDR ^107.23.219.74$ MODSEC_ENABLE=Off`

Os e-mails de notificação e lembrete da PagHiper podem ser desabilitados pelo painel (Ferramentas > Notificações).

**Comment by henriqueccruz** [comment]
Prezados,
Ainda estão com problemas relacionados a notificação/retorno automático?
