### ISSUE TITLE
Problemas ao emitir boleto automaticamente

### ISSUE THREAD

**Issue by henriqueccruz** [paghiper/whmcs#44]
Aparentemente tudo ok, a versão a mesma disponível no Github. Ele gera o boleto, só não inseri a linha digital no e-mail ...
Aguardo por mais alguma orientação

_Originally posted by @leonardoasb in https://github.com/paghiper/whmcs/issues/39#issuecomment-462203659_

**Comment by henriqueccruz** [comment]
@leonardoasb, checa se o hook do gateway subiu corretamente para a pasta /includes/hooks na sua instalação do WHMCS. A versão atual do módulo tem mais arquivos e pastas do que as anteriores, sem o hook, a tag {$linha_digitavel} não vai funcionar.
Sobre o boleto anexo, você chegou a modificar o invoicepdf.tpl do seu tema?

**Comment by leonardoasb** [comment]
@henriqueccruz reinstalei o plugin. O hook está no diretório correto, mas mesmo assim não pega a linha digital.

Como deve ser feita a implantação do arquivo invoicepdf.tpl?

**Comment by henriqueccruz** [comment]
Sobre o hook, checa se a função file_get_contents está desativada na sua configuração do PHP.
Não é comum mas pode ser a causa. Como você ja relatou conseguir emitir boletos sem problema, não creio ser um problema relacionado a biblioteca JSON.

Sobre a fatura anexa, basta pegar o conteudo do invoicepdf.tpl disponibilizado junto com o gateway e colar imediatamente no inicio do invoicepdf.tpl do seu tema.

**Comment by leonardoasb** [comment]
A fatura no email está ok!

Mas ainda sem o linha digitavel no email .... file_get_contents está habilitado

**Comment by leonardoasb** [comment]
Data | Descrição | Nome de Usuário | Endereço IP
-- | -- | -- | --
12/02/2019 16:08 | Hooks Debug: No Hook Functions Defined | System | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: Called Hook Point LogTransaction | System | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: No Hook Functions Defined | leonardoasb | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: Called Hook Point AddTransaction | leonardoasb | 107.23.219.74
12/02/2019 16:08 | Added Transaction - Transaction ID: 1386 | leonardoasb | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: No Hook Functions Defined | System | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: Called Hook Point LogTransaction | System | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: No Hook Functions Defined | leonardoasb | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: Called Hook Point AddTransaction | leonardoasb | 107.23.219.74
12/02/2019 16:08 | Added Transaction - Transaction ID: 1385 | leonardoasb | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: Hook Defined for Point: AfterRegistrarRenewalFailed - Priority: 1 - Function Name: (anonymous function) | System | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: Hook Defined for Point: AfterRegistrarRenewal - Priority: 1 - Function Name: (anonymous function) | System | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: Hook Defined for Point: DomainTransferFailed - Priority: 1 - Function Name: (anonymous function) | System | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: Hook Defined for Point: DomainTransferCompleted - Priority: 1 - Function Name: (anonymous function) | System | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: Hook Defined for Point: AfterRegistrarTransferFailed - Priority: 1 - Function Name: (anonymous function) | System | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: Hook Defined for Point: AfterRegistrarTransfer - Priority: 1 - Function Name: (anonymous function) | System | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: Hook Defined for Point: AfterRegistrarRegistrationFailed - Priority: 1 - Function Name: (anonymous function) | System | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: Hook Defined for Point: AfterRegistrarRegistration - Priority: 1 - Function Name: (anonymous function) | System | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: Hook Defined for Point: CancellationRequest - Priority: 1 - Function Name: (anonymous function) | System | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: Hook Defined for Point: AfterModuleTerminateFailed - Priority: 1 - Function Name: (anonymous function) | System | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: Hook Defined for Point: AfterModuleTerminate - Priority: 1 - Function Name: (anonymous function) | System | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: Hook Defined for Point: AfterModuleUnsuspendFailed - Priority: 1 - Function Name: (anonymous function) | System | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: Hook Defined for Point: AfterModuleUnsuspend - Priority: 1 - Function Name: (anonymous function) | System | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: Hook Defined for Point: AfterModuleSuspendFailed - Priority: 1 - Function Name: (anonymous function) | System | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: Hook Defined for Point: AfterModuleSuspend - Priority: 1 - Function Name: (anonymous function) | System | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: Hook Defined for Point: AfterModuleCreateFailed - Priority: 1 - Function Name: (anonymous function) | System | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: Hook Defined for Point: AfterModuleCreate - Priority: 1 - Function Name: (anonymous function) | System | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: Hook Defined for Point: FraudCheckFailed - Priority: 1 - Function Name: (anonymous function) | System | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: Hook Defined for Point: CancelAndRefundOrder - Priority: 1 - Function Name: (anonymous function) | System | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: Hook Defined for Point: CancelOrder - Priority: 1 - Function Name: (anonymous function) | System | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: Hook Defined for Point: AcceptOrder - Priority: 1 - Function Name: (anonymous function) | System | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: Hook Defined for Point: OrderPaid - Priority: 1 - Function Name: (anonymous function) | System | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: Hook Defined for Point: AfterShoppingCartCheckout - Priority: 1 - Function Name: (anonymous function) | System | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: Hook Defined for Point: UpdateInvoiceTotal - Priority: 1 - Function Name: (anonymous function) | System | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: Hook Defined for Point: InvoiceRefunded - Priority: 1 - Function Name: (anonymous function) | System | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: Hook Defined for Point: InvoiceCancelled - Priority: 1 - Function Name: (anonymous function) | System | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: Hook Defined for Point: InvoicePaid - Priority: 1 - Function Name: (anonymous function) | System | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: Hook Defined for Point: InvoiceCreation - Priority: 1 - Function Name: (anonymous function) | System | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: Hook Defined for Point: TicketClose - Priority: 1 - Function Name: (anonymous function) | System | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: Hook Defined for Point: TicketFlagged - Priority: 1 - Function Name: (anonymous function) | System | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: Hook Defined for Point: TicketStatusChange - Priority: 1 - Function Name: (anonymous function) | System | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: Hook Defined for Point: TicketPriorityChange - Priority: 1 - Function Name: (anonymous function) | System | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: Hook Defined for Point: TicketDepartmentChange - Priority: 1 - Function Name: (anonymous function) | System | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: Hook Defined for Point: TicketAddNote - Priority: 1 - Function Name: (anonymous function) | System | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: Hook Defined for Point: TicketAdminReply - Priority: 1 - Function Name: (anonymous function) | System | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: Hook Defined for Point: TicketUserReply - Priority: 1 - Function Name: (anonymous function) | System | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: Hook Defined for Point: TicketOpen - Priority: 1 - Function Name: (anonymous function) | System | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: Hook Defined for Point: ShoppingCartCheckoutOutput - Priority: -1 - Function Name: (anonymous function) | System | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: Hook Defined for Point: ShoppingCartViewCartOutput - Priority: -1 - Function Name: (anonymous function) | System | 107.23.219.74
12/02/2019 16:08 | Hooks Debug: Hook Defined for Point: ClientAreaHomepage - Priority: -1 - Function Name: (anonymous function) | System | 107.23.219.74

**Comment by henriqueccruz** [comment]
O boleto junto a fatura PDF funcionou corretamente então?
Sobre a linha digitável, em qual dos templates de e-mail você está testando?

**Comment by leonardoasb** [comment]
Estou utilizando no da criação de faturas, lembrete e sobre os vencimentos .... 

Reprarei que ele não está reaproveitando os boletos, é isso mesmo?

**Comment by henriqueccruz** [comment]
Você está usando alguma solução personalizada (add-on ou módulo) para gerenciamento de taxas de gateway?

**Comment by leonardoasb** [comment]
Não .. estou aplicando a taxa diretamente no módulo paghiper

**Comment by henriqueccruz** [comment]
Ja sei o que acontece. Experimenta fazer a seguinte alteração no arquivo que contem o hook.
Procura pela seguinte linha:
`add_hook('EmailPreSend', 1, "display_digitable_line");`

E substitui por:
`add_hook('EmailPreSend', 10, "display_digitable_line");`

Suspeito que algum outro hook esteja substituindo o nosso, que disponibiliza a linha digitável.
Sobre o boleto não reutilizar, é um probleminha com a taxa, ja estamos trabalhando nisso.

**Comment by leonardoasb** [comment]
Fiz a alteração que vc disse, mas não deu certo, inclusive agora gerou dois boletos na paghiper, para o mesmo pedido.

**Comment by leonardoasb** [comment]
UMA DÚVIDA: Quando eu inserir o shortcode da linha digital em lembrete de fatura, pro exemplo, ele vai pegar o código do boleto já gerado ou vai gerar um novo boleto?

**Comment by henriqueccruz** [comment]
Identificamos um probleminha relacionado a taxa, que causa esse comportamento estranho (emissão de novos boletos no mesmo valor).
Sobre a linha digitável, estou com um pouco de dificuldade de replicar seu problema. Pode me dizer qual versão do WHMCS e do gateway está usando?

**Comment by henriqueccruz** [comment]
Bug confirmado, patch em homologação na v2.0.1.2
Fecho este ticket assim que a versão estiver disponível para download.

**Comment by leonardoasb** [comment]
@henriqueccruz obrigado pelo seu apoio e atenção

**Comment by rafso** [comment]
Bom dia, alguma previsão para subir a versão 2.0.1.2 que corrige esse bug?

**Comment by divulgaabc** [comment]
Fiz os testes aqui desta última versão disponível 2.0.1.1, está show, pelo menos nos meus testes, com o WHMCS 7.1.1 rodou perfeito. Creio que a única coisa que falta é a opção de juros diários. Ai fica 100%...
