### ISSUE TITLE
Existem 2 bugs no modulo e ideia de melhoria

### ISSUE THREAD

**Issue by objetivoup** [paghiper/whmcs#45]
Olá boa tarde!

As mudanças estão excelente, parabéns para a equipe e colaboradores.

Existem 2 bugs no modulo:
- Segunda pagina em branco no PDF do boleto em anexo ao e-mail da fatura.
- Pagina em branco no PDF na confirmação de pagamento que seria uma fatura padrão do whmcs com a tarja vender com o Status “pago” e os detalhes da fatura.

Sugestão/Melhorias:
É possível mudar o invoicepdf.tpl para gerar a fatura e o boleto no mesmo PDF?

O boleto na primeira folha e na segundo a fatura padrão (esta ordem ajuda o cliente ver o boleto, neste caso nós podemos informa na mensagem do e-mail para o cliente que o boleto e a fatura seguem em anexo)

E quando o e-mail de confirmação for enviado pelo WHMCS enviaria apenas a folha padrão do whmcs com a fatura com status “pago” e os detalhes da fatura.

Fico a disposição e obrigado!
Abraços
Pedro Santos

**Comment by henriqueccruz** [comment]
Boa tarde, @objetivoup 

Na verdade o invoicepdf.tpl contem um bloco de código que deve ser adicionado ao inicio do invoicepdf.tpl do seu tema. Fazendo como instruido, a fatura PDF apresentará o comportamento que deseja, por padrão. 

Vou manter este issue aberto por hora e pedir a gentileza de fechar assim que conseguir finalizar.

**Comment by objetivoup** [comment]
Olá boa tarde Henrique! Tudo bem?

Muito obrigado eu não sabia que erra para fazer isso, mais deu certo e agora esta da forma que eu precisava.

Abraços
Pedro Santos
Objetivo UP

**Comment by Richards0nd** [comment]
No caso o segundo erro citado ainda existe.
Não na parte do PDF da fatura.

E sim na pagina da fatura!
