### ISSUE TITLE
Como ativo o boleto em anexo com o E-mail

### ISSUE THREAD

**Issue by henriquelucas** [paghiper/whmcs#46]
Olá Henrique, estou com uma dúvida referente a opção de enviar o Boleto junto com a fatura. Já realizei o upload dos arquivos e o Beto já tá gerando normal ente no pelo painel do cliente, porém não está enviando o boleto em anexo.

Nesse caso como realizo a ativação?

**Comment by henriqueccruz** [comment]
Boa tarde @henriquelucas ,

Para implementar o boleto anexo, o processo é bastante simples.
Basta abrir um programa FTP de sua preferência, acessar a pasta de instalação do seu WHMCS, ir até a pasta templates, procurar pelo tema ativo na sua instalação e procurar pelo arquivo invoicepdf.tpl

Baixe e abra em um editor de texto. Daí é só adicionar uma quebra de linha antes da seguinte tag:
`<?php`

e colar o código abaixo:

`<?php
/**
 * Adiciona boleto bancário como página adicional na fatura anexa no WHMCS
 * @author     Henrique Cruz | henriquecruz.com.br
 * @copyright  Copyright (c) 2019 https://henriquecruz.com.br
 */

$whmcs_url = rtrim(\App::getSystemUrl(),"/");
$json_url = $whmcs_url."/modules/gateways/paghiper.php?invoiceid=".$invoiceid."&uuid=".$clientsdetails['userid']."&mail=".$clientsdetails['email']."&json=1";

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $json_url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

$json = curl_exec($ch);
$result = json_decode($json);

$transaction_id = (isset($result->transaction_id)) ? $result->transaction_id : '';
$pdf_url = (isset($result->bank_slip)) ? $result->bank_slip->url_slip_pdf : $result->url_slip_pdf;

if ((in_array($status, array('Unpaid', 'Payment Pending'))) && (isset($pdf_url) && !empty($pdf_url)) && (isset($transaction_id) && !empty($transaction_id))){
    $basedir = dirname(__FILE__).'/../../modules/gateways/paghiper/';
    /* Bloco inicializador do boleto */
    require_once($basedir.'inc/fpdi/fpdi.php');
    $pdf = new FPDI();
    // TODO: Implementar header e footer aqui
    $pdf->SetPrintHeader(false);
    $pdf->SetPrintFooter(false);
    $pdf->AddPage();
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $pdf_url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    $rawdata = curl_exec($ch);
    $filename = $basedir.'tmp/'.$transaction_id.'.pdf';
    $fp = fopen($filename, 'w');
    fwrite($fp, $rawdata);
    fclose($fp);
    $pdf->setSourceFile($filename);
    $tplIdx = $pdf->importPage(1);
    $pdf->useTemplate($tplIdx, 0, 0, 210);
    /* Bloco inicializador do template comum */
    $pdf->SetPrintHeader(false);
    $pdf->SetPrintFooter(false);
    $pdf->AddPage();
} ?>`

A partir daí, os PDFs anexos de fatura vão incluir o boleto bancário correspondente.
Só se certifique de estar utilizando a última versão do plugin (v2.0.1.1)

Vou só pedir a gentileza de atualizar/fechar esse ticket quando finalizar com sucesso.

**Comment by denisgomesfranco** [comment]
Olá @henriqueccruz,
Fiz essa modificação no meu WHMCS mas não deu certo, o boleto não é anexado à fatura em PDF. No entanto o código parece estar rodando pois vejo o boleto gerado no painel do PagHiper.

**Comment by divulgaabc** [comment]
@henriqueccruz hoje precisei gerar um PDF somente da fatura para um cliente, e ao entrar na fatura pelo WHMCS e clicar em "View PDF" ele não gera o PDF, fica um monte de 'códigos estranhos', e fiz também o teste para fazer o Download, e ele vai para mesma tela. Com isso, testei mais uma coisa, fui no Cpanel e tirei os códigos de gerar o boleto no Anexo do E-mail, ai gerou normalmente a fatura em PDF...

Você poderia analisar se há algum jeito de correção de 'bug'? Pois há em alguns casos a necessidade de gerar uma fatura sem o Boleto, ou até mesmo em casos que o cliente paga em dinheiro, etc. Por E-mail é gerada normalmente, só pelo próprio WHMCS que não esta sendo gerado.

**Comment by gwsnet** [comment]
Alguém está anexando boleto ao e-mail ?
eu tento acessar o link mas ele esta quebrado
