### ISSUE TITLE
Redirecionando o cliente pra fatura ao invés do boleto

### ISSUE THREAD

**Issue by f43l** [paghiper/whmcs#47]
Olá, primeiro quero parabenizar pelo excelente módulo, muito bem feito.

No meu sistema o cliente é redirecionado automático para o boleto quando ele fecha um pedido.
Eu queria que ele fosse redirecionado para a fatura, onde tem o botão "Gerar boleto"

Alguém sabe onde eu troco esse redirecionamento?
Obrigado

**Comment by divulgaabc** [comment]
Nas configurações do módulo tem a opção: 'Abrir boleto ao abrir fatura?', basta vocês desselecionar.

**Comment by f43l** [comment]
Já está desmarcado... isso que eu falei só acontece no primeiro pedido, depois que a pessoa vai fechar o pedido e redireciona pro pagamento já aparece o boleto.

**Comment by henriqueccruz** [comment]
Nosso plugin não tem nenhuma funcionalidade que interfira no checkout, além da que o amigo @divulgaabc mencionou. Você se refere ao link enviado por e-mail, que leva diretamente ao boleto bancário?

**Comment by f43l** [comment]
Não...
Quando clica no botão "FINALIZAR PEDIDO" aparece essa tela e ja vai para o boleto:
https://i.imgur.com/ZahDTeCl.png

Eu queria que fosse pra fatura, igual essa tela:
https://i.imgur.com/WkjOfgQ.png
