### ISSUE TITLE
Boleto em branco e duplicado

### ISSUE THREAD

**Issue by yvescleuder** [paghiper/whmcs#48]
Bom dia,

Estou desativando a opção "Caso selecione não, boletos bancários e lihnas digitáveis serão selecionadas somente caso o cliente selecione "boleto Bancário" (ou o nome que você configurar no primeiro campo de configuração) como método de pagamento padrão."

Está acontecendo isso: quando o método de pagamento do cliente é qualquer outra coisa menos "boleto Bancário" o PDF que vai para o e-mail vai em branco, está correto? Não deveria vir algo informando que o meio de pagamento não é boleto em vez do PDF ir em branco?
Outra coisa, não sei por qual motivo, mas está chegando 2 e-mails sobre boleto gerado. Tanto quando roda a cronjob quanto ele clica em gerar boleto no whmcs.
-> https://prnt.sc/mwsrjc
Se criar um novo pedido com boleto bancário, ele também gera 2 e-mails... não sei o porque.

**Comment by yvescleuder** [comment]
Já até imagino o porque de dois boletos
1) Porque gera a fatura para database;
2) Porque gera a fatura para ser enviado por e-mail;
É isso? Para o cliente fica estranho isso...

**Comment by yvescleuder** [comment]
Questão de enviar boleto em branco quando não está selecionado a opção boleto bancário resolvi com um else.
`else {
    $noboleto = file_get_contents($whmcs_url."/modules/gateways/paghiper.php?invoiceid=".$invoiceid."&uuid=".$clientsdetails['userid']."&mail=".$clientsdetails['email']."");
    $pdf->writeHTML($noboleto, true, false, false, false, '');
}
tirando a opção json da url e inserindo direto na variavel $pdf do invoicepdf que é padrão, e não da sua biblioteca.`

**Comment by TecSecret** [comment]
@yvescleuder em que parte do invoicepdf deve-se colocar esse else que você mensionou.

**Comment by henriqueccruz** [comment]
Na verdade, isso acontece quando o código fornecido pra inserção no invoicepdf.tpl do seu tema é inserido de maneira incorreta.
Para evitar esse comportamento, basta inserir o código no início do seu arquivo, não substituindo o restante.

**Comment by yvescleuder** [comment]
E em relação ao boletos duplicados? É normal?
Quando o cliente cria um pedido, e já gera 2 ou 3 boletos.

**Comment by henriqueccruz** [comment]
Não deveria ocorrer, definitivamente.
Você configurou alguma taxa adicional para emissão de boletos?

**Comment by yvescleuder** [comment]
Somente taxa fixa de 1.85

**Comment by yvescleuder** [comment]
Acabei de ver, está gerando 3 boletos, tudo na mesma data e hora.. tem como você fazer o teste aí? Se quiser vamos conversar no whatsapp.
(099)98257-7171

**Comment by souzadavi** [comment]
> Na verdade, isso acontece quando o código fornecido pra inserção no invoicepdf.tpl do seu tema é inserido de maneira incorreta.
> Para evitar esse comportamento, basta inserir o código no início do seu arquivo, não substituindo o restante.
> Por favor confirme se executando os passos informados o problema persiste.

Comigo esta acontecendo o mesmo erro, quando habilita a opção para não enviar o boleto para pessoas que não possuem o metodo de pagamento definido. 

Eu subi o arquivo invoicepdf.tpl  que esta nesse repositório aqui, tenho que fazer algo mais para corrigir?

Obrigado por compartilhar o código.
