### ISSUE TITLE
Armazenar boleto

### ISSUE THREAD

**Issue by tgssb** [paghiper/whmcs#49]
Olá, gostaria de saber porque do sistema gerar um novo boleto a cada notificação que o meu cliente recebe. Alguns estão reclamando de boletos duplicados no DDA.

**Comment by henriqueccruz** [comment]
Olá @tgssb , confirma pra mim se está utilizando algum tipo de taxa personalizada pra emissão do boleto por favor.

**Comment by tgssb** [comment]
Está sim, no campo tarifa fixa

**Comment by kdkhost** [comment]
positivo amigo @tgssb eu tbm estou com o mesmo problema e gostaria de saber se tem alguma solução para este caso?
@henriqueccruz eu tambem uso taxa fixa de R$ 1,90 e acontece o mesmo com o relatado acima veja abaixo o que ocorre:
https://nimb.ws/6wAozi

print da configuração do môdulo:
https://nimb.ws/uWPFcw
