### ISSUE TITLE
Checkout Transparente

### ISSUE THREAD

**Issue by DannAraujo** [paghiper/whmcs#5]
Olá, o Checkout Transparente está funcionando legal mas a taxa fixa não é adicionada ao valor da fatura, testando sem o checkout transparente a taxa fixa foi adicionada.

**Comment by henriqueccruz** [comment]
Olá Dann, consegui reproduzir seu problema.
Vou lançar uma atualização que corrige isso ainda hoje.

**Comment by DannAraujo** [comment]
Tudo bem, muito obrigado!

**Comment by DannAraujo** [comment]
Novidades do mesmo?

**Comment by alexandresqf** [comment]
Bom dia henriqueccruz
Estou com um problemas, quando o cliente clica em GERAR BOLETO ele não é gerado e fica a página em branco, o que pode ser? configuração na Hospedagem ?

**Comment by alexandresqf** [comment]
Resolvido pessoal !
No meu caso era o Administrador atribuído	
Era atribuído o padrão "admin" porém o meu o admin login é: admin-mm4
Coloquei e foi perfeitamente ! :)

**Comment by alexandresqf** [comment]
Realmente a Taxa Fixa não funciona, aguardando att :)

**Comment by henriqueccruz** [comment]
Olá @DannAraujo  e @alexandresqf, lançamos a versão 1.12 que corrige a questão das taxas e introduz algumas melhorias.
Caso tenham problemas, por favor reabram o ticket.
