### ISSUE TITLE
Alteração do vencimento não se aplica mais

### ISSUE THREAD

**Issue by ownserver** [paghiper/whmcs#50]
Primeiramente quero parabenizar pelos updates, o plugin está chegando próximo ao ideal.

Estou com um problema frequente que na versão antiga não tinha, como todo brasileiro muitos clientes deixam o vencimento passar 2,3, até 7 dias em alguns casos.

Então eu vou lá, altero a data do vencimento (manualmente) e então reemito outra fatura.
Algumas vezes ele emite normalmente a fatura respeitando a nova data mas muitas vezes (95%) ele mantem a data do vencimento "original" não permitindo o pagamento da fatura (testado no Itaú Bankline e Bradesco).

Minhas confs: https://i.imgur.com/q7ZVfRF.png

Um forte abraço e parabéns mais uma vez!

**Comment by henriqueccruz** [comment]
Problema persiste na v2.0.1.2 e/ou v2.0.1.3?
Confirma pra gente por favor.

**Comment by ownserver** [comment]
O problema foi resolvido com a nova versão.
