### ISSUE TITLE
Cliente sem CPF/CNPJ cadastrado

### ISSUE THREAD

**Issue by divulgaabc** [paghiper/whmcs#51]
Quando um cliente não tem o CPF/CNPJ cadastrado, esta indo para uma página de erro! Não teria como nesta página ter um link para o cliente ir no cadastro e inserir estes e outros dados que estejam faltando?

**Comment by TecSecret** [comment]
@divulgaabc eu acho que é muito mais fácil você solicitar esses dados ao seu cliente no momento do cadastro, pois hoje é lei ter cpf para boletos. Pois o mesmo sempre ficar digitando os dados não é legal, gera muitas páginas e desistências de pagamento.
