### ISSUE TITLE
Boleto em PDF está com a segunda página em branco

### ISSUE THREAD

**Issue by deguirbr** [paghiper/whmcs#52]
Prezados, configurei no meu WHMCS a última versão até hoje 2.0.1.1 do módulo PagHiper e quando chega o e-mail da geração da fatura com o boleto em PDF em anexo, o arquivo está vindo com 2 páginas, sendo a segunda em branco. Não afeta em nada mais estou comentando para que fique ainda mais perfeito!

**Comment by deguirbr** [comment]
Normalizado aqui. O que está acontecendo agora mais não sei se é do PagHiper é o anexo da comprovação de pagamento está vindo um pdf em branco.

**Comment by henriqueccruz** [comment]
@deguirbr - Normalmente, quando isso acontece é por conta de erro na instalação do bloco da Paghiper.
O código contido no arquivo invoicepdf.tpl fornecido com o plugin deve apenas ser adicionado no inicio do invoicepdf.tpl do seu tema, e não substituir o conteúdo original dele.
Checa se é esse o caso, 95% de chance de resolver seu problema em definitivo.

**Comment by henriqueccruz** [comment]
Caso continue com problemas, vou pedir a gentileza de abrir novo ticket de suporte.
Estou encerrando este para melhor organização dos tickets.
