### ISSUE TITLE
Fatal error: Cannot redeclare create_table()

### ISSUE THREAD

**Issue by gcampanholi** [paghiper/whmcs#53]
Subi os arquivos conforme solicitado e o erro abaixo é exibido quando tento abrir os meios de pagamentos no admin.

Fatal error: Cannot redeclare create_table() in /home/marketplace/public_html/modules/gateways/paghiper.php on line 473

HP Version 7.2.13
WHMCS Version 7.6.1

**Comment by henriqueccruz** [comment]
@gcampanholi 
Por favor utilize a versão mais recente disponibilizada no repositório.
O erro apresentado foi corrigido.
