### ISSUE TITLE
Pagamento Duplicado

### ISSUE THREAD

**Issue by ddrhost** [paghiper/whmcs#54]
Olá. Estou utilizando o módulo em sua versão mais recente e uma das faturas recebeu a confirmação do pagamento duplicado, adicionando créditos na conta do cliente em meu WHMCS. Verifiquei no site do PagHiper e o cliente pagou o boleto apenas uma vez, corretamente.

Seria interessante adicionar alguma função para evitar o retorno duplicado.

Obrigado.

**Comment by henriqueccruz** [comment]
@ddrhost - o problema persiste?
Queremos entender melhor, nos dê mais detalhes, caso ainda aconteça.

**Comment by ddrhost** [comment]
Sim, ocorreu novamente hoje em 1 pagamento.

Seria interessante criar uma condição no sistema de retorno automático, que se o Status da fatura estiver como Pago, ignorar um nova transação na fatura.

**Comment by ddrhost** [comment]
O código da transação é o mesmo, então o cliente não pagou o boleto duas vezes. Foi um retorno duplicado mesmo.

Transação: 1WRUQCM5SE5NGYTV

**Comment by henriqueccruz** [comment]
Vamos trabalhar nisso.
Reabrindo o ticket e atualizamos assim que estiver disponível para testes.

**Comment by henriqueccruz** [comment]
Implementamos mais algumas medidas pra evitar esse tipo de situação, por favor atualize sua instalação.
Importante notar que temos um novo hook e nova lógica de inclusão de boletos. Você precisará atualizar seu invoicepdf.tpl
