### ISSUE TITLE
2 via de Boleto

### ISSUE THREAD

**Issue by henriquelucas** [paghiper/whmcs#55]
Olá amigos, agradeço desde já por fornecer um módulo de pagamento tão completo como esse. Gostaria de vê se seria possível adicionar uma opção de segunda via, como funcionária essa segunda via? Através de uma página adicional no whmcs o cliente precisaria apenas digital seu E-mail, CPF ou algum dado que identifica-se o usuário, sem necessidade dele ter que acessar a conta. Essa segunda via seria enviada para seu e-mail ou poderia até redirecionar o cliente já para página do boleto, sendo mais apropriado enviar a fatura por e-mail pra evitar vazamento de dados pessoais.

**Comment by henriquelucas** [comment]
Porque necessito de algo assim, muito de nossos clientes, são pessoa leigas e muitas delas esquecem das senhas, ou tem preguiça de acessar a conta pra gerar uma fatura.

**Comment by divulgaabc** [comment]
Hoje em dia não há necessidade de emitir uma segunda via, por serem boletos registrados mesmo após o vencimento o cliente pode pagar em qualquer banco, e se você configurar a multa ainda atualiza sozinho. Basta colocar nas configurações quantos dias após o vencimento você autoriza o recebimento no mesmo boleto...

**Comment by ddrhost** [comment]
Se você utilizar a URL abaixo e enviá-la por e-mail, o cliente poderá emitir uma via atualizada do boleto bancário, sempre com o mesmo link.

{$whmcs_url}modules/gateways/paghiper.php?invoiceid={$invoice_num}&amp;uuid={$client_id}&amp;mail={$client_email}

**Comment by henriqueccruz** [comment]
É possível fazer, temos tabelas no banco de dados que podem ser consultadas mas a integração deveria ser feita manualmente.
Esse tipo de integração fica fora do escopo de desenvolvimento do plug-in.
Como o amigo @ddrhost disse, ja temos métodos que facilitam a busca por uma segunda via atualizada do boleto.

**Comment by nuevox** [comment]
Olá,

Criei o seguinte arquivo para você hospedar no seu servidor. Basta apenas inserir suas credenciais que irá funcionar.

[segunda-via-paghiper.zip](https://github.com/user-attachments/files/28030731/segunda-via-paghiper.zip)
