### ISSUE TITLE
Erro na geração de Faturas

### ISSUE THREAD

**Issue by Richards0nd** [paghiper/whmcs#56]
Olá, recentemente eu atualizei para a versão mais atual do modulo,
Só que percebi alguns bugs no sistema.

Ex: Quando alguém gera um pedido, e paga usando o Saldo da conta (sem antes selecionar o metodo de pagamento)
o sistema cria um boleto para essa fatura, mesmo estando desmarcada a opção de gerar boleto automaticamente, além de que ele envia para o email, um boleto de 1 real, sendo q como foi pago por saldo na conta, não deveria enviar o boleto para o cliente.

Outro erro: Quando algum cliente gera uma fatura, mesmo que não pague com o saldo na conta (no caso ele não tem saldo na conta, gera um pedido, seleciona outro método de pagamento q não é o Boleto da PagHiper) o sistema não está enviando ele para a fatura, ele fica em uma Tela Branca, ou aparece que a pagina não foi encontrada.
Creio que tudo isso deve ser algum bug no hook que foi criado.

**Comment by Richards0nd** [comment]
Há, mais 1 coisa.
Como ele não está enviando para a pagina da fatura paga, quando o cliente acessa a fatura pelo menu de faturas, ai é q ele mostra a pagina que o pedido foi feito (Que deveria mostrar na hora q o pedido é feito, só que fica a tela em branco)

**Comment by Richards0nd** [comment]
Na verdade fiz os testes aqui, e esse erro só apresenta se eu usar o codigo de enviar a fatura por email (a fatura em pdf)
Fora isso o hook não está causando problema.

**Comment by henriqueccruz** [comment]
Confirma pra mim qual versão do WHMCS e do módulo da PagHiper está utilizando por favor.
Vamos tentar replicar o erro citado.

**Comment by henriqueccruz** [comment]
Por falta de comunicação, estou considerando esta issue como resolvida.
Caso o problema persista por favor abra outro ticket de suporte.
