### ISSUE TITLE
Problema com valores

### ISSUE THREAD

**Issue by ddrhost** [paghiper/whmcs#58]
Olá, tudo bem?

O módulo possui um problema com a atualização de valores. Se uma fatura possui por exemplo R$ 100,00 de valor, o cliente efetua um pagamento parcial de R$ 10,00 por depósito bancário e o administrador adicionar este valor como uma transação da mesma fatura, o boleto não é atualizado com o valor restante de R$ 90,00.

Somente é atualizado se adicionar os R$ 10,00 como créditos e o cliente aplicar na fatura.

Obrigado.

**Comment by henriqueccruz** [comment]
@ddrhost 
Confirma pra mim por gentileza qual versão do WHMCS, qual versão do módulo e se o problema ainda persiste?

**Comment by ddrhost** [comment]
Infelizmente sim, o problema permanece.

Fiz uma simulação criando uma nova fatura com o valor de R$ 200,00. Adicionei um pagamento parcial no valor de R$ 50,00 que o cliente fez por depósito e restou o valor de R$ 150,00 em aberto para que o cliente gere o boleto.

Mas o valor é gerado com o valor total de R$ 200,00 e não R$ 150,00.

Se o cliente gerar uma fatura no WHMCS de R$ 50,00 para ADICIONAR FUNDOS e aplicar a fatura, o boleto bancário é gerado normalmente com o valor restante de R$ 150,00, mas se o administrador ou a equipe adicionar um pagamento parcial a fatura pelo painel administrativo, o boleto do cliente não é atualizado. Mesmo o cliente clicando na fatura do WHMCS para gerar um novo boleto.

**Comment by henriqueccruz** [comment]
Vamos corrigir isso.
Atualizo este ticket assim que estiver disponível pra teste e confirmação

**Comment by henriqueccruz** [comment]
@ddrhost, baixa a última versão do meu repositório de desenvolvimento por favor.
Deve corrigir seu problema. Nos avise caso tenha algum problema, considere essa release uma versão beta. Temos mais implementações pra fazer até o lançamento da próxima versão.

**Comment by ddrhost** [comment]
Resolvido. Obrigado.
