### ISSUE TITLE
Data de vencimento nao muda

### ISSUE THREAD

**Issue by brinsleyparagao** [paghiper/whmcs#59]
Quando um boleto vence e o cliente reabre a fatura, a data de vencimento não altera.

E mesmo o boleto sendo registrado que permite pagamento depois do vencimento, no próprio boleto tem um aviso de NÃO RECEBER DEPOIS DO VENCIMENTO, e nem existe a possibilidade de se criar outro novo boleto pois todos os demais são a 2 via do primeiro criado.

Ou seja fica sem ter como pagar pois não existe possibilidade de pagamento.

**Comment by henriqueccruz** [comment]
Na verdade esse comportamento é esperado. Um boleto com nova data de vencimento é gerado quando se emite segunda via após a data de vencimento original, caso a configuração da sua instalação permita (você mesmo define como quer que isso funcione, nas opções do módulo da PagHiper).

Caso tenha configurado para não permitir novas reemissões, basta alterar a data de vencimento na configuração da fatura.
