### ISSUE TITLE
retorno automatico

### ISSUE THREAD

**Issue by carlosdfoz** [paghiper/whmcs#6]
Olá o retorno automático não funcionou aqui

**Comment by henriqueccruz** [comment]
Olá @carlosdfoz, você observou algum erro no log?
Quando um boleto é gerado, por exemplo, o log de transações informa que o boleto foi gerado?

**Comment by carlosdfoz** [comment]
não apresenta erro, mostra no log que o boleto foi gerado.

**Comment by henriqueccruz** [comment]
Entendo. O que você está dizendo é que os boletos compensados não estão sendo marcados como pagos no WHMCS?

**Comment by carlosdfoz** [comment]
isso mesmo

**Comment by henriqueccruz** [comment]
Dentro de uma fatura gerada, o log mostra quando as faturas são emitidas?

**Comment by carlosdfoz** [comment]
exibe esse formato de data e hora 03/05/2017 10:02
