### ISSUE TITLE
Utilização do "Reservado" para aprovação do pagamento

### ISSUE THREAD

**Issue by agenciah1code** [paghiper/whmcs#61]
Alguém já conseguiu configurar ou modificar o módulo para que o status "Reservado" faça com que a fatura seja aprovada?

Aguardo retorno.

**Comment by henriqueccruz** [comment]
Olá @agenciah1code 
Não há planos de implementarmos esse comportamento, visto que um pequeno percentual das confirmações não se concretizam em pagamentos.

Você pode modificar o gateway para que isso ocorra mas nós não recomendamos.
