### ISSUE TITLE
Não envia email com Fatura via painel de faturas dá erro.

### ISSUE THREAD

**Issue by CriarSitesBr** [paghiper/whmcs#62]
Pessoal... Instalei o PageHiper está quase tudo funcionando. Pagamentos, retorno Automático.

- Eu fiz o procedimento Como ativo o boleto em anexo com o E-mail e funcionou mas....

Porém se eu entro na fatura do cliente e clico em enviar Email. está dando essa mensagem e não envia a fatura no email, Mesmo se o usuário utilizar outra forma de pagamento.

Depois de instalar o PageHiper eu não mudei nada no meu template de email. Preciso fazer algo?

Email Sending Failed - Email message rendered empty - please check the email message Smarty markup syntax

Alguém pode me ajudar por favor.

**Comment by henriqueccruz** [comment]
Checa se o nosso hook (includes/hooks/create_paghiper_slip.php) está colocado corretamente na pasta. Além disso, seria legal também darmos uma olhada em como está seu template de e-mail.
Aparentemente tem uma tag malformada, causando erro no envio.

Coloca um print do seu template pra podermos te ajudar melhor

**Comment by CriarSitesBr** [comment]
/user/public_html/central/includes/hooks/create_paghiper_slip.php   Está Lá Normalmente.
Abaixo o meu template.

`<table style="width: 80%;" border="0" cellspacing="0" cellpadding="0">
<tbody>
<tr>
<td>
<p style="text-align: center;"><span style="color: #999999; font-size: medium;"><strong>NOVA FATURA GERADA</strong></span></p>
<p>Olá {$client_name} sua fatura já está disponível,  M<span style="font-family: inherit; font-size: inherit; font-style: inherit; font-variant-ligatures: inherit; font-variant-caps: inherit;">étodo de pagamento é: {$invoice_payment_method}</span></p>
<p><strong>O PAGAMENTO PODE SER FEITO VIA DEPÓSITO OU TRANSFERÊNCIA BANCÁRIA:</strong></p>
<p><strong>Por favor nos envie os dados do depósito ou transferencia assim que efetuado para dar baixa nas faturas.<br /><br /><br />Fatura Gerada: </strong>{$invoice_date_created} <strong>Vencimento:</strong> {$invoice_date_due}</p>
<p><strong>Valor:</strong> {$invoice_total} <strong>Fatura:</strong> {$invoice_num} <strong>Forma de Pagamento:</strong> {$invoice_payment_method}</p>
<p><strong>Itens da Fatura</strong></p>
<p style="text-align: justify;"><span style="font-family: inherit; font-size: inherit; font-style: inherit; font-variant-ligatures: inherit; font-variant-caps: inherit;">{$invoice_html_contents} </span><span style="color: #626262; font-style: inherit; font-variant-ligatures: inherit; font-variant-caps: inherit; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 13px; text-align: justify; background-color: #fafafa;">{assign var='hash' value=$client_email|cat:"</span><span style="text-align: justify; background-color: #fafafa; font-size: 13px;"><span style="font-family: Verdana, Arial, Helvetica, sans-serif;"></span></span><span style="color: #626262; font-style: inherit; font-variant-ligatures: inherit; font-variant-caps: inherit; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 13px; text-align: justify; background-color: #fafafa;">"}</span></p>
<p><a style="background-color: #fafafa; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 13px; text-align: justify;" title="Pagar Agora" href="{$whmcs_url}autologin-faturas.php?email={$client_email}&amp;invoice={$invoice_num}&amp;hash={$hash|md5}" target="_blank" rel="noopener"><img title="Efetuar o pagamento Agora Mesmo" src="http://superhospedagens.com/Imagens/pagar-agora.png" alt="Efetuar o pagamento Agora Mesmo" width="300" height="80" /></a><br /><br /><strong style="font-family: inherit; font-size: inherit; font-style: inherit; font-variant-ligatures: inherit; font-variant-caps: inherit;">Obs: Aconselhamos Pagar sempre 3 dias Antes do Vencimento, caso não vá renovar é necessário avisar com 7 dias de antecendência.</strong></p>
<p><strong>ATENÇÃO: SE FOR EFETUAR O PAGAMENTO VIA BOLETO... O VENCIMENTO DO BOLETO VAI SAIR COM UM ATRASO DE 3 DIAS, PORÉM DEVE-SE LEVAR EM CONSIDERAÇÃO A DATA DO VENCIMENTO DA FATURA EM NOSSO SISTEMA.</strong></p>
<p>Sr(ª) {$client_name} Essa mensagem é gerada automaticamente então se sua fatura já tenha sido quitada por favor desconsiderar. Obrigado pela sua compreesão.</p>
</td>
</tr>
<tr>
<td>
<p align="justify">ATENÇÃO: Lembramos que após <strong>2</strong> dias (úteis) de atraso, a sua conta poderá ser bloqueada em qualquer momento e após 15 dias de atraso a conta poderá ser excluída de nossos registros sem prévio aviso, e todo o conteúdo de sua conta ou aplicação (site) será perdido, tornando impossível a sua recuperação.</p>
<p align="justify">Caso o pagamento ainda não tenha sido realizado, pedimos a gentileza de fazê-lo o antes possível, evitando assim o bloqueio do seu site. Lembramos que alguns pagamentos somente são reconhecidos após compensação bancaria.</p>
<p>{$signature}</p>
</td>
</tr>
</tbody>
</table>`


CONTEÚDO DO ARQUIVO CREATE_PAGEHIPER_SLIP.PHP
`<?php
/**
 * Adiciona boleto bancário e link direto para boleto no WHMCS
 * @author     Henrique Cruz | henriquecruz.com.br
 * @copyright  Copyright (c) 2019 https://henriquecruz.com.br
 */

if (!defined("WHMCS")) die("This file cannot be accessed directly");
function display_digitable_line($vars) {
    $merge_fields = [];
    $email_template = $vars['messagename'];
    $invoice_id = $vars['relid'];

    $target_templates = array('Invoice Created', 'Invoice Payment Reminder', 'First Invoice Overdue Notice', 'Second Invoice Overdue Notice', 'Third Invoice Overdue Notice');

    if(in_array($email_template, $target_templates)) {
        // Todo: 
        $invoice = mysql_fetch_array(mysql_query("SELECT tblinvoices.*,tblclients.id as client_id, tblclients.email FROM tblinvoices INNER JOIN tblclients ON tblclients.id=tblinvoices.userid WHERE tblinvoices.id='$invoice_id'"));

        $whmcs_url = rtrim(\App::getSystemUrl(),"/");
        $json = file_get_contents($whmcs_url."/modules/gateways/paghiper.php?invoiceid=".$invoice_id."&uuid=".$invoice['client_id']."&mail=".$invoice['email']."&json=1");
        $result = json_decode($json);
        if(isset($result->digitable_line) && !empty($result->digitable_line)) {
            $digitable_line = $result->digitable_line;

            $merge_fields['linha_digitavel'] = '<span>Linha digitável: <br><span style="font-size: 16px; color: #000000"><strong>';
            $merge_fields['linha_digitavel'] .= $digitable_line;
            $merge_fields['linha_digitavel'] .= '</strong></span></span>';
        }

    }
    return $merge_fields;
}
add_hook('EmailPreSend', 1, "display_digitable_line");`

**Comment by henriqueccruz** [comment]
Pelo que dá pra ver, tem um parâmetro extra sendo inserido na URL do boleto (hash|md5)
Experimenta tirar esse pedaço da URL e testa se seu e-mail volta a funcionar.
A sintaxe da URL do boleto bancário está correta.

**Comment by CriarSitesBr** [comment]
Éra isso mesmo. O problema era essa linha antiga de Auto-Login, retirei ela e tudo voltou a funcionar. Um forte Abraço.

**Comment by henriqueccruz** [comment]
Excelente. 
Vou encerrar este ticket então, se precisar de suporte novamente por favor abra outro ticket.
