### ISSUE TITLE
Cancelamento de fatura no WHMCS - cancelar no paghiper

### ISSUE THREAD

**Issue by conexaoalisson** [paghiper/whmcs#65]
Olá, Amigos tudo bem?
vocês estão de parabéns por fazer o modulo.

Muito bem trabalhado.
Gostaria de deixar uma sugestão para novas alterações.

Bom, sobre a geração de boleto de forma automática quando gera a fatura
Isso é muito show.. aumentou até a conversão pagamentos

Tem alguns clientes que pagar via cartão de créditos.
Ou até mesmo transfere para conta bancaria ao invés do boleto 

Minha sugestão é 
1º Quando a gente cancela a fatura no WHMCS cancelar o boleto no PagHiper

2º Não sei se seria viável. caso o pagamento seja adicionado manualmente,
automaticamente fosse cancelado o boleto no paghiper.

Para não ficar aquele monte de boleto pendente no paghiper
já que esta gerando de forma automática.

As vezes o cliente questiona o recebimento de e-mail etc.

Parabéns  pelo modulo.

**Comment by henriqueccruz** [comment]
Olá @conexaoalisson, obrigado pelas sugestões.
A sugestão número 1 é algo que ja vinhamos planejando a algum tempo, muito provavelmente entrará na próxima update.
A sugestão 2 realmente é inviável. Vamos deixar o ticket aberto e atualizamos quando a update contendo o item 1 for lançada.

Obrigado!

**Comment by henriqueccruz** [comment]
Sugestão implementada na v2.0.3
Vou pedir a gentileza de abrir outro ticket caso tenha dificuldades.
