### ISSUE TITLE
BUG ao gerar boleto com saldo positivo na fatura.

### ISSUE THREAD

**Issue by conexaoalisson** [paghiper/whmcs#67]
Olá, Pessoal do Paghiper.
Novamente, excelente modulo.

Hoje gostaria de reportar um BUG,. 
Já tem algum tempo que venho tendo esse problema
e nem cheguei a mencionar na ultima sugestão que fiz aqui. 

Eu adiciono o saldo positivo a uma fatura.
E quando vou gerar o boleto, o modulo não abate o valor 

EX; eu coloco um crédito na fatura de R$ 100.00 parcial ao total de R$ 350.00
As vezes a gente recebe em dinheiro. eu tenho costume de adicionar saldo a uma fatura.

Bom, a fatura de R$ 350  fica no valor de R$ 250.00 com o saldo adicionado parcialmente.
Quando vou gerar o boleto a fatura originalmente fica com o valor R$ 350 no boleto do paghiper.

Isso seria valido para as situações aonde o cliente já possui um saldo positivo na conta.
E automaticamente e gerado um boleto puxando o saldo positivo. 

Basicamente é isso. 
Muito Obrigado pelo modulo. excelente trabalho. 
Cada dia melhor que os concorrentes rs. 

Só faltou um cartão de credito. ai abandonava os outros portais. 
Parabéns pessoal. Bom final de ano

**Comment by henriqueccruz** [comment]
Olá @conexaoalisson , boa noite
Realmente, estamos cientes deste problema. Abordamos ele na versão v2.0.2.
Confirma pra gente qual versão está utilizando por favor?

Tentei replicar o problema com a última versão e não consegui.

**Comment by henriqueccruz** [comment]
Bom, vou fechar o ticket para mantermos as issues organizadas cronologicamente.
Caso tenha problemas com a v2.0.3, por favor abra novo ticket.

**Comment by conexaoalisson** [comment]
Amigo.....
Parabéns..

você mandou bem nessa atualização
Como a gente faz uma doação?

Ele funcionou muito bem.
Adicionou o saldo, a fatura e na hora de gerar a fatura cancelou a outra fatura com o outro valor

Cara incrível

**Comment by henriqueccruz** [comment]
Ainda temos muitas melhorias a implementar, nosso objetivo é ser o melhor gateway de boletos do mercado e ficamos felizes com o seu feedback. Obrigado!

Você pode contrubuir indicando a PagHiper pra mais gente!
