### ISSUE TITLE
Boleto em branco

### ISSUE THREAD

**Issue by rafso** [paghiper/whmcs#68]
Minha integração estava funcionando corretamente, e após a atualização de versão parou, eu acredito sinceramente que seja coincidência com algo que tenha mudado no servidor, mas não consigo localizar o que é, verifiquei os pre requisitos, estou com PHP 7.0
Todas as minhas faturas desse mês geraram corretamente no paghiper mas no e-mail foram em branco, meu invoicepdf está conforme o indicado, já voltei para o código anterior que funcionava e continua indo em branco, alguém tem alguma ideia?

**Comment by henriqueccruz** [comment]
Olá @rafso 
Abordamos esse problema na última versão, por favor atualize sua instalação.
Importante notar que será necessário atualizar seu invoicepdf.tpl, modificamos a lógica de inclusão dos boletos.

Por favor abra novo ticket caso tenha problemas.

**Comment by vhosts** [comment]
Aconteceu o mesmo comigo. Estava funcionando normal, mas começou a exibir boleto em branco. Baixei novamente o pacote do site da paghiper e refiz o erro continua. Uso whmcs 8.1.1, plugin paghiper versão 2.1, PHP 7.3.

**Comment by henriqueccruz** [comment]
@vhosts Atualiza para a última versão por favor.
Adicionamos mais informações de log e telas de status.
Caso o problema persista, abra outro ticket por favor

**Comment by vhosts** [comment]
Uso a última versão. Problema persiste.

**Comment by henriqueccruz** [comment]
@vhosts , consegue mandar uma mensagem para a nossa central de integração (integracao@paghiper.com)?
Estamos aguardando seu contato para olhar mais de perto e ir diretamente na causa do problema.

**Comment by henriqueccruz** [comment]
Por falta de interação, estou fechando este ticket.
Caso o problema persista, proceda como informado na mensagem acima. Estaremos prontos para ajudar/investigar o problema.
