### ISSUE TITLE
Invoice PDF

### ISSUE THREAD

**Issue by souzadavi** [paghiper/whmcs#69]
Olá notei que toda vez que o WHMCS atualiza preciso editar o arquivo: invoicepdf.tpl

Sera que é possível inserir essa informação via hooks? Porque assim evitaria esse trabalho toda nova atualização do WHMCS.

**Comment by henriqueccruz** [comment]
Boa noite @souzadavi 
Infelizmente não é possível (não sem fugir bastante do escopo de gateway de pagamento)
O WHMCS não oferece hooks para monitorarmos a atualização do sistema e, caso você utilize um template padrão (como o six, por exemplo), precisará sempre reinserir as modificações para que o boleto seja adicionado junto.

Uma opção interessante (ou pelo menos, viável) é tornar o arquivo invoicepdf.tpl somente-leitura, ou remover as permissões de escrita pra ele via FTP ou chmod.
