### ISSUE TITLE
Erro ao Acessar Portais de Pagamentos

### ISSUE THREAD

**Issue by MarksEliel** [paghiper/whmcs#7]
Olá, quando tento acessar Opções > Pagamentos > Portais de Pagamentos apresenta o seguinte erro: http://prntscr.com/f3mbzp

Com a versão anterior do módulo isso não acontecia...

**Comment by MarksEliel** [comment]
Corrigi, alterando a linha 447 para $whmcsAdmin = 'LOGIN_ADMIN';

**Comment by henriqueccruz** [comment]
Bastava informar o login do admin na página de configuração do Gateway.
Caso tenha problemas, por favor reabra o ticket.
