### ISSUE TITLE
cancel_paghiper_slip.php

### ISSUE THREAD

**Issue by ddrhost** [paghiper/whmcs#72]
Olá.

Ao ativar o Hook "cancel_paghiper_slip.php", as confirmações de pagamentos de outros módulos não estão sendo feitas, inclusive ocorre no módulo nativo do PayPal.

O pagamento é recebido, a transação adicionada na fatura, mas o status permanece como "Não Pago".

O problema foi resolvido após removermos este Hook.

**Comment by henriqueccruz** [comment]
Bom dia @ddrhost,
Estamos replicando o problema. Uma update menor deve ser lançada no repositório em breve para resolver este ticket.

**Comment by henriqueccruz** [comment]
Você nos faria um favor?
Checa se removendo a linha 80 do arquivo /includes/hooks/cancel_paghiper_slip.php, seu problema é resolvido.

**Comment by ddrhost** [comment]
> Você nos faria um favor?
> Checa se removendo a linha 80 do arquivo /includes/hooks/cancel_paghiper_slip.php, seu problema é resolvido.

Infelizmente não. O problema permanece.

**Comment by henriqueccruz** [comment]
Creio que seja um problema nas chamadas, mas não consegui replicar.
Você poderia ativar a geração de arquivos de log no seu ambiente PHP por favor?
Continuaremos tentando replicar o problema por aqui.

**Comment by ddrhost** [comment]
> Creio que seja um problema nas chamadas, mas não consegui replicar.
> Você poderia ativar a geração de arquivos de log no seu ambiente PHP por favor?
> Continuaremos tentando replicar o problema por aqui.

Nenhum erro é retornado. Após comentar a linha 78 o problema foi resolvido, mas não sei se afeta o funcionamento do Hook.

**Comment by henriqueccruz** [comment]
O hook vai deixar de cancelar boletos quando pagamentos parciais forem feitos.
Para pagamentos no valor integral, o hook continua funcionando normalmente.
De qualquer maneira, estamos estudando a melhor maneira de resolver esse problema. Manteremos o ticket aberto para te informar sobre novidades.

Obrigado por reportar.

**Comment by conexaoalisson** [comment]
Olá, Bom dia!.
O meu também aconteceu isso. 

Os pagamentos são recebidos porem não baixa no WHMCS

**Comment by paulonichio** [comment]
Olá, tudo bem? 

Mesmo problema por aqui. 
Precisei restaurar o módulo para a versão 2.0.1 para que o funcionamento da baixa voltasse a ocorrer.

**Comment by henriqueccruz** [comment]
Bom dia pessoal,
Uma update menor será lançada amanhã, abordando esse problema.
Aviso por aqui quando estiver disponível.

**Comment by henriqueccruz** [comment]
Olá pessoal, por favor atualizem os arquivos da sua pasta /includes/hooks
Caso vocês tenham boletos não sincronizados, elaboramos este script pra atualizar as faturas.
Basta colocar esse arquivo na raiz do site e acessar ele diretamente do navegador.

[paghiper_force_sync.zip](https://github.com/paghiper/whmcs/files/4071154/paghiper_force_sync.zip)

Ex: https://painel.site/paghiper_force_sync.php
