### ISSUE TITLE
Retorno automático não dá baixa na fatura

### ISSUE THREAD

**Issue by fabwebbr** [paghiper/whmcs#73]
Após atualizar para a última versão, o sistema parou de dar baixa automaticamente na fatura. O sistema cria a entrada/adição do pagamento mas não marca como pago.

Alguém passou por isso e pode nos dar uma luz?

**Comment by henriqueccruz** [comment]
Bom dia @fabwebbr,
Problema está no hook novo (para cancelamento de boletos não-pagos ao atualizar o valor total de uma fatura).
Para resolver temporariamente, basta comentar a linha 78 do arquivo /includes/hooks/cancel_paghiper_slip.php

Uma update corrigindo esse comportamento será lançada amanhã.

**Comment by fabwebbr** [comment]
> Bom dia @fabwebbr,
> Problema está no hook novo (para cancelamento de boletos não-pagos ao atualizar o valor total de uma fatura).
> Para resolver temporariamente, basta comentar a linha 78 do arquivo /includes/hooks/cancel_paghiper_slip.php
> 
> Uma update corrigindo esse comportamento será lançada amanhã.

Obrigado!

**Comment by henriqueccruz** [comment]
@fabwebbr, por favor atualize os arquivos da sua pasta /includes/hooks
Caso você tenha boletos não sincronizados, elaboramos este script pra atualizar as faturas.
Basta colocar esse arquivo na raiz do site e acessar ele diretamente do navegador.

[paghiper_force_sync.zip](https://github.com/paghiper/whmcs/files/4071154/paghiper_force_sync.zip)

Ex: https://painel.site/paghiper_force_sync.php
