### ISSUE TITLE
Arquivo PDF com segunda página em branco

### ISSUE THREAD

**Issue by deguirbr** [paghiper/whmcs#75]
Prezados, 

O plugin instalado em meu WHMCS é a versão 2.0.1.3.
Está acontecendo de se a fatura em PDF for para boleto, vai na primeira página o boleto e na segunda uma página em branco.
Se o modo de pagamento da fatura for Paypal por exemplo, ao invés de boleto, junto ao e-mail vai um arquivo PDF com uma página e ela está em branco.

Espero te auxiliado nos detalhes.

**Comment by henriqueccruz** [comment]
Bom dia.
Você provavelmente apagou todo o conteúdo do arquivo ao adicionar o bloco novo...
O bloco deve ser somente adicionado ao topo do arquivo, sem apagar o restante.
Mudamos isso na v2.1 e o bloco de integração ficou menor.

Basta colar o código abaixo antes do conteúdo existente do seu invoicepdf.tpl
`<?php require_once(dirname(__FILE__).'/../../modules/gateways/paghiper/inc/helpers/attach_pdf_slip.php'); ?>`
