### ISSUE TITLE
Erro no retorno automático versão 2.0.1.3

### ISSUE THREAD

**Issue by tonybdo** [paghiper/whmcs#76]
Olá, desde que instalei essa versão os boletos não estão sendo baixados de forma automática. Como posso resolver essa questão?

**Comment by eseixas** [comment]
Também estou com o mesmo problema.

**Comment by luispimenta** [comment]
também estou com esse problema, no painel do paghiper, poderia ter alguma forma de reenviar ou testar esses retornos !

**Comment by henriqueccruz** [comment]
Olá pessoal, por favor testem a atualização nova.
Caso ainda assim não consigam resolver o problema da baixa, entrem em contato com o suporte telefônico. Vamos pedir mais informações por lá (talvez até pedir credenciais temporárias de login) para entender melhor o problema.
