### ISSUE TITLE
Não Gera a Fatura!!!!

### ISSUE THREAD

**Issue by luizrenatodc** [paghiper/whmcs#79]
Então uso o Paghiper a algum tempo, resolvi instalar o plugin Whmcs Bridge no meu Wordpress, quando algum cliente tenta gerar a fatura pela pagina onde está o whmcs brige, ele não gera, aparece uma tela de erro, mais na área do cliente do whmcs, os clientes conseguem gerar a fatura normalmente sem erro, vocês podem me ajudar? Pagseguro e Mercado Pago funcionam de boa...

**Comment by luizrenatodc** [comment]
Fica assim:

Link do Whmcs: https://meusite/central/modules/gateways/paghiper.php?invoiceid=47&uuid=1&mail=meuemail@gmail.com  (Abre normal)

Link do Whmcs Bridge: https://meusite/cliente/js/?ajax=1&js=modules/gateways/paghiper.php?invoiceid=47&uuid=1&mail=meuemail@gmail.com   (Não Abre)

**Comment by divulgaabc** [comment]
Estou com mesmo erro no WHMCS 7.10.2

**Comment by henriqueccruz** [comment]
Olá @luizrenatodc 
O plugin não é compatível com o WHMCS Bridge, infelizmente. Os desenvolvedores do plugin não fornecem documentação e não respondem aos nossos contatos. E, para ajudar, o código-fonte do plugin deles é criptografado.
Podemos adicionar suporte a ele no futuro mas ainda é incerto.
