### ISSUE TITLE
Retorno

### ISSUE THREAD

**Issue by andrepmw** [paghiper/whmcs#8]
Olá o meu não funcionou o retorno automático, antes de eu atualizar funcionava perfeitamente, sabe me informar o que ocorre. Versão 7.1.0

**Comment by henriqueccruz** [comment]
Olá @andrepmw, você observou algum erro no log?
Quando um boleto é gerado, por exemplo, o log de transações informa que o boleto foi gerado?

**Comment by andrepmw** [comment]
O log do modulo: http://imgur.com/a/onFTu

**Comment by henriqueccruz** [comment]
Essa mensagem é relacionada a uma funcionalidade que estamos planejando para uma versão futura. Pelo que parece, o retorno automático está chegando, só não está sendo gravado na tabela que designamos na integração avançada.

Veja em uma fatura, se o log de "Boleto Gerado" está sendo inserido por favor.

**Comment by andrepmw** [comment]
Seria isso? http://imgur.com/a/RfyeD

**Comment by henriqueccruz** [comment]
Isso mesmo! Isso indica que o retorno automático está chegando até sua instalação normalmente. Amanhã seus boletos serão marcados como pagos normalmente, assim que o post da PagHiper for enviado.
Provavelmente o usuário sendo usado pro banco de dados não tem permissões pra criar uma tabela nova. Caso não queira usar a integração avançada, você pode desativar ou ignorar esse erro.

Se precisar de ajuda para preparar a tabela, por favor nos avise.

**Comment by andrepmw** [comment]
Ok, agradeço a atenção.

**Comment by henriqueccruz** [comment]
Seus boletos compensados hoje foram marcados como pagos normalmente?

**Comment by andrepmw** [comment]
Sim. Normalmente. Obrigado
