### ISSUE TITLE
não gera cobrança de multa e juros

### ISSUE THREAD

**Issue by carlosdfoz** [paghiper/whmcs#80]
Prezados configurei para multa e juros, mas somente atualiza o vencimento e não cobra 

print

https://nimb.ws/cpljib

**Comment by divulgaabc** [comment]
@carlosdfoz o juros e multa é aplicado direto no boleto após o pagto do cliente. O PagHiper manda esta info para o WHMCS e o valor é adicionado na fatura.

https://nimb.ws/bqYBit

**Comment by divulgaabc** [comment]
@henriqueccruz, boa tarde.
Creio que estou passando pelo mesmo problema que o @carlosdfoz, há alguns dias havia dito que a multa era aplicado direto no boleto, ok, mas o problema é que quando o cliente acessa o portal para pegar o boleto após vencido, o mesmo é gerado um novo, fazendo assim com que o antigo perca validade, e o mesmo pegando um novo não consegue cobrar a multa e juros.

@carlosdfoz é este problema que esta tendo? Percebi hoje, pois tinha alguns boletos vencidos, os clientes pagaram e não foi cobrado multa nem juros. Ao entrar no WHMCS vi que tinha mais de 1 boleto emitido!!!

**Comment by carlosdfoz** [comment]
> @henriqueccruz, boa tarde.
> Creio que estou passando pelo mesmo problema que o @carlosdfoz, há alguns dias havia dito que a multa era aplicado direto no boleto, ok, mas o problema é que quando o cliente acessa o portal para pegar o boleto após vencido, o mesmo é gerado um novo, fazendo assim com que o antigo perca validade, e quando ele pega um novo não é cobrado os juros e multa.
> 
> @carlosdfoz é este problema que esta tendo? Percebi isso hoje, pois tinha alguns boletos vencidos, os clientes pagaram e não foi cobrado multa nem juros. Ao entrar no WHMCS vi que tinha mais de 1 boleto emitido an mesma fatura, e o que o cliente pagou, era o que ele acessou no dia do pagamento (atrasado)!!!
> 
> WHMCS: 7.10.2

Abandonei o uso do paghiper, nao esxiste suporte ao modulo
realmente não cobra juros e multo
aconselho usar o juno.com.br

**Comment by henriqueccruz** [comment]
Bom dia pessoal
Update v2.1 aborda essa questão também. Peço que atualizem e abram novo ticket caso o problema persista.
