### ISSUE TITLE
Não faz a conversão de outras moedas para BRL

### ISSUE THREAD

**Issue by aldemaroc** [paghiper/whmcs#81]
Atualmente esse módulo não faz a conversão do valor da fatura para outras moedas, mesmo com a opção "Converter Para Processar" definida no WHMCS.

Para empresas que recebem em mais de uma moeda, isso permite que os clientes gerem um pedido em USD por exemplo e paguem o boleto em BRL sem nenhum tipo de conversão de moeda, efetivamente pagando apenas uma fração do valor da fatura.

Esse é um bug potencialmente crítico já que permite uso malicioso causando prejuízo financeiro para quem usa esse módulo.

**Comment by aldemaroc** [comment]
Mais detalhes:

Atualmente o módulo gera o boleto baseado no resultado da chamada na [API local do WHMCS](https://github.com/paghiper/whmcs/blob/master/modules/gateways/paghiper.php#L558), porém a API retorna o valor original da fatura, sem nenhum tipo de conversão de moeda, e [nem mesmo retorna em qual moeda a fatura está](https://requests.whmcs.com/topic/retrieve-invoice-currency).

Para evitar mais clientes utilizando essa falha para conseguir grandes "descontos" adicionamos o seguinte código acima da linha 558 para evitar que clientes com outras moedas possam gerar boletos.

```
        $postData = array(
			'clientid' => $user_id,
			'stats' => true,
		);
		$cliente = localAPI('GetClientsDetails', $postData, $whmcsAdmin);

        if($cliente['currency'] != '1') {
                $title = 'Boleto apenas disponível para BRL';
                $message = 'Apenas é possível pagamento por boleto bancário em Reais (BRL).<br>Entre em contato com o suporte para modificar a moeda de sua conta.';
                echo print_screen($ico, $title, $message);
                exit();

        }
```

**Comment by henriqueccruz** [comment]
Boa sugestão, @aldemaroc 
Vamos incorporar isso de forma definitiva mo módulo.

**Comment by henriqueccruz** [comment]
Corrigido na v2.1
Caso precise de suporte novamente, peço a gentileza de abrir novo ticket.
