### ISSUE TITLE
Problema com CNPJ e Nome da Empresa

### ISSUE THREAD

**Issue by MarksEliel** [paghiper/whmcs#84]
Mesmo com CNPJ preenchido, no boleto sai o nome do cliente, preciso que saia o nome da Empresa.

**Comment by MarksEliel** [comment]
Lembrando que eu utilizo o mesmo campo CPF para CNPJ

**Comment by henriqueccruz** [comment]
@MarksEliel - Temos uma update que resolve esse problema.
Até amanhã lançaremos aqui no repositório.

**Comment by henriqueccruz** [comment]
Corrigido na v2.1
Caso precise de suporte novamente, peço a gentileza de abrir novo ticket.
