### ISSUE TITLE
Pagamento duplicado

### ISSUE THREAD

**Issue by russo1** [paghiper/whmcs#85]
Boa tarde, uso a versão 2.0.3 e hoje percebi que o problema de duplicar o pagamento e adicionar saldo na conta do cliente ainda ocorre, mesmo que bem raro mas ocorre..

https://prnt.sc/vpyiu2
https://prnt.sc/vpyo6a
https://prnt.sc/vpyom6

**Comment by henriqueccruz** [comment]
@russo1 - Problema ainda persiste?
Queremos acompanhar seu caso.

**Comment by henriqueccruz** [comment]
Por falta de interação, estamos fechando este ticket.
Caso precise de suporte com alguma outra questão ou queira retomar o assunto, peço a gentileza de abrir outro ticket.
