### ISSUE TITLE
PIX paghiper

### ISSUE THREAD

**Issue by souzadavi** [paghiper/whmcs#86]
É possível criar um novo modulo com a opção de pagamento por PIX? Notei que tem um QR code no boleto para o PIX, será que é possível imprimir esse QR code direto na fatura dentro do WHMCS?

Obrigado.

**Comment by henriqueccruz** [comment]
@souzadavi Temos uma update ampla em homologação, que oferece método de pagamento separado para PIX, anexa QR code na comunicação por e-mail e nas faturas PDF.
Até amanhã lançamos aqui no repositório

**Comment by henriqueccruz** [comment]
Corrigido na v2.1
Caso precise de suporte novamente, peço a gentileza de abrir novo ticket.
