### ISSUE TITLE
PIX em Branco

### ISSUE THREAD

**Issue by jaison** [paghiper/whmcs#88]
Ao clicar em "Pagar usando Pix" abre uma página em branco.
Testei o {$codigo_pix} no template de e-mail e não retorna nada.

Já o boleto funciona perfeitamente como sempre.
Alguém tem alguma idéia do que pode ser?

**Comment by henriqueccruz** [comment]
Boa tarde @jaison 

Só pra facilitar o diagnóstico:
- PIX é emitido normalmente no checkout?
- Tem alguma informação referente a criação/modificação da nossa tabela de controle no item Transações > Log dos portais ?
- Adicionalmente, checa se o hook novo carregado corretamente (/includes/hooks/create_paghiper_pix.php)

Aguardamos seu retorno para seguir com o diagnóstico e resolução do problema

**Comment by jaison** [comment]
Encontrei o problema 

"json => 
    pix_create_request => 
        result => reject
        response_message => O valor do pix esta abaixo do minimo permitido de R$ 3,00.
        http_code => 200
post => "
Testei com uma fatura de valor maior que o mínimo e funcionou como deveria.


No meu caso, raramente há alguma fatura inferior a R$3.00, mas é possível existir caso algum cliente use seu saldo e fique um residual abaixo do mínimo de R$3.00.
Então creio que seria bom ter uma mensagem de aviso quando isso ocorrer e não uma página em branco.

**Comment by henriqueccruz** [comment]
Boa sugestão, vamos implementar.

**Comment by jaison** [comment]
Obrigado pela agilidade!
Outra sugestão é no retorno está marcado que foi pago com boleto ao invés do Pix. Seria bom diferenciar.

**Comment by henriqueccruz** [comment]
Repositório atualizado, @jaison 
Se precisar de suporte com outros itens, peço a gentileza de abrir outro ticket.
Obrigado!
