### ISSUE TITLE
Pagina em branco para contas com cpf incorreto ou sem cpf

### ISSUE THREAD

**Issue by russo1** [paghiper/whmcs#94]
Boa tarde, o sistema está mostrando uma pagina em branco quando a conta não está com cpf preenchido ou quando está com um cpf invalido 
Em um modulo antigo da paghiper, me recordo que exibia uma mensagem informando o erro no cpf, assim fica mais fácil para o cliente e para nós administradores identificar o problema, como ocorreu hoje achei que fosse alguma indisponibilidade no sistema até verificar que era um erro de digitação feito pelo cliente ao preencher o cpf
https://prnt.sc/whkppw

Obs: o problema ocorre no modulo pix e no modulo de boletos

**Comment by linkoficial** [comment]
Mesmo problema aqui, seria interessante exibir o motivo do erro ao usuário.

**Comment by jeantmsantos** [comment]
Olá pessoal,

Estou tendo esse problema também, vocês efetuaram algum procedimento para resolver? Pois aqui com ou sem CPF o problema acontece.

**Comment by andersonosn** [comment]
Isso não será resolvido?
Antes de atualizar para esse novo módulo, mostrava para o cliente que o CPF estava em branco ou incorreto... agora fica página em branco e o cliente reclamando que tem erro em nosso painel, pois o módulo parou de avisar...

Será resolvido? É crucial um update para resolver

**Comment by henriqueccruz** [comment]
Bom dia pessoal
Sim, teremos um update nos próximos dias abordando essas questões. Informo assim que estiver disponível para download.

**Comment by andersonosn** [comment]
> Bom dia pessoal
> Sim, teremos um update nos próximos dias abordando essas questões. Informo assim que estiver disponível para download.

Será de extremo valor!
Usamos uma metodologia de pré-cadastro sem preenchimento de dados pessoais (apenas nome, email, telefone)... então as vezes (maioria das vezes rsrs) o cliente tenta realizar o pagamento sem completar os dados cadastrais e cai na tela branca...

Vamos aguardar ansiosamente, obrigado!

**Comment by andersonosn** [comment]
> Bom dia pessoal
> Sim, teremos um update nos próximos dias abordando essas questões. Informo assim que estiver disponível para download.

Olá!
Existe uma previsão sobre essa essa correção? Informou que seria nos próximos dias e completamos mais 1 mês.

Peço desculpas, mas infelizmente está insustentável continuar com o PagHiper devido ao problema com usuários.

Agradecemos por um posicionamento real

Obrigado.

**Comment by OneHitX** [comment]
> Bom dia pessoal
> Sim, teremos um update nos próximos dias abordando essas questões. Informo assim que estiver disponível para download.

Pelo visto a PagHiper está abandonada, uma correção tão simples não foi feita a meses...

**Comment by souzadavi** [comment]
Olá pessoal, boa tarde. Este erro tbm nos causa muito problema, atualizamos o plugin da paghiper para resolver este problema. Demos um pull request no repositório para o pessoal da Paghiper aprovar. Agora depende deles, se não quiser esperar por eles basta pegar as alterações em: https://github.com/paghiper/whmcs/pull/102/commits/62a027405344e768d712895804c9134bc0dd7eb6 e alterar no modulo de vcs... boa sorte!

**Comment by henriqueccruz** [comment]
Olá prezados.
O fix demorou um pouco mais a sair por que fomos incorporando outros fixes e melhorias ao release.
Incorporamos parte do pull request enviado pelo amigo @souzadavi ao trabalho que ja estava em curso. Outra novidade desse novo release é que temos um novo hook de validação de CPF/CNPJ ja no checkout. Isso evita que o cliente faça todo o processo para só ver um aviso relacionado a dados incorretos na tela final.

Agradecemos a todos pela paciência. Se precisarem de suporte, peço a gentileza de abrirem novo ticket.
