### ISSUE TITLE
PHP 7.4 support: Deprecated: Unparenthesized

### ISSUE THREAD

**Issue by webzan** [paghiper/whmcs#95]
Prezados,

Arquivo /modules/gateways/paghiper/inc/helpers/process_payment.php on line 41 com a seguinte msg de erro:

Deprecated: Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)`

Poderiam verificar por gentileza?

**Comment by henriqueccruz** [comment]
Boa tarde @webzan 

Não se trata de um erro, é só uma ressalva do PHP. Corrigiremos isso no próximo update.
Obrigado por reportar!

**Comment by webzan** [comment]
Ótimo, obrigado pelo retorno.

**Comment by henriqueccruz** [comment]
Demorou um pouco mais que o esperado por que fomos incorporando outros fixes e melhorias.
Finalmente está disponível na v2.2

Obrigado por reportar!
