### ISSUE TITLE
Campos obrigatórios.

### ISSUE THREAD

**Issue by yanzeraa** [paghiper/whmcs#96]
Minha duvida é a seguinte, quais campos de cadastro são realmente usados pelo módulo? criei um campo personalizado, mas quando vou salvar o CPF diz não ser válido, o módulo usa algum outro campo para pegar informação? pois em meu WHMCS inutilizei todos os campos de endereço.

Obrigado!

**Comment by henriqueccruz** [comment]
Bom dia, @yanzeraa 
Mesmo com CPF válido, seu WHMCS informa que o CPF é inválido? Me parece ter alguma etapa de validação (nosso plugin só fará isso a partir do próximo update)
Tem algum endereço que possamos testar?

**Comment by henriqueccruz** [comment]
Por falta de interação, estamos fechando este ticket.
Caso queira retomar a questão, peço a gentileza de abrir outra issue.
