### ISSUE TITLE
Erro no plugin PIX - PagHiper

### ISSUE THREAD

**Issue by egalvani** [paghiper/whmcs#97]
O Plugin funciona perfeitamente até aparecer o erro no site:

Erro ao salvar a ação: Table './psilo15_wp/wp_actionscheduler_actions' is marked as crashed and last (automatic?) reapir failed.

Depois disso eu preciso entrar no PhpMyAdmin e truncar a tabela, depois que eu limpo ela o checkout do site volta a funcionar e a tabela volta a funcionar.

O que será que pode ser?

**Comment by henriqueccruz** [comment]
Olá @egalvani 
Seu erro ocorre na plataforma Woocommerce, aqui é o forum de suporte do plugin Paghiper para WHMCS

De qualquer maneira, respondi sua postagem no grupo do Woocommerce. Para facilitar, vou responder aqui novamente:
Esse é um erro relacionado a corrosão de tabelas no MySQL. O servidor MySQL pode estar sendo interrompido enquanto uma operação é executada, isso pode corromper tabelas. Isso explica o fato de voltar a funcionar imediatamente após você truncar a tabela. 

Seria legal checar com seu provedor de hospedagem, ao analisar os logs eles vão poder diagnosticar melhor.
Fechando este ticket ja que não é referente a este plugin. Você pode usar o repositório do Woocommerce aqui no Github da Paghiper (https://github.com/paghiper/woocommerce-paghiper) ou usar o fórum de suporte do plugin no repositório do Wordpress (https://wordpress.org/support/plugin/woo-boleto-paghiper/)

Obrigado!
