### ISSUE TITLE
Boleto em Branco

### ISSUE THREAD

**Issue by ricardomecca** [paghiper/whmcs#98]
Olá,

Quando o cliente vai acessar o boleto pelo WHMCS, a página que deveria emitir o boleto fica em branco.
Estou usando o WHMCS 8.0 e o PHP 7.2

**Comment by russo1** [comment]
eu já relatei esse problema mas até hoje não deram nenhuma posição sobre o mesmo

isso acontece se a conta do usuário não estiver com cpf preenchido ou se estiver com um cpf invalido

**Comment by ricardomecca** [comment]
Então, os dados do cliente estão certos kk. O módulo que está bugado provavelmente

> eu já relatei esse problema mas até hoje não deram nenhuma posição sobre o mesmo
> 
> 
> 
> isso acontece se a conta do usuário não estiver com cpf preenchido ou se estiver com um cpf invalido

**Comment by henriqueccruz** [comment]
@ricardomecca , @russo1 
Pessoal, vocês conseguem mandar um e-mail pra suporte@paghiper.com por favor?
Vamos pedir mais detalhes e escalar o caso até a equipe de dev por lá. Por aqui ficamos meio restritos no suporte.
Se vocês tiverem logs, encaminhem no e-mail também, por favor.

Vou deixar o ticket aberto para atualizar por aqui também.
Obrigado!

**Comment by ricardomecca** [comment]
Cansei de mandar e-mails relatando e nada ocorrer

> @ricardomecca , @russo1 
> 
> Pessoal, vocês conseguem mandar um e-mail pra suporte@paghiper.com por favor?
> 
> Vamos pedir mais detalhes e escalar o caso até a equipe de dev por lá. Por aqui ficamos meio restritos no suporte.
> 
> Se vocês tiverem logs, encaminhem no e-mail também, por favor.
> 
> 
> 
> Vou deixar o ticket aberto para atualizar por aqui também.
> 
> Obrigado!

**Comment by henriqueccruz** [comment]
@ricardomecca 
Me fala o endereço de e-mail usado pra enviar o pedido de suporte por favor

**Comment by ricardomecca** [comment]
suporte@rvmecca.com.br

> @ricardomecca 
> 
> Me fala o endereço de e-mail usado pra enviar o pedido de suporte por favor
