### ISSUE TITLE
Módulo não está registrando as transações e realizando quitação automática de faturas

### ISSUE THREAD

**Issue by ricardomecca** [paghiper/whmcs#99]
Testei o último release como o anterior e o módulo funciona corretamente, exceto quando o boleto é gerado e há movimentações de quitação e demais ações na fatura, não tendo nenhum log na fatura de transações.

WHMCS que estou usando é na v8 e o módulo está na v2.0.3

**Comment by henriqueccruz** [comment]
Boa tarde @ricardomecca 
Obrigado por reportar. Queremos investigar mais de perto o problema. Consegue mandar um e-mail com o link da sua instalação do WHMCS para suporte@paghiper.com ?

Damos sequência por lá e, conforme resolvermos seu caso, atualizamos este ticket.

**Comment by ricardomecca** [comment]
Alguma novidade?
PagHiper está deixando a desejar, se continuar assim vou ter que recorrer a outra plataforma de pagamentos

**Comment by henriqueccruz** [comment]
Você chegou a enviar o e-mail para suporte@paghiper.com como solicitado?

**Comment by ricardomecca** [comment]
Ah não, sacanagem isso. Enviei 2 e-mails e ainda me perguntam se enviei? Aí não dá sinceramente vou ter que recorrer a outro meio de pagamento

**Comment by henriqueccruz** [comment]
@ricardomecca Me fala o endereço de e-mail do qual as mensagens foram enviadas por favor.
Damos sequência por lá e atualizo este ticket conforme progredirmos.

**Comment by ricardomecca** [comment]
mecca@rvmecca.com.br

**Comment by henriqueccruz** [comment]
@ricardomecca , você nos faria um favor extra? 😬
Realmente não encontramos seus e-mails por algum motivo. Usando seu e-mail de cadastro na Paghiper, você encaminharia esses e-mails para integracao@paghiper.com por favor?

Entendemos que talvez o problema seja frustrante mas queremos resolvê-lo. 
Estamos tratando seu caso como prioridade.

**Comment by ricardomecca** [comment]
Foi enviado pelo e-mail que utilizo no PagHiper, encaminhei via financeiro@rvmecca.com.br

**Comment by henriqueccruz** [comment]
Certo... Buscando pelo e-mail conseguimos achar seu cadastro. Notamos duas coisas:

1. A URL de retorno (notificação de movimentação transacional) que sua instalação do WHMCS está gerando começa com http://... O que me faz crer que a URL-base da sua configuração precisa ser ajustada pra https://
2. Enviamos uma notificação manual para testar se o problema é esse, seu WHMCS respondeu com erro 500. Neste item, seria legal ativar os logs do WHMCS e olharmos lá o que ocorre.
3. Adicionalmente: Existe alguma chance de vocês terem uma ferramenta como mod_security, cpGuard, IPDB ou semelhantes ativos no servidor?

**Comment by ricardomecca** [comment]
Ótimo, o erro de http:// foi corrigido. Ativei todos os debugs e logs possíveis para verificar algum erro, se possível tentar realizar mais um procedimento por parte de vocês

**Comment by ricardomecca** [comment]
O boleto foi gerado, normalmente, mas não registra a transação na fatura como não realiza a baixa por pagamento

**Comment by henriqueccruz** [comment]
Hm. Certo, sobre o SSL ficou tudo certo.

Veja o que acha pra gente nos logs (exceto erros 404) por favor.

Com isso, achamos outro problema (sobre os erros 404): Vejo que aparentemente você emitiu algumas transações com a versão nova do módulo mas nos disse que está usando a v2.0.3 (fez downgrade?)
Com isso, as URLs de retorno das transações estão apontando para arquivos da v2.1 que não existem mais. Consegue atualizar para a v2.1?

**Comment by ricardomecca** [comment]
Removi todos os arquivos e dados referentes aos módulos do PagHiper no WHMCS, baixei novamente a última versão do módulo de vocês e instalei/configurei no WHMCS.

**Comment by henriqueccruz** [comment]
Certo, aparentemente tudo foi resolvido com essa intervenção.
Re-enviamos a notificação de fatura paga #1369 e não identificamos problemas. Pode confirmar se a baixa ocorreu como esperado?
Ja com relação ao PIX, nossa notificação não foi processada por conta do gateway PIX estar desativado. Caso queira reativá-lo, a baixa deve ocorrer normalmente.

**Comment by ricardomecca** [comment]
Certo, a transação foi registrada. Estarei ativando o PIX futuramente. Agradeço pelo atendimento

**Comment by henriqueccruz** [comment]
Conte com nosso suporte sempre. :)

**Comment by ricardomecca** [comment]
Olá novamente,

Ativei a parte PIX do módulo, a fatura foi gerada e tudo mais só que não gerou a transação no WHMCS, é normal isso?

**Comment by AlexandreLage** [comment]
Olha, existe um movimento aqui.
Fico feliz. Vai PagHiper!
